### ISSUE TITLE
proposal: test context builder (test helper function)

### ISSUE THREAD

**Issue by kpurdon** [go-chi/chi#134]
I've switched a personal project over to chi and have been working on converting my integration tests. I've found myself repeating this chunk of code in tests quite often. Each test case (table tests) provides a list of params `tc.params` which is a `map[string]interface{}` that I load into the URLParams context. This allows me to test functionality based on different param values passed to a handler.

```
req, err := http.NewRequest("METHOD", "/path/:variable", nil)
assert.NoError(err, tc.description)

rctx := chi.NewRouteContext()
for k, v := range tc.params {
	rctx.URLParams.Add(k, v)
}
ctx := context.WithValue(context.Background(), chi.RouteCtxKey, rctx)

w := httptest.NewRecorder()
SomeHTTPHandler(w, req.WithContext(ctx))
```

While I could certainly extract the building of a `context.Context` in my own project, I think it would be a nice addition to chi. I am imagining something like:

```
func NewTestContext(ps map[string]interface{}) context.Context {
	rctx := NewRouteContext()
	for k, v := range ps {
		rctx.URLParams.Add(k, v)
	}

	return context.WithValue(context.Background(), RouteCtxKey, rctx)
}
```

This would change my code snippet to:

```
req, err := http.NewRequest("METHOD", "/path/:variable", nil)
assert.NoError(err, tc.description)

w := httptest.NewRecorder()
SomeHTTPHandler(w, req.WithContext(chi.NewTestContext(tc.params)))
```

I would be happy to provide a PR for this addition if your open too it. Thanks!

**Comment by pkieltyka** [comment]
@kpurdon thanks for the proposal. I think its a good idea, but I'm always trying to keep the chi project as minimal as possible. I think this along with other common test helpers would make for a good auxiliary testing package for chi.

**Comment by kpurdon** [comment]
> I'm always trying to keep the chi project as minimal as possible

👍 

Thanks for the response. If you have an idea for how you'd like this testing package to look (and a potential name (`chi/chitest`?)) I'd be happy to drop a first pass PR. Let me know.

**Comment by jlovison** [comment]
I do think it'd be a big help to people adopting this package to have a "testing" section in the readme about how to properly setup chi in tests. @kpurdon's setup in his first code block is not intuitive without seriously looking under the hood at the chi package. Other aspects of integration are pretty easy to pick up from a glance at the readme, but integration in tests is currently a bit of a head scratcher.

**Comment by pkieltyka** [comment]
hey guys, with the recent move to a dedicated org for chi projects to https://github.com/go-chi we can start thinking about a project specific to testing chi APIs

**Comment by brycereitano** [comment]
With v3 this method of testing won't work since URLParams is an unexported type and has removed `Add` method. Looking forward to some testing example.

**Comment by kpurdon** [comment]
Closing since this would be implemented elsewhere and changes with V3 anyway.

**Comment by pkieltyka** [comment]
thanks gents. @brycereitano its a good point - I was circling the decision if it makes sense to make URLParams writable, testing is a good example where it is helpful. I'll look into it again thanks
