### ISSUE TITLE
Named wildcard params

### ISSUE THREAD

**Issue by dobegor** [go-chi/chi#174]
Wildcard patterns aren't very useful without ability to actually retrieve them, i.e. with `chi.UrlParam`.

Maybe we can use the following pattern syntax for this:
`/my/url/*param1`
and retrieve it later with `chi.UrlParam("param1")`.

This won't break any existing code as chi doesn't do any check after `*` symbol, i.e. with pattern set to `qwe*iop` both `qwe1iop` and `qwedsf` are wired to the handler.

**Comment by pkieltyka** [comment]
why not just use, `/my/url:param1` then?

**Comment by dobegor** [comment]
i.e. your parameter contains slashes, i.e. it's a storage key:
`/storage/folderID/userID/somekey`
and you don't want to hard-code key format, a wildcard is a nice choice, but there's no way to get the matched parameter other than getting full request path, stripping everything and etc.

That would also require handler to know the prefix to strip off, and it somewhat breaks the abstraction of an app.

Named wildcard params, if possible, would solve this.
The proposed syntax (`/*param`) is the same in Rails, for example.

**Comment by pkieltyka** [comment]
yea I agree with you.. I think a better solution is to change from `:param` syntax to `{param}` which would solve the delimiter problem and you can place them anywhere on the route.

**Comment by dobegor** [comment]
If syntax is `{param}`, then how would these patterns be handled?
Pattern 1: `/{param}` // can match both /someparam and /someparam/something/something
Pattern 2: `/{param}/{param2}` // ??

IMO, wildcards would be simpler to implement and to understand.

**Comment by pkieltyka** [comment]
submit a PR then :) but, make sure you also include before/after benchmarks

**Comment by pkieltyka** [comment]
this isn't something I have time for anytime soon, but I'd love some help from other users to keep making chi better.

**Comment by dobegor** [comment]
Turns out it's already implemented [here](https://github.com/pressly/chi/blob/master/tree.go#L371).
Perhaps it's worth to add it to documentation :)

**Comment by polyfloyd** [comment]
For anyone else looking for how to get the matched path part, the variable is named `*`:
```
thing := chi.URLParam(r, "*")
```
