### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by kuronyago** [go-chi/chi#204]
Hello, sorry for the stupid question, but how correctly implement qzip compression

`r.Use(middleware.Compress(6, "gzip"))`
and nothing:

![screenshot from 2017-06-12 19-52-40](https://user-images.githubusercontent.com/25136476/27045153-c3e0dd38-4fa8-11e7-82de-a903b00c6e20.png)

**Comment by VojtechVitek** [comment]
Try `r.Use(middleware.DefaultCompress)`

**Comment by kuronyago** [comment]
similar result

**Comment by VojtechVitek** [comment]
Pls provide full example code. `r.Use(middleware.DefaultCompress)` should work.

**Comment by kuronyago** [comment]
`package main

import (
	"github.com/pressly/chi"
	"github.com/pressly/chi/middleware"
	"html/template"
	"net/http"
	"path"
	"path/filepath"
)

var tpl = template.Must(template.ParseGlob("templates/*"))

func mainpage(w http.ResponseWriter, r *http.Request) {
	tpl.ExecuteTemplate(w, "mainpage.tpl", nil)
}

func main() {
	r := chi.NewRouter()
	//r.Use(middleware.Compress(6, "gzip"))
        r.Use(middleware.DefaultCompress)
	r.Get("/", mainpage)
	workDir, _ := os.Getwd()
	filesDir := filepath.Join(workDir, "static")
	r.FileServer("/static", http.Dir(filesDir))
	http.ListenAndServe(":80", r)
}
`

**Comment by pkieltyka** [comment]
@kuronyago thanks for that. the `FileServer` is the one exception which is not like any other routing method. 

@vojtechvitek perhaps we should remove the `FileServer` method as there has been a lot of confusion with it, and instead offer a helper snippet for people to write their own

**Comment by VojtechVitek** [comment]
@pkieltyka sounds good to me, we can remove it for v3.0 and provide an example instead.

---

@kuronyago you'd have to set Content-Type header, so the Compress middleware knows whether it can compress the payload or not.

```go
func mainpage(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("Content-Type", "text/html") // will be compressed, since it's in https://github.com/pressly/chi/blob/5b7406a71dbb35d4f59b0b48e68cd9f9256f5262/middleware/compress.go#L22-L32
    tpl.ExecuteTemplate(w, "mainpage.tpl", nil)
}
```

And same for the `r.FileServer()`, it would have to set the Content-Type header accordingly. Not sure what happens under the hood by default.
