### ISSUE TITLE
Just curious: why the org is changed?

### ISSUE THREAD

**Issue by hsluoyz** [go-chi/chi#210]
I noticed that the org has been changed from pressly to go-chi. I'm curious why?

**Comment by pkieltyka** [comment]
hey @hsluoyz - there are many subpkgs id like to include around chi, without bloating the core library, so my thinking was a clear and dedicated org for chi related subpkgs would be an easy way to organize those projects. Soon I will be moving other pkgs to go-chi org for jwt auth, logging, auth, raml-based doc generation, shutdown signaling, etc. For example, as proposed by #212 it also makes sense to move render into its own repo as well under go-chi org. And finally, with the release of v3, I felt it was the right time to do it as v3 introduce other compatibility changes with the routing syntax, so I had done it all in one shot.
