### ISSUE TITLE
Allow to range on UrlParams

### ISSUE THREAD

**Issue by hectorj** [go-chi/chi#211]
Hi :slightly_smiling_face: !

Before v3, I used to be able to do something like this:

```go
for i := range chiContext.URLParams {
	span.SetTag("urlparam."+chiContext.URLParams[i].Key, chiContext.URLParams[i].Value)
}
```

Basically a middleware logging **every** URLParam, no matter the route.

But now `chi.Context.URLParams` is a `[]routeParams`: a slice of unexported struct type with unexported fields.

Is there a way to range on all URLParams' `key, value` in v3+ ? Is this something you would consider supporting again?

Thanks

**Comment by pkieltyka** [comment]
Sure I'll look into it soon

**Comment by pkieltyka** [comment]
hey @hectorj please let me know how this works out for you: 25201e8a886f7ef210501dfa55759d4c1fdf0cce

I've exported the URLParams underlying type so you can traverse it. You'll have to work with the new data structure, but the access is there.
