### ISSUE TITLE
Proposal: Split render out into it's own package

### ISSUE THREAD

**Issue by lwc** [go-chi/chi#212]
Now that you have the `go-chi` org is it worth thinking about splitting `render` out into it's own package?

**Comment by pkieltyka** [comment]
interesting idea, I think this makes sense.

**Comment by VojtechVitek** [comment]
SGTM

**Comment by pkieltyka** [comment]
Moved `render` and `docgen` to https://github.com/go-chi/

Links:
https://github.com/go-chi/render
https://github.com/go-chi/docgen

**Comment by VojtechVitek** [comment]
Warning: I plan to break the API in the new docgen pkg.
