### ISSUE TITLE
Just a Chinese translate!

### ISSUE THREAD

**Issue by muei** [go-chi/chi#214]
`go-chi`够吃，够吃就够了！
大道至简！

**Comment by Xuanwo** [comment]
`够吃` in Chinese means `enough to eat`.

> I have no idea for this translate, just a explain.

**Comment by muei** [comment]
通俗易懂，诙谐幽默，又不失寓意，斯以为可也！
😆，其实我想说
`go-chi` is nice

**Comment by venliong** [comment]
chi和echo/beego比起来，开发时会不会麻烦很多？
感觉从开发速度上比较的话，beego/macaron>echo/gin>chi/pure。
iris开发也很方便，就是编译出来的文件大很多。

**Comment by muei** [comment]
大而全 or 小而美
看个人喜好！
