### ISSUE TITLE
Parameter with suffix fails to match

### ISSUE THREAD

**Issue by niklasj** [go-chi/chi#217]
Hi,

I noticed that patterns with parameters with tails other than / fail to match when the tail character occurs more than once in the suffix. For example, the pattern `/{foo}.json` matches `/a.json` as expected, but fails to match `/a.b.json`.

**Comment by niklasj** [comment]
[Here's a patch](https://github.com/go-chi/chi/files/1113403/suffix_test.patch.txt) with tests for a (slightly contrived) scenario that showcases the issue. Routes with different handlers are added to: 

- /archive/{file}.zip
- /archive/{file}.tar.gz
- /archive/{file}.{ext}

At the moment filenames containing a dot all end up in the third handler, even when they have a suffix .zip or .tar.gz.

**Comment by pkieltyka** [comment]
hey @niklasj thanks for the details.

parameter values in chi cannot contain the trailing character. For example in the routing path

`/articles/{file}.{ext}` the "file" param cannot contain a "." in it, as it considers the "." to be the terminating character of the param value. If you're looking for a customized handling of extensions, try out the URLFormat middleware (https://github.com/go-chi/chi/blob/master/middleware/url_format.go) or adapt it to suit your needs
