### ISSUE TITLE
HTTP method routing bug with overlapping static and parameter paths

### ISSUE THREAD

**Issue by dobegor** [go-chi/chi#220]
Given these endpoints:
```
r.Get("/users/:userId", ShowUser)
r.Put("/users/me", EditUserProfile)
```
Request `GET /users/me` fails with 405 Method Not Allowed, which obviously isn't true.

**Comment by dobegor** [comment]
Small program to reproduce:
```
package main

import (
	"fmt"
	"github.com/go-chi/chi"
	"net/http"
)

func main() {
	r := chi.NewRouter()

	r.Get("/users/{userId}", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("end1")
	})

	r.Put("/users/me", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("end2")
	})

	http.ListenAndServe(":9999", r)
}
```

**Comment by kendellfab** [comment]
I observed something like this as well.  The uri with parameters is sent to the wrong handler, so the parameters are pulled out of the uri incorrectly.

package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewMux()

	r.Get("/comment/{slug}", func(w http.ResponseWriter, r *http.Request) {
		slug := chi.URLParam(r, "slug")
		id := chi.URLParam(r, "id")
		fmt.Println("SLUG:", slug, " ID:", id)
		fmt.Fprint(w, "SLUG:", slug, " ID:", id)
	})

	r.Delete("/comment/{id}", func(w http.ResponseWriter, r *http.Request) {
		slug := chi.URLParam(r, "slug")
		id := chi.URLParam(r, "id")
		fmt.Println("SLUG:", slug, " ID:", id)
		fmt.Fprint(w, "SLUG:", slug, " ID:", id)
	})

	http.ListenAndServe(":3000", r)
}

Expected:
GET /comment/first-page -> SLUG:first-page ID:
DELETE /comment/first-page -> SLUG: ID:first-page

Actual:
GET /comment/first-page -> SLUG: ID:first-page
DELETE /comment/first-page -> SLUG: ID:first-page

**Comment by pkieltyka** [comment]
Interesting, something with the method routing is going on. I'll have a peak soon.

**Comment by Advoskr** [comment]
I'm also dealing with this issue :( Hope you'll find solution soon. Here's what i have in my routing setup:
r.Post("/Dictionaries/{alias}", func(w http.ResponseWriter, r *http.Request) {
			alias := chi.URLParam(r, "alias")
})
r.Post("/Dictionaries/{alias}/Columns/{columnAlias}/{columnName}", func(w http.ResponseWriter, r *http.Request) {
			alias := chi.URLParam(r, "alias")
			columnAlias := chi.URLParam(r, "columnAlias")
			columnName := chi.URLParam(r, "columnName")
                        //some logic here
		})
Second return 404 :(
I'm sorry for my markup...

**Comment by pkieltyka** [comment]
Resolved by https://github.com/go-chi/chi/commit/49e7138cabd9e374dcbf1a3b56d3ba4a459763e2
