### ISSUE TITLE
Routing context using different URLParam name

### ISSUE THREAD

**Issue by itsjamie** [go-chi/chi#221]
Chi version 2.1.0

We had routes registered in the Chi router like so..

```go
router.With(
	playbackMW.NetworkReadOnly,
	playbackMW.ValidatePlaybackToken,
	playbackMW.LoadPlaylistMetadata,
).Get("/playlists/:networkID/:playlistID/meta", playbackHandlers.handlePlaylistMeta)

router.With(
	Deprecate,
	playbackMW.NetworkReadOnly,
	playbackMW.ValidatePlaybackToken,
	playbackMW.PrivateVideoPlayback,
).Get("/playlists/:networkID/:resourceID", playbackHandlers.handleMasterPlaylists)
```

When you output the route context it appears to be URL parameter name from the earlier route when parsing the playlist.

```go
(*chi.Context)(0xc4200a8fa0)({
 URLParams: (chi.params) (len=2 cap=2) {
  (chi.param) {
   Key: (string) (len=9) "networkID",
   Value: (string) (len=36) "7892184f-4613-44fb-9ae3-8ed726dedc3d"
  },
  (chi.param) {
   Key: (string) (len=10) "playlistID",
   Value: (string) (len=41) "6b12ef19-37ee-4236-a5cb-f10a5c3f877d"
  }
 },
 RoutePath: (string) "",
 RoutePattern: (string) (len=33) "/playlists/:networkID/:resourceID",
 RoutePatterns: ([]string) (len=1 cap=1) {
  (string) (len=33) "/playlists/:networkID/:resourceID"
 }
})
```

**Comment by itsjamie** [comment]
We've resolved it by switching them both to `:resourceID` but is there a better way?

**Comment by pkieltyka** [comment]
hey @itsjamie - the syntax changed from :param to {param} - did you have a chance to review the release notes? https://github.com/go-chi/chi/blob/master/CHANGELOG.md#v300-2017-06-21

let me know

**Comment by itsjamie** [comment]
I'll update it to use chi v3 and see if we get the same behaviour. Thanks.

**Comment by pkieltyka** [comment]
Oh, I see your issue now. Yes, this was a bug fixed in v3 :) see https://github.com/go-chi/chi/issues/179 for list of things fixed

**Comment by itsjamie** [comment]
@pkieltyka Thank you very much for telling me it was fixed in v3. The change was pretty minimal for us, and it's fixed now!

💯
