### ISSUE TITLE
A lot of docgen functions are not documented

### ISSUE THREAD

**Issue by JensRantil** [go-chi/chi#225]
Background: I was browsing https://godoc.org/github.com/go-chi/docgen to understand the different ways I could output API.

Problem: Most functions were/are undocumented.

Expected: They were documented and I could learn about what they do.

Proposed solution: Document them :)

**Comment by VojtechVitek** [comment]
Work in progress ;)

**Comment by JensRantil** [comment]
Closing this. See https://github.com/go-chi/docgen/issues/2 instead.
