### ISSUE TITLE
Generate API in Swagger format

### ISSUE THREAD

**Issue by JensRantil** [go-chi/chi#226]
[Swagger/OpenAPI](https://swagger.io) is a very popular format for documenting, and generating clients, for APIs. Has there been any discussions about supporting Swagger generation? I couldn't find any issue for it.

**Comment by VojtechVitek** [comment]
I'm working on RAML docgen right now for https://github.com/go-chi/docgen. Please open a new issue in the new project.

Swagger/OpenAPI format is very similar, it shouldn't be that hard to tweak the code once I have it working.

**Comment by pkieltyka** [comment]
please open in docgen repo

**Comment by afidegnum** [comment]
How far with this?

**Comment by marrow16** [comment]
You could try https://github.com/go-andiamo/chioas
