### ISSUE TITLE
Support route pattern quantity match (i.e. curly braces in regex expression)

### ISSUE THREAD

**Issue by craigjackson** [go-chi/chi#230]
Attempting to use routes that specify the quantity to match in regex does not work. This looks to be related to the way finding curly braces (i.e. `{` and `}`) works in pattern segments:

https://github.com/go-chi/chi/blob/49e7138cabd9e374dcbf1a3b56d3ba4a459763e2/tree.go#L628

Here are two routes that fail in different ways from my expectations:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func handler(w http.ResponseWriter, req *http.Request) {
	w.WriteHeader(200)
	w.Write([]byte("HERE"))
}

func main() {
	r := chi.NewRouter()
	r.MethodFunc("GET", "/{first:[a-z]{4}}", handler)          // Does not panic at runtime, however I except it to match only requests with four a-z characters.
	r.MethodFunc("GET", "/{first:[a-z]{4}}/{second}", handler) // Panics at runtime, slice bounds out of range. I expect it to match only requests where the first URI segment has four a-z characters and some value in the second segment. Comment out to test the first defined route.
	fmt.Println("Listening...")
	http.ListenAndServe(":3000", r)
}
```

**Comment by pkieltyka** [comment]
Thanks for the report. I'll get this supported eventually - PRs are welcome too from anyone interested :)

**Comment by nicpottier** [comment]
Ran into this as well and willing to put together a PR. 

How do we want this to work?

Seems we have two options, either require "escaping" the `{` and `}` characters somehow when you are trying to define a regex in a path, or require that variables must being with a non-digit, in which case we can test anything in `{}` for whether it starts with a digit and if so use it as a variable name and if not use it as a regex.

Regexes are already a bit nuts when it comes to escaping, so adding another way of escaping in there sounds error prone to me. So my vote would be to disallow names that start with a digit, then treat any `{..}` block that starts as a digit as something to be part of a regex.

Thoughts?

**Comment by pkieltyka** [comment]
thanks @nicpottier - I believe we could update `patNextSegment()` method to parse `"/{first:[a-z]{4}}"` without any restriction. As you parse the tokens, if you determine two `{`'s where one isn't closed, then we skip the second, keep track and look for the outer closing bracket. In case the count is off, panic to inform the expression of the tree is invalid (as we do with other invalid routing paths)

**Comment by pkieltyka** [comment]
thanks @nicpottier for the PR!
