### ISSUE TITLE
In REST example you pass *chi.Mux to docgen.MarkdownRoutesDoc

### ISSUE THREAD

**Issue by Labutin** [go-chi/chi#232]
In REST example ( https://github.com/go-chi/chi/blob/master/_examples/rest/main.go )  you pass *chi.Mux to docgen.MarkdownRoutesDoc but docgen.MarkdownRoutesDoc waits chi.Router

**Comment by pkieltyka** [comment]
Hey Labutin, chi.Router is an interface and *chi.Mux's implementation adheres to that interface, so in Go you're able to pass objects to interface values that match.

**Comment by dhax** [comment]
when using MarkdownRoutesDoc with *chi.Mux it works though, but breaks gorename for the whole project with this error:
cannot use api (variable of type *github.com/go-chi/chi.Mux) as github.com/go-chi/chi.Router value in argument to docgen.MarkdownRoutesDoc: wrong type for method Group

Can you confirm this please or am I doing something wrong?

**Comment by VojtechVitek** [comment]
we can't help you if you don't provide full reproducers
