### ISSUE TITLE
Can not use gopkg.in/cas.v1 in chi? How?

### ISSUE THREAD

**Issue by shenshouer** [go-chi/chi#236]
Is there any way How to use gopkg.in/cas.v1 with chi ? The rep of cas.v1 is github.com/go-cas/cas

**Comment by pkieltyka** [comment]
It sure can. Have a look at https://github.com/casbin/chi-authz for an example.

**Comment by shenshouer** [comment]
I did not find any useful example for use gopkg.in/cas.v1 with the chi-authz  and chi.  The chi-authz is authorization and cas  is Authentication

**Comment by shenshouer** [comment]
I made a PR for gopkg.in/cas.v1 to support at https://github.com/go-cas/cas/pull/13
