### ISSUE TITLE
*Mux.Handle fails where identical http.Handle works with no problem

### ISSUE THREAD

**Issue by NikosEfthias** [go-chi/chi#239]
i have the following sample code 
```go
        //r := chi.NewRouter()
	//r.Handle("/assets/", http.StripPrefix("/assets/", http.FileServer(rice.MustFindBox("assets").HTTPBox())))
	http.Handle("/assets/", http.StripPrefix("/assets/", http.FileServer(rice.MustFindBox("assets").HTTPBox())))
	//http.ListenAndServe(":8080", r)
	http.ListenAndServe(":8080", nil)
```

when i switch comment lines from chi to http the browser always returns 404 regardless of the path but http works with no problem

**Comment by pkieltyka** [comment]
@NikosEfthias Id have to look into these details sometime. but, did you check the https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go example?

it's likely the semantics of Handle() are not identical between chi and http

**Comment by zemirco** [comment]
Try the following. It works for me serving static files from my `/public/` repo.

```go
r.Method(http.MethodGet, "/public/*", http.StripPrefix("/public/", http.FileServer(http.Dir("public"))))
```

It might just be the missing asterisk `*`.

**Comment by pkieltyka** [comment]
in that case, `http.Handle("/assets/*", http.StripPrefix("/assets/", http.FileServer(rice.MustFindBox("assets").HTTPBox())))` will probably work as well
