### ISSUE TITLE
How do people pronounce this library?

### ISSUE THREAD

**Issue by jutkko** [go-chi/chi#242]
Is it only me who is confused about how to say "chi"? I am hearing at least two ways of pronouncing it. In Chinese, there is another way of saying it...

**Comment by ustrajunior** [comment]
Hey, @jutkko. 

You can check this issue about this: [Chi pronunciation?](https://github.com/go-chi/chi/issues/199).

**Comment by pkieltyka** [comment]
you are welcome to pronounce it by your own rendition too :)
