### ISSUE TITLE
Is it possible to have routing based on header value using chi/mux?

### ISSUE THREAD

**Issue by gabiganam** [go-chi/chi#244]
I currently use the mux and I route based on the HTTP method, like so:
![image](https://user-images.githubusercontent.com/28859646/29277512-84f0ca18-811a-11e7-9499-7b3f39f16fd4.png)

I would love to be able to add header-value or header-existence based routing in the same manner.
Is this possible using chi?
When I googled it I came across a different package that has such a feature: http://www.gorillatoolkit.org/pkg/mux

But I'm already using (and loving) chi, hence this question :)

**Comment by pkieltyka** [comment]
hey sorry I dont understand the question. Are you saying you want to have dynamic routes depending on header-value of a request?

**Comment by gabiganam** [comment]
I'm not sure what you mean by "dynamic", but yes.
For example I could have;
r.Header("Version", "1.2.3").Get("/some/uri/here", oldHandler)
r.Header("Version", "2.0").Get("/some/uri/here", newHandler)

Now assume my application has a header called "Version", then requests from version "1.2.3" will be handled by the "oldHandler" function, and version "2.0" will be handled by the "newHandler".
It would obviously be very powerful to have the header value support regex, although that will introduce the problem of overlapping results, so let's put a pin in that for now.
Let's also define that requests for that URI without the mapped header, or without a mapped header value, will result in a page-not-found error.
Unless of course I have:
r.Get("/some/uri/here", defaultHandler)
In which case they will get to the "defaultHandler".

**Comment by VojtechVitek** [comment]
Imho you should have two chi routers, one for each API version.

And then, have a simple multiplexer handler that will route to that specific router:

```go
func APIVersionRouter(w http.ResponseWriter, r *http.Request) {
    switch  {
        case strings.HasPrefix(r.Header.Get("Version"), "1."):
             APIVersion1.ServeHTTP(w, r)

        default:
             APIVersion2.ServeHTTP(w, r)
    }
}
```

**Comment by pkieltyka** [comment]
exactly @VojtechVitek - this is what I was going to suggest

**Comment by gabiganam** [comment]
Sounds like a great solution for what I need :)
