### ISSUE TITLE
How to avoid globals in middlewares (ArticleCtx example) ?

### ISSUE THREAD

**Issue by hugows** [go-chi/chi#250]
Hello,
I've been using the "methods inside db type" pattern to avoid globals in my server:

```
func (api *Api) Router() http.Handler {
	r := chi.NewRouter()
        ...
	r.Method("POST", "/user/login", Handler(api.userLogin))
	r.With(TokenCtx).Method("GET", "/user/devices", Handler(api.userDevices))
	return r
}
```

In this example, TokenCtx would need to receive a ref to Api.
Is there a way to do this without resorting to global references?

Thanks

**Comment by pkieltyka** [comment]
hey @hugows - there are many ways you could design it - but its all for personal preference. 

One idea is to check other open source projects to see how they manage project structure and passing references around to application state.

**Comment by hugows** [comment]
Sorry, that was a very basic mistake (C style thinking), I was going to delete the issue.
Solution is of course to just write TokenCtx as such:

`func (api *Api) TokenCtx(next http.Handler) http.Handler {`

Thanks for Chi, again.
Hugo

**Comment by VojtechVitek** [comment]
1. Method receiver, as you just pointed out
2. Pass the reference in the request Context
3. Global reference
