### ISSUE TITLE
Question: How to use StripSlashes in a Group

### ISSUE THREAD

**Issue by flimzy** [go-chi/chi#251]
I need to match an endpoint of the pattern `/bundle-{id}`, but some of my JS clients always add a trailing slash: `/bundle-{id}/`.  I'm trying to strip this with the `StripSlashes` middleware, but it's not effective:

```go
	r.Group(func(r chi.Router) {
		r.Use(middleware.StripSlashes)
		bundleHandler := createBundle(proxy, client)
		r.Handle("/bundle-{id}", bundleHandler)
		// r.Handle("/bundle-{id}/", bundleHandler)
	})
```

If I uncomment the last line, with the nearly redundant route, it works as expected, but that ought not be necessary.

Am I doing something wrong?  Does the pattern match interact strangely with StripSlashes and/or groups?

**Comment by pkieltyka** [comment]
hey @flimzy it will be too late in the group as the code to find the routing handler from your path executes before that middleware. You will have to move this to the very top, not as an inline middleware like Group(). It's its a problem, just have both routes defined, `r.Handle("/bundle-{id}", bundleHandler)` and `r.Handle("/bundle-{id}/", bundleHandler)`

**Comment by flimzy** [comment]
Thanks for the prompt reply!
