### ISSUE TITLE
Error 404 whenever using URL parameters

### ISSUE THREAD

**Issue by tutley** [go-chi/chi#252]
I'm having a really strange issue where I get a 404 error whenever I try to access a route with URL parameters. I've tried a ton of things at this point and so I thought I'd post here. I'm developing on Mac OS and using Go 1.8.3. Here's the routing section of my code, any help would be appreciated:

	r := chi.NewRouter()

	// Use Chi built-in middlewares
	r.Use(middleware.Logger)
	r.Use(middleware.NoCache)
	r.Use(middleware.Recoverer)

	// Mount database
	r.Use(mongoMiddleware)

	// Set a timeout value on the request context (ctx), that will signal
	// through ctx.Done() that the request has timed out and further
	// processing should be stopped.
	r.Use(middleware.Timeout(60 * time.Second))

	// Setup routes

	r.Get("/", handlers.GetIndexHandler)
	r.Get("/test/{test}", handlers.GetIndexHandler) // get /test/something
	r.Route("/test2", func(r chi.Router) {
		r.Route("/{test2}", func(r chi.Router) {
			r.Get("/", handlers.GetIndexHandler) // get /test2/something
		})
	})

	// This goes last so every other request gets the fileserver
	// This serves the static files generated by go-bindata-assetfs
	r.FileServer("/dist", assetFS())

	// and.... go!
	serveAddr := ":" + strconv.Itoa(serverPort)
	log.Println("dhcpportal Server listening on: ", strconv.Itoa(serverPort))
	http.ListenAndServe(serveAddr, r)

**Comment by pkieltyka** [comment]
hey @tutley what version of chi are you using? we removed `FileServer` from the core as its too difficult to support, you will have to write your own implementation for routing files.

**Comment by pkieltyka** [comment]
many issues have been brought up with the `FileServer` and routing tree - as we can't peak into the fileserver routes, they cannot overlap

check https://github.com/go-chi/chi/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20fileserver it might offer some hints for what others experienced and how they solved their issues

the best thing to do is write a custom FileServer method for your needs, see https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go

**Comment by tutley** [comment]
I'll check that out. I didn't think the fileserver would cause an issue becuase it has it's own stub ('/dist') but I'll try some things there (like just removing that line and seeing what happens with the API routes)

I'm using the fileserver that is exported by: https://github.com/elazarl/go-bindata-assetfs

I'd be open to not using a fileserver but instead using go-bindata to create a variable for each asset if there was some sort of automated way to setup the routing for each asset.

Oh I'm using:
 cat vendor/github.com/pressly/chi/CHANGELOG.md
# Changelog

## v2.1.0 (2017-03-30)

**Comment by tutley** [comment]
Commenting out the r.FileServer doesn't seem to have changed anything. Still 404ing.

**Comment by tutley** [comment]
OK, I updated to the correct project (go-chi/chi rather than pressly/chi) and implemented your fileserver function then called it like this:
FileServer(r, "/dist", assetFS())

And now url parameters are working. Thanks!
