### ISSUE TITLE
Using unsupported method

### ISSUE THREAD

**Issue by stelund** [go-chi/chi#253]
I'm trying to implement support for unsupported http methods. Do you have any suggested solution rather than forking?

Maybe chi could support ANY method routing for explicit setup. So to add a route for e.g. PROPFIND a new function mux.AnyMethodRoute would be used which would use mANY. Then routeHTTP would fallback to mANY if no matching methodType could be found in methodMap.

In the end the responsibility to verify the http method would be up to the handler.

**Comment by pkieltyka** [comment]
hey @stelund - yea you'll have to fork it to add PROPFIND. There is a `Router.Method()` that takes the string of a method name, you can add PROPFIND to the methodMap and it'll just work.

**Comment by pkieltyka** [comment]
perhaps what I'll do is export the methodMap so people can configure it themselves to add their own custom types.. they would have to specify their own constant too

**Comment by pkieltyka** [comment]
I quickly took a look, it would be much more work than that as the methods are a bitmap - maybe some other day way into the future.

Why do you need PROPFIND? how come you cant use some other method?

**Comment by stelund** [comment]
I'm writing a proxy which also need to pass through webdav requests. 

Can I suggest an PR for an support any method that I mentioned?

**Comment by pkieltyka** [comment]
Thanks for the offer - but it’s not a standard HTTP method from what I can see so I’d rather it not put it into the core

Just fork the project for now

**Comment by stelund** [comment]
OK, thanks!

**Comment by oliverpool** [comment]
If I'm not mistaken, this is now available without fork, using [`RegisterMethod("PROPFIND")`](https://godoc.org/github.com/go-chi/chi#RegisterMethod) :-)

**Comment by stelund** [comment]
Thanks for the heads up!
