### ISSUE TITLE
pronunciation?

### ISSUE THREAD

**Issue by scrivy** [go-chi/chi#256]
Is the pronunciation chi as in the Greek letter χ or qi as in the Chinese letter 氣?

https://en.wikipedia.org/wiki/Chi_(letter)
https://en.wikipedia.org/wiki/Qi

Very heated debate at work today.

**Comment by VojtechVitek** [comment]
See https://github.com/go-chi/chi/issues/199#issuecomment-303135420

**Comment by scrivy** [comment]
Shoot. Should have searched. Thanks

**Comment by hugows** [comment]
So https://www.youtube.com/watch?v=_dz7CIYQXcg ?
