### ISSUE TITLE
querystring?

### ISSUE THREAD

**Issue by vincentserpoul** [go-chi/chi#257]
I don't see any docs on querystring params.
Are we supposed to parse it like any URL pattern?
It would be worse giving an example with it in the test/docs/examples.

**Comment by DisruptiveMind** [comment]
@vincentserpoul you can still use `request.URL.Query().Get(...)`

**Comment by ggicci** [comment]
Looks like what #320 asked for. Please take a look at [ggicci/httpin](https://github.com/ggicci/httpin). Which provides functionablities of processing query parameters from path, querystring, header, etc. And it is well integrated with chi, see https://ggicci.github.io/httpin/integrations/gochi for more details. 😄
