### ISSUE TITLE
Variable shadowing in examples

### ISSUE THREAD

**Issue by gurre** [go-chi/chi#261]
There is a lot of variable shadowing in the examples files. It makes the code harder to read.

https://github.com/go-chi/chi/blob/master/_examples/limits/main.go

**Comment by pkieltyka** [comment]
thanks, but I disagree. I find it to be minimal and easy to follow with some experience with `context`

**Comment by Vektah** [comment]
I think this kind of shadowing is preferred:
```go
r.Group(func(r chi.Router) {
	r.Use(middleware.CloseNotify)
	r.Get(...)
}
```

not shadowing can lead to bugs like:
```go
outerRouter.Group(func(innerRouter chi.Router) {
	innerRouter.Use(middleware.CloseNotify)
	outerRouter.Get(...)
}
```

Now the middleware dosent apply to anything

The same logic applies to "shadowing" testing `t.Run(func(t *testing.T) {})`.
