### ISSUE TITLE
Any chance of adding an appengine build target?

### ISSUE THREAD

**Issue by polds** [go-chi/chi#267]
Wondering if it'd be possible to add an `appengine` target to all the *18.go files so the build looks like:

```
// +build go1.8 appengine
```

As appengine reports, when using Go 1.8, a Go version of `1.8.3 (appengine-1.9.61)`

Looks like files affected would be:

 - [middleware/closenotify18.go](https://github.com/go-chi/chi/blob/master/middleware/closenotify18.go)
 - [middleware/compress18.go](https://github.com/go-chi/chi/blob/master/middleware/compress18.go)
 - [middleware/wrap_writer18.go](https://github.com/go-chi/chi/blob/master/middleware/wrap_writer18.go)

I'd open a PR, but due to some employer legalities it'd be a pain for me for just three lines of code.

**Comment by polds** [comment]
fwiw I've modified my own copy locally of chi and this allows me to deploy to appengine with no issue.

**Comment by VojtechVitek** [comment]
As long, as it doesn't break anything for non-appengine users, I don't see reason why not ;)

**Comment by pkieltyka** [comment]
No problem, we’ll add it soon. I’ll return to a terminal on Sunday. Vojtech if you want to do it sooner, go for it

**Comment by VojtechVitek** [comment]
@polds wanna submit a PR?
