### ISSUE TITLE
Matching routes by Request.URL.Host

### ISSUE THREAD

**Issue by mvdan** [go-chi/chi#269]
This might have been left out of chi on purpose, but I could not find a reference or mention anywhere in the repo.

I have a fairly big project that uses `github.com/gorilla/mux` and I'd like to move it to chi. For the most part, it does a better job at the same functionalities - especially when it comes to middlewares.

However, there's something I can't figure out how to port - filtering by host. That is, a router having a sub-router (or route) that only matches requests with a certain `Request.URL.Host`.

Is there a way to do this with chi at the moment? I could not figure out a way. I played with a middleware that did the filtering for a bit, but it seems obviously wrong.

I could always do the filtering either before chi (i.e. implement my own thin router on top), or at the handler level. Both seem like bad approaches, because it needs the host routing in between - at a more granular level.

After looking at the chi codebase a bit, I believe this to be impossible at the moment, since the tree matcher only uses `Method` and `Path`. I would like to be proven wrong, or to be shown another way to do it.

Thanks!

**Comment by pkieltyka** [comment]
@mvdan welcome onboard :) 

can you take a look at https://github.com/go-chi/hostrouter and let me know if this helps. The solution is just stacking routers on top based on the Request.URL.Host

**Comment by pkieltyka** [comment]
this is as you suggested, building the host routing before the chi method/path routing. If it doesn't work, can you provide an example of what the `hostrouter` approach fails to support?

**Comment by mvdan** [comment]
Ah I see, I missed that repo (forgot to do an org-wide search).

Yes, that's exactly what I was thinking of building. It *should* be all that I need. However, the way the project is built, it handles hosts at the sub-router level, not at the top level. So I would have to refactor quite a bit of the code to make it fit `hostrouter`.

I'll give it a go and let you know if I hit any wall (i.e. anything that was possible with the other router, but not chi+hostrouter). Feel free to close this issue, and I'll reopen in that case. Thanks!

**Comment by pkieltyka** [comment]
great, good luck! and let me know how it goes. cheers
