### ISSUE TITLE
RoutePattern at middleware level?

### ISSUE THREAD

**Issue by jutkko** [go-chi/chi#270]
Hi I am migrating from an echo router codebase to chi. One of the things we use was the parameterised path variable echo provides. I can see a similar thing in chi, `chi.RouteContext(r.Context()).RoutePattern()`, but this function seems to be returning an empty string when called in middlewares. Is there way out? 

Am I missing something obvious? Thanks.

**Comment by pkieltyka** [comment]
@jutkko the RoutePattern() will only return a value once its determined the final route. You can either access it in the endpoint handler, or after a request responds in the middleware. See the description in https://github.com/go-chi/chi/blob/master/context.go#L80-L93 and example there:

```golang
func Instrument(next http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    next.ServeHTTP(w, r)
    routePattern := chi.RouteContext(r.Context()).RoutePattern() // <---<< after
    measure(w, r, routePattern)
 })
}
```

please let me know if this works for you guys / other feedback

**Comment by jutkko** [comment]
Yes that will do the job. But there are some operations (tracing) we want to do before calling `next` and also want to have the `RoutePattern()`... 

Thanks for the quick response though!

**Comment by pkieltyka** [comment]
@jutkko cool - if thats the case, you could use a technique similar in https://github.com/go-chi/chi/blob/master/middleware/get_head.go to pre-process the route and get the RoutePattern() from that context.

**Comment by rliebz** [comment]
For anyone who still needs this, the following seems to work:

```go
func getRoutePattern(r *http.Request) string {
	rctx := chi.RouteContext(r.Context())
	if pattern := rctx.RoutePattern(); pattern != "" {
		// Pattern is already available
		return pattern
	}

	routePath := r.URL.Path
	if r.URL.RawPath != "" {
		routePath = r.URL.RawPath
	}

	tctx := chi.NewRouteContext()
	if !rctx.Routes.Match(tctx, r.Method, routePath) {
		// No matching pattern, so just return the request path.
		// Depending on your use case, it might make sense to
		// return an empty string or error here instead
		return routePath
	}

	// tctx has the updated pattern, since Match mutates it
	return tctx.RoutePattern()
}
```
