### ISSUE TITLE
Is this `WriteHeader(http.StatusOK)` necessary?

### ISSUE THREAD

**Issue by luweimy** [go-chi/chi#280]
https://github.com/go-chi/chi/blob/687d2792aedd8e8ac3bbd8592cf55b91d7ea8ce9/middleware/wrap_writer.go#L51

```
func (b *basicWriter) Write(buf []byte) (int, error) {
	b.WriteHeader(http.StatusOK)
	n, err := b.ResponseWriter.Write(buf)
	if b.tee != nil {
		_, err2 := b.tee.Write(buf[:n])
		// Prefer errors generated by the proxied writer.
		if err == nil {
			err = err2
		}
	}
	b.bytes += n
	return n, err
}
```
Http server when `finishRequest` will set  `http.StatusOK`.
Changing the header map after a call to WriteHeader (or Write) has no effect unless the modified headers are trailers.

**Comment by VojtechVitek** [comment]
It's not necessary, but it's explicit :)
