### ISSUE TITLE
[Proposal]Change of RequestID using X-Request-ID Header

### ISSUE THREAD

**Issue by pei0804** [go-chi/chi#282]
Thank you for a nice work.

I have a proposal.
I would like to change the prepared middleware as follows for logging.
Of course I can make it yourself.
If you incorporate it officially, I can create it.

```go
rid := r.Header.Get("X-Request-ID")
if rid == "" {
		myid := atomic.AddUint64(&reqid, 1)
		rid = fmt.Sprintf("%s-%06d", prefix, myid)
		r.Header.Set("X-Request-ID", rid)
}
```

**Comment by pei0804** [comment]
```go
```

**Comment by pkieltyka** [comment]
thanks @pei0804 - its a reasonable proposal, but the goal is to keep chi's middlewares unopinionated. If someone wants to assign the X-Request-ID header, then they should do so in a separate middleware.
