### ISSUE TITLE
2017/11/29 10:28:47 http: panic serving 127.0.0.1:39972: interface conversion: interface {} is nil, not *chi.Context

### ISSUE THREAD

**Issue by zjn1234** [go-chi/chi#284]
`ctx := context.WithValue(context.Background(), common.TENANTKEY, resLog.DestTenantId)
r = r.WithContext(ctx)
next.ServeHTTP(w, r)`

chi is the latest
import "context" package

when i use these, i got the errors below
2017/11/29 10:28:47 http: panic serving 127.0.0.1:39972: interface conversion: interface {} is nil, not *chi.Context

**Comment by pkieltyka** [comment]
please look at the examples. You are setting a new context.Background() but you must use the request context. change the line to:

`ctx := context.WithValue(r.Context(), common.TENANTKEY, resLog.DestTenantId)`

**Comment by zjn1234** [comment]
oh，thanks
