### ISSUE TITLE
Weird characters when logging to text file

### ISSUE THREAD

**Issue by jdelk** [go-chi/chi#290]
Hi,

I'm logging to a text file called logs.txt using the following code:

```
var file, err = os.Create("logs.txt")
	if err != nil {
		panic("Failed to create log file")
	}
	customLogger := log.New(file, "", log.LstdFlags)
	middleware.DefaultLogger = middleware.RequestLogger(&middleware.DefaultLogFormatter{Logger: customLogger})
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
```
In logs.txt, I see:

2018/01/15 18:48:05 [33m[devtest/NHcrlBfdos-000001] [0m[36m"[0m[35;1mGET [0m[36mhttp://10.0.1.25/ HTTP/1.0" [0mfrom 10.0.1.26 - [32;1m200[0m[34;1m 10422B[0m in [32m3.256873ms[0m

There's some odd characters being logged. How can I fix that?

**Comment by mafredri** [comment]
@jdelk the strange characters you're seeing are terminal color codes. It seems chi has basic detection for when the program is not running in a TTY and disables colors, but it does not take into account where the program is printing (e.g. a file).

I made a quick PR (#299), which if merged, will allow you to disable color logging by changing:

```go
middleware.DefaultLogger = middleware.RequestLogger(&middleware.DefaultLogFormatter{Logger: customLogger})
```

to

```go
middleware.DefaultLogger = middleware.RequestLogger(&middleware.DefaultLogFormatter{Logger: customLogger, NoColor: true})
```
