### ISSUE TITLE
Middlewares called on NotFound handler

### ISSUE THREAD

**Issue by nullbio** [go-chi/chi#292]
Hello. There is no way to prevent middlewares from being called before the NotFound handler is called, which is a problem because, for example, I don't need my CSRF middleware to kick in when the page isn't found. It sounds like it was by design that it shouldn't be called, but now it seems it is being called and it hasn't been rectified: https://github.com/go-chi/chi/issues/163

If it weren't called automatically we could wrap the middlewares manually if we needed to for the NotFound handler.

**Comment by aarondl** [comment]
Ran into this, it'd be handy if this was preventable in some way.

**Comment by aarondl** [comment]
Sample program that reproduces the problem. Note that even when navigating to a route that's not handled the output still includes the middleware piece.

```package main

import (
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	router := chi.NewRouter()

	router.Use(func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			fmt.Println("middleware", r.URL.Path)
			h.ServeHTTP(w, r)
		})
	})

	router.NotFound(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("not found", r.URL.Path)
		w.WriteHeader(http.StatusNotFound)
	}))

	router.Get("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("normal route")
		w.WriteHeader(200)
		io.WriteString(w, "<!DOCTYPE html>\n<html><body>rofl</body></html>")
	}))

	http.ListenAndServe(":6423", router)
}
```

**Comment by pkieltyka** [comment]
hey guys, the correct design is to execute the top-level middlewares, as the top-level middlewares have the power to change the request URL Path, to something that could resolve a found handler.

so... if you're really trying to avoid some particular middleware from executing, you can look ahead and execute the NotFound handler sooner.

To get an idea of how to write a middleware how to match a route look at https://github.com/go-chi/chi/blob/master/middleware/get_head.go

something like..

```go
func CustomNotFound(next http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    tctx := chi.NewRouteContext()
    if !rctx.Routes.Match(tctx, r.Method, routePath) {
       notFound(w, r)
       return
    }
    next.ServeHTTP(w,r)
  }
}
```
