### ISSUE TITLE
The future of chi after Pressly being merged

### ISSUE THREAD

**Issue by jimbojetlag** [go-chi/chi#293]
Could chi authors please update us about the future of the library given that the company behind chi is now merged into another company.

Just in case if the new company likes the smell of Java and Javascript over Go, what would happen to chi?

**Comment by pkieltyka** [comment]
hey @jimbojetlag thanks for asking. The future is bright for chi :) 

In many ways, chi is stable and architecturally hasn't changed a long time. The core library after all is just ~1000 lines of code. We will of course continue to support any bugs that come up.

From a business perspective, Pressly the product/platform still lives on, and the acquirer and team there love Go. But, the fact of the matter is that chi is an independent open source initiative that is beyond any company and belongs to the community under the MIT license.
