### ISSUE TITLE
Should AllowContentType middleware skip checks for empty requests?

### ISSUE THREAD

**Issue by jawnsy** [go-chi/chi#295]
The [AllowContentType middleware](https://github.com/go-chi/chi/blob/master/middleware/content_type.go#L21-L45) checks all request types, even if the payload is empty. For requests like `GET` and `HEAD`, the payload is typically empty; however, [the spec](https://tools.ietf.org/html/rfc7231#section-4.3.1) leaves the possibility of a payload for these requests up to the implementation:

> A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

For chi users, this means that we must either:

* Use separate middleware stacks for read-only (GET, HEAD) and create-update (POST, PUT) requests; or
* Require that a `Content-Type` is always provided, even when there's no request body

**Comment by pkieltyka** [comment]
closing in 8983e7a9dafa3a7a2f5509e20bf57063cae438eb -- taking your suggestion and skipping check on requests with empty body
