### ISSUE TITLE
Wrapping Chi for testability and composition

### ISSUE THREAD

**Issue by lansana** [go-chi/chi#304]
Hi there,

I am trying to wrap Chi so I can create mocks as well as compose my own logic within it.

For example, here's my wrapper:

```go
package router

import (
	"github.com/go-chi/chi"
	"net/http"
)

type Router interface {
	ParamReader
	Paginator
	Printer

	Get(pattern string, handlerFn http.HandlerFunc)
	Post(pattern string, handlerFn http.HandlerFunc)
	Put(pattern string, handlerFn http.HandlerFunc)
	Delete(pattern string, handlerFn http.HandlerFunc)
	Group(fn func(r Router))
	Route(pattern string) Router
	Use(middlewares ...func(http.Handler) http.Handler)
	With(middlewares ...func(http.Handler) http.Handler) Router
	NotFound(handlerFn http.HandlerFunc)
	MethodNotAllowed(handlerFn http.HandlerFunc)
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

func newRouter(mux *chi.Mux) Router {
	return &router{mux: mux}
}

func New() Router {
	return newRouter(chi.NewMux())
}

type router struct {
	mux *chi.Mux
}

func (rr *router) Get(pattern string, handlerFn http.HandlerFunc) {
	rr.mux.Get(pattern, handlerFn)
}

func (rr *router) Post(pattern string, handlerFn http.HandlerFunc) {
	rr.mux.Post(pattern, handlerFn)
}

func (rr *router) Put(pattern string, handlerFn http.HandlerFunc) {
	rr.mux.Put(pattern, handlerFn)
}

func (rr *router) Delete(pattern string, handlerFn http.HandlerFunc) {
	rr.mux.Delete(pattern, handlerFn)
}

func (rr *router) Use(middlewares ...func(http.Handler) http.Handler) {
	rr.mux.Use(middlewares...)
}

func (rr *router) With(middlewares ...func(http.Handler) http.Handler) Router {
	return newRouter(rr.mux.With(middlewares...).(*chi.Mux))
}

func (rr *router) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	rr.mux.ServeHTTP(w, r)
}

func (rr *router) NotFound(handlerFn http.HandlerFunc) {
	rr.mux.NotFound(handlerFn)
}

func (rr *router) MethodNotAllowed(handlerFn http.HandlerFunc) {
	rr.mux.MethodNotAllowed(handlerFn)
}

func (rr *router) Group(fn func(r Router)) {
	rr.mux.Group(func(r chi.Router) {
		fn(newRouter(r.(*chi.Mux)))
	})
}

func (r *router) Route(pattern string) Router {
	mux := r.mux.Route(pattern, nil).(*chi.Mux)
	return newRouter(mux)
}
```

I'm getting an issue when calling the `Route` method. For some reason, when I initialize my router with `r := router.New().Route("/v1")` in `main.go`, the `/v1` prefix is never added. But when I pass that router instance into a controller or something and then do `r.Prefix("/v1").Group(...)`, THEN it works. 

This doesn't make any sense. Am I wrapping it in such a way that it breaks the core functionality?

Here is what I do in `main.go`. The second call to `Route` should panic saying that the `/v1` path has already been mounted, but it doesn't...

```go
r := router.New().Route("/v1")
	r = r.Route("/v1")
	r = r.Route("/v1")
```

But later in my code, in my `AuthController` where I inject my custom `router.Router` interface (which is my interface that wraps Chi), I can do the following and it prefixes the `/v1` path as it should:

```go
func (c *authController) AddRoutes() {
	c.router.Route("/v1").Group(func(r router.Router) {
		r.Use(middleware.Anyone)

		r.Post("/auth/register", c.Register)
		r.Post("/auth/login", c.Authenticate)
		r.Post("/auth/token/refresh", c.RefreshToken)
	})

        // This line will panic because /v1 was already mounted in the statement above
	c.router.Route("/v1").Group(func(r router.Router) {
		r.Use(middleware.Authorized)

		r.Get("/auth/ping", c.Ping)
		r.Post("/auth/logout", c.Logout)
	})
}
```

That is what it should be doing. Why doesn't the example from `main.go` behave this way?

**Comment by pkieltyka** [comment]
hey @lansana - I wrote something similar to add an ACL layer on top of a chi.Router, check out https://gist.github.com/pkieltyka/d4ab2e385febcc195a9cea4ef8e61227 which should help you finish your version

**Comment by lansana** [comment]
Hey @pkieltyka - thanks for the good reference, it may be helpful in the future or to someone else. :)

I managed to solve this. I was doing something wrong when setting up the router in `main.go`.

I had:
```go
r := router.New().Route("/v1", nil)
```

I should have had:
```go
r := router.New()
v1 := r.Route("/v1", nil)
```

I should have then passed the `v1` router into my controllers, as opposed to the `r` router. There needed to be a base to work off of, at least that's how I interpret it without reading through the source code fully.

**Comment by pkieltyka** [comment]
@lansana great! thanks
