### ISSUE TITLE
[Feature request] Add a flag to log request payload in logging middleware

### ISSUE THREAD

**Issue by asydorchuk** [go-chi/chi#305]
Hi what's your opinion on adding "LogPayload" attribute to DefaultLogFormatter in middleware/logger.go, so that DefaultLogger logs payload if configured?

If authors approve, I can do a pull request.

**Comment by VojtechVitek** [comment]
What payload do you mean? Request or Response payload?

Would be nice to have this configurable somehow. So one could toggle this on a specific route for example.

**Comment by asydorchuk** [comment]
Hi, I meant request payload.

Not sure how to make it configurable per route. How about I start with making it configurable per Logger instance?

**Comment by pkieltyka** [comment]
hey @asydorchuk - the middleware logger interface in chi is designed with the intention that it'd be extended in some way. For production apps, I'd recommend some kind of structured logging

Check out https://github.com/pressly/lg or https://github.com/go-chi/chi/blob/master/_examples/logging/main.go where you can easily add the request payload from any stage of your request/response lifecycle.
