### ISSUE TITLE
Walk mis-reports sub-router routes

### ISSUE THREAD

**Issue by carldunham** [go-chi/chi#310]
The code below produces:
```
2018/04/04 09:17:21 GET /
2018/04/04 09:17:21 GET /v1/*/
2018/04/04 09:17:21 GET /v1/*/docs
2018/04/04 09:17:21 GET /v1/*/stuff/*/
2018/04/04 09:17:21 Listening on 127.0.0.1:8181
```
with no indication that that `/v1/foo` will fail, while `/v1/stuff/foo` will succeed.

I'm using Walk to verify route construction in unit tests, which I want to fail if someone adds a wildcard to `/v1/`.

Go version: go1.10.1 darwin/amd64
chi version: 3.3.2

code:
```
package main

import (
	"log"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Get("/", root)

	r.Route("/v1", func(r chi.Router) {
		r.Get("/", v1root)
		r.Get("/docs", v1docs)
		r.Get("/stuff/*/", v1stuff)
	})

	address := "127.0.0.1:8181"

	chi.Walk(r, func(method string, route string, handler http.Handler, middlewares ...func(http.Handler) http.Handler) error {
		log.Printf("%s %s", method, route)
		return nil
	})

	log.Printf("Listening on %s", address)
	err := http.ListenAndServe(address, r)
	if err != nil {
		log.Fatalf("ListenAndServe: %s", err.Error())
	}
}

func root(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("root"))
}

func v1root(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("v1"))
}

func v1docs(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("v1docs"))
}

func v1stuff(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("v1stuff"))
}
```

**Comment by wayneashleyberry** [comment]
I just ran into the same issue, here's a simple example:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Route("/foo", func(r chi.Router) {
		r.Get("/bar", func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprintf(w, "Hello, %s!", "World")
		})
	})

	chi.Walk(r, func(method string, route string, handler http.Handler, middlewares ...func(http.Handler) http.Handler) error {
		fmt.Printf("%s: %s\n", method, route)
		return nil
	})

	http.ListenAndServe(":3000", r)
}
```

This programme will output `GET: /foo/*/bar` which is incorrect. It should be `GET: /foo/bar`

**Comment by pkieltyka** [comment]
this is just the nature of the raw details of the walker, you can just string+replace `/*` to `/`

let me know if this is still a problem

**Comment by carldunham** [comment]
But those are two different route specifications. In my use case (and many, I egocentrically assume), there are cases like the ones I listed where wildcards could be stripped out and others where they should not.

**Comment by VojtechVitek** [comment]
@pkieltyka I wouldn't mind filtering out `/*/` paths in the Walk() func itself, since the star `*` is an implementation detail of the chi sub-routers. And Walk() is rather user-facing thing meant for documentation purposes etc. Thoughts?

**Comment by pkieltyka** [comment]
done https://github.com/go-chi/chi/commit/17fb1065d2b256d20f68bed0b7bca6c2942aff49
