### ISSUE TITLE
URLParam() returns the parameter until the "." (dot)

### ISSUE THREAD

**Issue by PlkMarudny** [go-chi/chi#319]
I have a handler defined like that:

`r.Route("/media/{mediaID}", func(r chi.Router) {
		r.Use(MediaAssetCtx)
		r.Get("/", ServeFile)
	})`

In the MediaAssetCtx I try to extract the mediaID:
`m := chi.URLParam(r, "mediaID");`

With the request:

`http://my_address:3333/media/a.html`

the returned value is "**a**", not "**a.html**", in other words only the part up to the dot is extracted.
Is this right? If yes, is this any other way to get the full parameter value?

**Comment by pkieltyka** [comment]
@PlkMarudny can you paste a gist of your full example? 

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hello world"))
	})
	r.Get("/media/{mediaID}", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("test " + chi.URLParam(r, "mediaID")))
	})
	http.ListenAndServe(":3333", r)
}
```

try that above, the response is "test a.html" in a request to /media/a.html

**Comment by pkieltyka** [comment]
ensure you are using the latest version of chi btw (master)
