### ISSUE TITLE
Feature Request: Add URL param/query helpers

### ISSUE THREAD

**Issue by lansana** [go-chi/chi#320]
In Chi, there is a helper to get the URL param. It has this signature:

```go
func Param(r *http.Request, key string) string
```

I found I would often have to import `strconv` and convert a number param to an int. So I forked and created a method with a signature like so:

```go
func ParamInt(r *http.Request, key string) (int, error)
```

Then I came across an issue with query parameters. I want to get a query parameter by name without having to parse it manually on each endpoint, and they also might be numbers that should be converted to ints.

So I created these two signatures as well:

```go
func QueryString(r *http.Request, key string) string
func QueryStringInt(r *http.Request, key string) (int, error)
```

Here is the logic for everything:

context.go:
```go
// Param returns the url parameter from a http.Request object.
func Param(r *http.Request, key string) string {
	if rctx := RouteContext(r.Context()); rctx != nil {
		return rctx.Param(key)
	}
	return ""
}

// ParamInt will get a param from the request URL and attempt to parse it as an int.
func ParamInt(r *http.Request, key string) (int, error) {
	val, err := strconv.Atoi(Param(r, key))
	if err != nil {
		return 0, err
	}
	return val, nil
}

// Query will get a query parameter by key.
func QueryString(r *http.Request, key string) string {
	if rctx := RouteContext(r.Context()); rctx != nil {
		return rctx.QueryString(key)
	}
	return ""
}

// QueryInt will get a query parameter by key and convert it to an int or return an error.
func QueryStringInt(r *http.Request, key string) (int, error) {
	val, err := strconv.Atoi(QueryString(r, key))
	if err != nil {
		return 0, err
	}
	return val, nil
}
```

Would you be willing to implement this so I don't need to use a forked version? :P

**Comment by VojtechVitek** [comment]
This is indeed handy and we use something similar internally. I think this could be a nice standalone package, ie. https://github.com/go-chi/param.

```
i, _ := param.Int64(r, "id")

str, _ := param.String(r, "hash")
```

Thoughts?

**Comment by VojtechVitek** [comment]
yeah, it can rely on chi's context, why not

**Comment by lansana** [comment]
@VojtechVitek How would I go about creating the `param` package? I've created it on my end, would you or anyone else be able to create the param package for go-chi and merge in my changes in my own repository? Haven't done this sort of integration before.

Thanks!

**Comment by VojtechVitek** [comment]
@lansana pls go ahead and hack on it on your Github profile

I'd fork it to go-chi if it's MIT licensed and in a good shape after you're done :) Thanks!

**Comment by oceanicdev** [comment]
Hey guys. It is a good idea and I can help with implementation as well. I think creating that as a subpackage of chi router is preferred way. (like middleware subpackage).

**Comment by oceanicdev** [comment]
@VojtechVitek hello, can I take the initiative and implement it today? How do you think of this idea: if the value from `path` is empty then we try to get value from `query string` and then we cast that to necessary type. Otherwise, we will have `Int64`, `QueryInt64` and etc.

**Comment by lansana** [comment]
I agree with @VojtechVitek on being explicit. Easier to read and predict :)

@oceanicdev Feel free to get started on this or complete it all together. I am still planning to do it and will do it if you have not done it by the time I start. I just got distracted recently with some events and need to focus on them for a couple of weeks.

**Comment by oceanicdev** [comment]
@lansana, @VojtechVitek thanks guys :) I need it urgently so I will complete that today :)

**Comment by oceanicdev** [comment]
@lansana, @VojtechVitek Let's try to use that :) I will add tests later because now I do not have so much time :) Anyway, we can work on it together.

**Comment by mmatczuk** [comment]
@VojtechVitek could this be moved in-house under `github.com/go-chi/chi/param` as it's needed in almost any case.

**Comment by pkieltyka** [comment]
hey guys — go-chi/chi needs to be kept as simple/lean as possible. However, param helpers are easy things for developers to build on their own. Just make `param` subpkg that suits your needs and use it

**Comment by ggicci** [comment]
I think the [ggicci/httpin](https://github.com/ggicci/httpin) is what you're looking for. And recently I'm working on how to integrate it with other packages including gochi. Any suggestions are welcomed :)
