### ISSUE TITLE
HandleFunc() has different signature than stdlib Mux

### ISSUE THREAD

**Issue by utrack** [go-chi/chi#322]
chi.Router has
`HandleFunc(string, http.HandlerFunc)`
while http.ServeMux has
`HandleFunc(string, func(http.ResponseWriter, *http.Request))`.

It's not possible to cover standard function `HandleFunc()` under a single interface at the moment because of that.

**Comment by pkieltyka** [comment]
Unfortunately the signatures are set. We tried to be close to stdlib but couldn't do so to be flexible to all cases. Can you provide some example code of what you're trying to do?

**Comment by utrack** [comment]
@pkieltyka see the sample @ https://github.com/utrack/chi-322/blob/master/main.go

`chi.Router` accepts `http.HandlerFunc` and std mux accepts `func(ResponseWriter, *Request)`.
They're the same, just the name is different - however, since Go doesn't resolve interfaces recursively, we can't use the same interface for `chi.Router` and std mux.

**Comment by Adirio** [comment]
I think this change should not break the API at all as both `func(http.ResponseWriter, *http.Request)`s and `http.HandlerFunc`s are admited in both signatures as proven in [this playground](https://play.golang.org/p/zxbo1VH0Foy). I made a registry just to have some struct to hold the functiosn with the different signatures. I included a third kind of signature accepting `http.Handler`s directly and provided a non-`http.HandlerFunc` implementation of `http.Handler`.

I would then suggest, for consistency's shake and to avoid future missunderstandings, to keep the signature the same as `nett/http`.

**Comment by nhooyr** [comment]
I'd side with Chi here. Using `http.HandlerFunc` is just cleaner. It was a mistake by `net/http` to not use it.

**Comment by nhooyr** [comment]
Maybe this is a bug in Go and the interface should be considered implemented by Chi.

**Comment by nhooyr** [comment]
Given functions autocast to http.HandlerFunc

**Comment by utrack** [comment]
It's not a bug, there's no deep interface conversion by Go 1 spec.

**Comment by nhooyr** [comment]
Yea my bad, I guess by bug I meant missing feature. Given you can directly use a `func(w http.ResponseWriter, r *http.Request)` as a `http.HandlerFunc`, why not consider the two interfaces equal?

**Comment by utrack** [comment]
Please try running https://github.com/utrack/chi-322/blob/master/main.go from my 2nd comment to see the problem.

**Comment by pkieltyka** [comment]
this will not change in chi.

But FYI, for a var of type HandlerFunc, you can call `.ServeHTTP` which is an http.Handler

**Comment by utrack** [comment]
I feel like no one had actually bothered to see an example :) But I've got your point.

**Comment by nhooyr** [comment]
@utrack I see the issue

The interface

```
type handler interface {
	HandleFunc(string, func(http.ResponseWriter, *http.Request))
}
```

Is not equal to

```
type handler interface {
	HandleFunc(string, http.HandlerFunc)
}
```

I'm saying maybe Go should consider them the same.
