### ISSUE TITLE
Cant use regex to match routes with and without trailing slash

### ISSUE THREAD

**Issue by Tom29** [go-chi/chi#325]
I tried to handle 2 routes like this:
`domain/things/9
`and
`domain/things/9/`
with same function, but it doesn't work.
Here is the code:
```
r.HandleFunc("/things/{id:[0-9](?:\\/)?}", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("match"))
	})
```

**Comment by lceconi** [comment]
I couldn't make this work 😅  Can somebody post the answer? I want my route to work both with slash and without it, calling the same handler:
```
r.Get("/my-route", myHandler)
r.Get("/my-route/", myHandler)
```
