### ISSUE TITLE
Run time panic when compiling with vgo

### ISSUE THREAD

**Issue by Daniel-M** [go-chi/chi#330]
### Details
The same go-chi implementation shows errors at runtime related to the tool used to compile it. When compiled with `go build` the code snippet (below) runs as expected. When compiled with `vgo build` the binary throws a panic

### Error

```sh
panic: chi: unsupported middleware signature: func(chi.Handler) chi.Handler

goroutine 1 [running]:
github.com/go-chi/chi.assertMiddleware(0x7bb3e0, 0x8628f8, 0x1, 0xc42022b720)
```

### System details
* **vgo**: go version go1.10.2 linux/amd64 vgo:2018-02-20.1
* **go**: go version go1.10.2 linux/amd64 (manually installed)
* **OS**: Linux 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 GNU/Linux

### Ways of reproduce the error
I have the following code snippet:

```go
package main

import (
	"net/http"
	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)


func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("root."))
	})

	http.ListenAndServe(":3333", r)
}
```

Compile with,

```sh
vgo build
```
Then run the binary and the panic above is thrown

Compile as,

```sh
go build
```
Then run the binary and the panic never happens

**Comment by Daniel-M** [comment]
Could it be that, somehow, `vgo` rewrites the `middleware` interface signature from `http.handler` to `chi.Handler`? the relevant portion of the code which throws the error is,

```
// Runtime type checking of the middleware signature
func assertMiddleware(middleware interface{}) interface{} {
	switch t := middleware.(type) {
	default:
		panic(fmt.Sprintf("chi: unsupported middleware signature: %T", t))
	case func(http.Handler) http.Handler:
	case func(Handler) Handler:
	}
	return middleware
}
```

**Comment by VojtechVitek** [comment]
Your vgo is probably pulling chi v1.0.0 instead of latest v3.3.2. This is vgo problem.. See https://github.com/go-chi/chi/pull/327 and https://github.com/golang/go/issues/25967

**Comment by Daniel-M** [comment]
@VojtechVitek Actually just found out this by myself and was about to close this issue

The solution was to change `go.mod` as:

```go
require (
	github.com/go-chi/chi v2.0.0
	github.com/pressly/chi v2.0.0
        ...
)
```

**Comment by Daniel-M** [comment]
@VojtechVitek Actually just found out this by myself and was about to close this issue

The solution was to change go.mod as:
```
require (
	github.com/go-chi/chi v2.0.0
	github.com/pressly/chi v2.0.0
        ...
)
```

**Comment by VojtechVitek** [comment]
note that v2.0.0 is old version that is not maintained anymore :)

**Comment by Daniel-M** [comment]
@VojtechVitek Oh, thanks, which version should I use then?

**Comment by Daniel-M** [comment]
The following worked for me

```
require (
    github.com/go-chi/chi v3.3.2
...`
