### ISSUE TITLE
Mistake in REST example?

### ISSUE THREAD

**Issue by jpincas** [go-chi/chi#331]
From the [REST example](https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L353)

```go
func NewArticleResponse(article *Article) *ArticleResponse {
	resp := &ArticleResponse{Article: article}

	if resp.User == nil {
		if user, _ := dbGetUser(resp.UserID); user != nil {
			resp.User = NewUserPayloadResponse(user)
		}
	}

	return resp
}
```

Is the `if` clause redundant here?

**Comment by pkieltyka** [comment]
@jpincas yes, in that block of code it is redundant. It's there for illustrative purposes though in a way to think about how to build a ArticleResponse payload, in case the resp.User set somewhere else. Not so much a mistake, more of redundant/illustrative.
