### ISSUE TITLE
Feature request: add the possibility to print registered routes for debug purposes

### ISSUE THREAD

**Issue by titpetric** [go-chi/chi#332]
When setting up drone.ci I noticed that they use a [gin/debug.go](https://github.com/gin-gonic/gin/blob/master/debug.go) feature to print all the registered routes, namely `debugPrintRoute` method. It would be nice to have an utility function that would produce somewhat standard output;

Here's my stab at that function:

~~~
var printRoutes func(chi.Routes, string, string)
printRoutes = func(r chi.Routes, indent string, prefix string) {
        routes := r.Routes()
        for _, route := range routes {
                if route.SubRoutes != nil && len(route.SubRoutes.Routes()) > 0 {
                        fmt.Printf(indent+"%s - with %d handlers, %d subroutes\n", route.Pattern, len(route.Handlers), len(route.SubRoutes.Routes()))
                        printRoutes(route.SubRoutes, indent+"\t", prefix+route.Pattern[:len(route.Pattern)-2])
                } else {
                        for key, fn := range route.Handlers {
                                fmt.Printf("%s%s\t%s -> %s\n", indent, key, prefix+route.Pattern, runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name())
                        }
                }
        }
}
printRoutes(r, "", "")
~~~

The function, like gin, uses reflection to print the name of the individual handlers.

And an example output:

~~~
/module/* - with 10 handlers, 5 subroutes
        DELETE  /module/content/delete -> crm.(*ModuleHandlers).ContentDelete-fm
        POST    /module/content/edit -> crm.(*ModuleHandlers).ContentEdit-fm
        GET     /module/content/list -> crm.(*ModuleHandlers).ContentList-fm
        POST    /module/edit -> crm.(*ModuleHandlers).Edit-fm
        GET     /module/list -> crm.(*ModuleHandlers).List-fm
/types/* - with 10 handlers, 2 subroutes
        GET     /types/list -> crm.(*TypesHandlers).List-fm
        GET     /types/type/{id} -> crm.(*TypesHandlers).Type-fm
~~~

What's missing:

- info about middleware (not sure it should even be included)
- a better way to output this stuff (io.Writer, colors, standard structured logger?)

I'd love to improve it, and submit a PR for something like `chi.Debug(chi.Router)`. Comments for improvements are welcome, and I hope I didn't have a blind spot somewhere and missed that something like this already exists in chi :)

**Comment by VojtechVitek** [comment]
Try chi.Walk():

```go
walkFunc := func(method string, route string, handler http.Handler, middlewares ...func(http.Handler) http.Handler) error {
	fmt.Printf("%s %s\n", method, route)
	return nil
}

if err := chi.Walk(r, walkFunc); err != nil {
	fmt.Printf("Logging err: %s\n", err.Error())
}
```

**Comment by titpetric** [comment]
Another example in the wild, django in debug mode:

![image](https://user-images.githubusercontent.com/233360/48707408-a6a7c200-ebff-11e8-9b48-4eac60ecc1eb.png)

This one comparatively just prints the routes to the browser, in case you hit a 404 (which usually for APIs is also the root URL `/` since endpoints are usually prefixed with things like `/account`, `/users`, etc.).

There are obvious differences between the server-side and the client-side route print in intent, but both are very usable when you're either 1) looking for the implementation of an endpoint, or 2) figuring out which endpoints are available just by opening and navigating the 404 pages.

**Comment by pkieltyka** [comment]
@titpetric have you tried something like https://github.com/go-chi/chi/blob/master/_examples/router-walk/main.go ? there is also https://github.com/go-chi/docgen

**Comment by titpetric** [comment]
@pkieltyka no, i'm using pretty much the same code snippet as above, [here](https://github.com/crusttech/crust/blob/master/crm/routes.go#L43). I'll take a look at docgen to see if I can use the docgen as the 404 page like django does in the above example. Thanks.
