### ISSUE TITLE
Wildcard must be the last pattern in a route but it is not enforced in some cases

### ISSUE THREAD

**Issue by adamwasila** [go-chi/chi#333]
This code runs smoothly although gives unexpected results:
```go
r := chi.NewRouter()
r.Get("/*/this/is/ignored", myHandler())
```
Problem is that anything past the wildcard seems to be ignored, thus in this example - requesting ANY path prefixed with _/test/_, eg. _/test/blah/blah/blah_ causes handler to be called.

On the other case, if you simply modify the code:
```go
r := chi.NewRouter()
r.Get("/*/this/is/{not}/ignored", myHandler())
```
(path with named param and wildcard together), then code simply panics at the startup with clear and meaningful error:
```
panic: chi: wildcard '*' must be the last pattern in a route, otherwise use a '{param}'
```

So, what I believe expected behaviour would be to panic consistently in both cases, with exactly same error. Am I right?

**Comment by pkieltyka** [comment]
@adamwasila yes thats exactly right, both cases should catch. thanks for noticing and reporting this. I've fixed it in v4
