### ISSUE TITLE
Redirect slashes middleware should be documented to be incompatible with http.FileServer

### ISSUE THREAD

**Issue by nhooyr** [go-chi/chi#343]
https://github.com/go-chi/chi/blob/44932d207a10cd2f26b06095a61843c9807188ea/middleware/strip.go#L29

http.FileServer will redirect requests for a directory without the trailing slash to include the trailing slash. If a chi user has enabled the redirect slashes middleware, that will then redirect the request back and so on.

This edge case should be documented.

**Comment by pkieltyka** [comment]
done in #378
