### ISSUE TITLE
http.CloseNotifier is deprecated

### ISSUE THREAD

**Issue by wayneashleyberry** [go-chi/chi#347]
```
middleware/wrap_writer.go:103:38: http.CloseNotifier is deprecated: the CloseNotifier interface predates Go's context package. New code should use Request.Context instead.  (megacheck)
	cn := f.basicWriter.ResponseWriter.(http.CloseNotifier)
	                                    ^
middleware/wrap_writer.go:129:7: http.CloseNotifier is deprecated: the CloseNotifier interface predates Go's context package. New code should use Request.Context instead.  (megacheck)
var _ http.CloseNotifier = &httpFancyWriter{}
```

Started seeing this pop up in my linters, not sure if this code could simply be removed?

- https://github.com/go-chi/chi/blob/b5294d10673813fac8558e7f47242bc9e61b4c25/middleware/wrap_writer.go#L103

- https://github.com/go-chi/chi/blob/b5294d10673813fac8558e7f47242bc9e61b4c25/middleware/wrap_writer.go#L143

---

From godoc.org:

> Deprecated: the CloseNotifier interface predates Go's context package. New code should use Request.Context instead. — https://golang.org/pkg/net/http/#CloseNotifier

**Comment by pkieltyka** [comment]
done in #378
