### ISSUE TITLE
Is it possible to know the matched pattern inside a handler?

### ISSUE THREAD

**Issue by sudo-suhas** [go-chi/chi#352]
When a request is matched to a handler with the patterns such as `/articles/{articleID}`, is it propagated in the request context? My use-case is to use this pattern instead of the URL for instrumentation. And if so, would that be available in the middleware as well?

**Comment by pkieltyka** [comment]
yes its possible. check this issue, it might help clear up how to do this: https://github.com/go-chi/chi/issues/270

**Comment by sudo-suhas** [comment]
Thanks!
