### ISSUE TITLE
Differences between Group, Mount, and Route and inner workings of Group?

### ISSUE THREAD

**Issue by SuperFluffy** [go-chi/chi#354]
~~I am a bit confused about how the three function `Group`, `Mount`, and `Route` differ from each other.~~

~~So `Route` is more or less a convenience function for `Mount`, which becomes obvious from the source code.~~

~~Now, `Group` has the following doc entry:~~

~~> Group creates a new inline-Mux with a fresh middleware stack. It's useful for a group of handlers along the same routing path that use an additional set of middlewares.~~

~~What does this offer compared to just using `Mount`? In which way is the behaviour different?~~

~~When I use `Group`, are middlewares from the parent mux called? In the case of `Mount`, are the middlewares from the parent mux called?~~

I got the difference. `Mount` and `Route` mount are for child routes under a new parent route (which itself is the child of the current route). `Group` is for changing the behaviour of child routes under the 
current route.

So my final and only question is:

I have noticed that `Group` return `im` (which is of type `*Mux`), but it's not assigned anywhere. How do you actually register this new inline mux so that the parent mux knows how to call it?

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/blob/master/mux.go#L247 is where routes are added to the new inline mux made by Group.

glad you figured out the other parts
