### ISSUE TITLE
PUT route being processed as GET

### ISSUE THREAD

**Issue by rocanion** [go-chi/chi#355]
I have configured a chi route for a PUT operation like this:
```
router := chi.NewRouter()
router.Put("/user/{id}", updateUser)
```

I have a form tag in a template for the purpose of updating the record. The form is configured to use a PUT method. When I submit the form it actually generates a GET operation with the form data url-encoded as query data.

So I changed the form to use the convention for handling a PUT to be like this:

```
<form action="/user/1234" method="POST">
<input type="hidden" name="_method" value="PUT">
... form data tags are here ...
</form>
```

But doing that results in a 404 Page not found

So I decided to create a new routing rule for a create action like this:

```
router.Post("/user/{id}", createUser)
```

and made the corresponding function to handle it. Then put a debugger breakpoint into both the createUser and updateUser functions to see which would be invoked by the routing rules.

The createUser function was called every time! So it seems that it is not possible to get chi routing to properly handle a conventional PUT operation.

**Comment by rocanion** [comment]
FYI, I found a workaround for now, but strongly feel that this should be in the core code.

I add this middleware hook:
```
router.Use(putConversion)
```

And the putConversion code looks like this:

```
// putConversion is a middleware component that checks for the combination of a
// POST method with a form field named _method having a value of PUT. This is the
// convention for how to establish a PUT method for form submission in a restful API.
// It should run early in the middleware stack.
func putConversion(next http.Handler) http.Handler {
	return http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {
			if r.Method == "POST" {
				r.ParseForm()
				if r.Form["_method"] != nil && r.FormValue("_method") == "PUT" {
					r.Method = "PUT"
				}
			}
			next.ServeHTTP(w, r)
		})
}
```

**Comment by pkieltyka** [comment]
nice work, you did the right thing by writing your own handler for it

**Comment by rocanion** [comment]
If you don't plan to add this to the code then at least document it so that other people don't encounter the problem and have to figure it out themselves.

**Comment by rocanion** [comment]
Ah, Vojtech you have a bit more to learn then.

The REST model is based on the use of various http methods for the different CRUD actions like this:
POST is used for Create
GET is used for Read
PUT is used for Update
DELETE is used for Delete

Now while your observation about only POST and GET being actually used in HTML forms is somewhat accurate (there are browsers that fully support more methods) there are ways that have been devised to support additional http methods such as PUT.

NOTE: the DELETE method is not allowed in forms.

To implement a PUT method in a form you specify the form’s method as POST and then create a hidden input variable to indicate that the form data should be handled as a PUT operation. Here’s an example

```
<form action="/user/1234" method="POST">
<input type="hidden" name="_method" value="PUT">
... form data tags are here ...
</form>
```

Because the Chi router is defined as supporting these different methods for creating RESTful code my argument is that proper support for the detection and handling of the PUT method should be part of the Chi core. Otherwise you allow people to define a route using Put() but the code fails to process it correctly. Refer to my earlier comments in this thread for the specific details.

From the perspective of creating a proper REST API you cannot use POST for everything. As an example let's consider the following chi routing rule set that would be typical of a REST API:

```
router := chi.NewRouter()
router.Get("/user", ListAllUsers)
router.Get("/user/{id}", ShowUser)
router.Post("/user", CreateUser)
router.Put("/user/{id}", UpdateUser)
router.Delete("/user/{id}", DeleteUser)
```

You can see from the above that there is a clear distinction between the creation of a new user and updating an existing user. Using POST for both create and update operation breaks the REST model.

You may find these references to be educational:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

Does this help?

**Comment by VojtechVitek** [comment]
> Ah, Vojtech you have a bit more to learn then.

😕 I'm confused about your tone.

> To implement a PUT method in a form you specify the form’s method as POST and then create a hidden input variable to indicate that the form data should be handled as a PUT operation. Here’s an example

In your example, the browser sends a POST request via a `<form>` submission. So, from the REST perspective, this is POST request. The server just need to handle POST method, ie. via `r.POST()` in case of chi router.

I repeat, PUT method is not supported in `<form>` HTML element by any major browsers, see https://www.w3schools.com/tags/att_form_method.asp

However, your approach mimics the unsupported PUT method by adding some hidden input fields into the `<form>`, that must be in return handled by some extra logic on the backend side.

>  // This is the convention for how to establish a PUT method for form submission in a restful API.

Is this approach standardized by any RFC?

**Comment by pkieltyka** [comment]
chi is not a REST framework. its a router that so happens to be good at writing REST services. @rocanion please learn to use form posts properly, and please do not use these issues at a stackoverflow. good luck to you sir.

**Comment by rocanion** [comment]
Ah, my apologies for the wrong tone. I'm trying to be helpful here. I love chi and think it is a great set of packages and my goal is to help it to be even better. That's why I'm taking the time to comment on this. There is no intent to have this be a stackoverflow type of discussion.

You can see some of the history of how the put handling I implemented came to be in this discussion about the implementation of PUT in HTML forms:

https://www.w3.org/Bugs/Public/show_bug.cgi?id=10671
In particular refer to comment 4 by Mike Amundsen

To directly answer the question about RFCs for handling a PUT - there are none. This is simply a convention established as a workaround for not having direct support for the PUT method in a form.

Anyway, I'm really just trying to help improve things, so if I offended then that was not intentional on my part.

**Comment by VojtechVitek** [comment]
I recommend creating a new repo with the `func putConversion(next http.Handler) http.Handler {` middleware, motivation and bunch of examples. We can link it back from this conversation.

Thanks

**Comment by rocanion** [comment]
Okay, I’ll do that.

**Comment by logrusorgru** [comment]
```go
// Package PPD implements HTTP middleware to replace reqeust method by
// POST-form "_method" value. It supports PUT, PATCH and DELETE methods.
package ppd

import (
	"net/http"
	"strings"
)

// The Method is the middleware.
func Method(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			switch strings.ToLower(r.PostFormValue("_method")) {
			case "put":
				r.Method = http.MethodPut
			case "patch":
				r.Method = http.MethodPatch
			case "delete":
				r.Method = http.MethodDelete
			default:
			}
		}
		next.ServeHTTP(w, r)
	})
}
```

```go
mux.User(ppd.Method)
```

**Comment by oliverpool** [comment]
Would it be acceptable to add such a middleware to this repo, to make it easily available? (but not included by default)

```go
// MethodSpoofing allows to spoof PUT, PATCH and DELETE methods from HTML forms, using the _method field.
// <input type="hidden" name="_method" value="PUT">
func MethodSpoofing(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			switch method := r.PostFormValue("_method"); method {
			case http.MethodPut:
				fallthrough
			case http.MethodPatch:
				fallthrough
			case http.MethodDelete:
				r.Method = method
			default:
			}
		}
		next.ServeHTTP(w, r)
	})
}
```
