### ISSUE TITLE
Double slash ignores regex in Route

### ISSUE THREAD

**Issue by matematik7** [go-chi/chi#357]
When using regex defined parameters in `r.Route`, you can use double slash to bypass the validation.

Example:
Going to `//test` with the following server code will display `Hi: test`, ignoring numbers only regex validation. 
```golang
func main() {
	r := chi.NewRouter()
	r.Route("/{param:[0-9]+}", func(r chi.Router) {
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte(fmt.Sprintf("Hi: %s", chi.URLParam(r, "param"))))
		})
	})
	http.ListenAndServe(":3000", r)
}

```

**Comment by piotrkubisa** [comment]
I don't know if it is feature or not but I tried to be more pushy and tried on your code to put `param` some weird value:

![screenshot from 2018-11-11 14-27-49](https://user-images.githubusercontent.com/3073499/48313531-290c0280-e5be-11e8-9740-5a2366f2c48a.png)

I don't know if it is feature or not, but I'd go with the following code:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()
	r.Route("/{param:[0-9]+}", func(r chi.Router) {
		r.Get("/{param}", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte(fmt.Sprintf("Hi: %s", chi.URLParam(r, "param"))))
		})
	})
	http.ListenAndServe(":3000", r)
}
```

Some tests:

![screenshot from 2018-11-11 14-34-18](https://user-images.githubusercontent.com/3073499/48313568-ee569a00-e5be-11e8-9f81-2373110bf939.png)

![screenshot from 2018-11-11 14-34-05](https://user-images.githubusercontent.com/3073499/48313564-e5fe5f00-e5be-11e8-953c-190a26e9a242.png)

![screenshot from 2018-11-11 14-33-53](https://user-images.githubusercontent.com/3073499/48313563-e5fe5f00-e5be-11e8-84ce-c15962394f53.png)

**Comment by piotrkubisa** [comment]
> @piotrkubisa r.Route should be used to group routes with common prefix together. It becomes useless if you have to repeat param in all children.

I know it it quite weird that you need to repeat yourself in any sub-route to pass the same route. In my example I have presented how to initialize param validation on the router side. The `{param} in `r.Get` has the same validation regex as in the `r.Route`. Personally, I don't know why `chi` works in this way but I haven't had any complex use-case when I really need to use regex-in-router. I hope some maintainer will shed some light on this feature :wink: 

> Also I should mention that if you rely on regex for validation and do not check input further before using it in sql, this could be a serius security issue.

I partially understand your point. It is clear if you need to enforce various checks against ownership and generally speaking a correct input  of the HTTP request. In `chi` and in many packages in various languages there are various types of middlewares or middleware-like-funcs which are included in router or implemented directly in the handler to take care of input validation/sanitization. Could you tell me what do you exactly mean?

**Comment by piotrkubisa** [comment]
The problem arises when you are going to use my implementation in following way:

``go
func main() {
	r := chi.NewRouter()

	r.Route("/{param:[0-9]+}", func(r chi.Router) {
		r.Get("/{param}/posts", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte(fmt.Sprintf("Hi: %s", chi.URLParam(r, "param"))))
		})
		r.Get("/{param}/profile", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte(fmt.Sprintf("Hi: %s", chi.URLParam(r, "param"))))
		})
	})
	http.ListenAndServe(":3000", r)
}
```

In that scenario my code does not work as I stated in previous post. 

```
GET http://localhost:3000/12/posts
404 page not found
```

```
GET http://localhost:3000/123/12/posts
Hi: 12
```

**Comment by efarem** [comment]
I ran into something similar today using a single `Get` route resulting in a panic from `chi.URLParam`, example below.

```golang
func main() {
	r := chi.NewRouter();
	r.Get("/{type:(one|two|three)}/something", func (w http.ResponseWriter, r *http.Request) {
	    w.Write([]byte(fmt.Sprintf("Hello %s", chi.URLParam(r, "type"))))
	})
        http.ListenAndServe(fmt.Sprintf(":%d", 3000), r)
}
```

```
GET http://localhost:3000/one/something
Hello one
```

```
GET http://localhost:3000//something
runtime error: index out of range
```

**Comment by pkieltyka** [comment]
thanks for the report + suggestions -- fixed: https://github.com/go-chi/chi/commit/3658d98ee4dc2e8e25a4b7cf759ad0dd42f4c075
