### ISSUE TITLE
In special cases, 500 internal server error

### ISSUE THREAD

**Issue by MetalBreaker** [go-chi/chi#361]
Hi. I'm trying to, by default, route all requests made to my server to a file server, except for some cases where I'm trying to make an API.
This is my code:
```
func main() {
	r := chi.NewRouter()
	r.Use(
		render.SetContentType(render.ContentTypeJSON),
		middleware.Logger,
		middleware.DefaultCompress,
		middleware.RedirectSlashes,
		middleware.Recoverer,
	)
	fs := http.FileServer(http.Dir("static"))

	r.Handle("/*", fs)
	r.Get("/api/{endpoint}", apiHandler)

	/* Irrelevant code */
}
```
This works, for the most part. The issue arises when I add something like "`<b>abc</b>`" to the URL. Using http.Handle (not Chi) works as expected, and throws a 404 not found error.
However, Chi, for some reason, throws a 500 internal server error.
Example:
![image](https://user-images.githubusercontent.com/6906399/48921236-b5f86b00-ee9e-11e8-8ca9-e12b87ca7784.png)
![image](https://user-images.githubusercontent.com/6906399/48921246-c6104a80-ee9e-11e8-85c5-4df28325b6eb.png)

For the API endpoint (using a named parameter), if I only open an HTML tag (`<b>`),  it works as expected. If I also close it (`<b></b>`), it returns a 404 instead of actually setting the named parameter.

Thanks in advance.

**Comment by VojtechVitek** [comment]
Can you share the version of chi you're using and a full trace of the panic error?

**Comment by VojtechVitek** [comment]
@MetalBreaker the version matters actually, the new `go get` with Go modules support might download v1.x version instead of v3.x. You can check the `git log` in your `$GOPATH/src/github.com/go-chi/chi` directory.

**Comment by MetalBreaker** [comment]
![image](https://user-images.githubusercontent.com/6906399/48922504-69655d80-eea7-11e8-954b-a44d9392934f.png)
Is this Chi v3?

**Comment by VojtechVitek** [comment]
yes it is.

now make sure you use
```
 r.Use(middleware.Logger)
 r.Use(middleware.Recoverer)
```

and pls report back the actual error / panic.

**Comment by MetalBreaker** [comment]
I'm already using those, as you can see in the code I posted, and I can't see a panic that actually happens. I feel like I'm missing something. Maybe you misunderstood me; the server continues working after the 500 error like nothing happened (logger just logs a 500 error, posted above), I just find the 500 response a bit weird when for example, google.com/?q=<b> works.

**Comment by VojtechVitek** [comment]
hmm, I see .. so this error is coming from

```
fs := http.FileServer(http.Dir("static"))

r.Handle("/*", fs)
```

So this is not a chi returning the HTTP 500 - it's the stdlib's http.FileServer.

**Comment by MetalBreaker** [comment]
Wait, I'm confused... How does it work fine with a router like Gin or the default http router, but only fails with Chi? Is it something to do with the way of passing the arguments to FileServer or something?
