### ISSUE TITLE
Chi should not panic when no routes

### ISSUE THREAD

**Issue by makhov** [go-chi/chi#362]
Hello!

We use a generic service skeleton based on chi in our company. Sometimes we needn't handle http-request and our skeleton creates chi.Mux with no roures.

If someone try to ping our service, it fails with panic because of [this if section](https://github.com/go-chi/chi/blob/master/mux.go#L62-L64). 

I think Chi should return 404 error instead of panic.

**Comment by VojtechVitek** [comment]
Why don't you add a 404 handler in your skeleton app's code?

I'm not sure if this is the right call. The panic might be useful for some folks that forget to mount the handlers correctly.

Let's poll the community for their opinions:
👍 for HTTP 404; 👎 for keeping the panic

**Comment by makhov** [comment]
I understood your point, but in this case we create a service which can panic at the random moment when someone send any http request. And developer don't know about this behavior. 

Maybe we should panic at service startup

**Comment by VojtechVitek** [comment]
@makhov that's a good point, thanks. Let me add it as a third option to the poll.

**Comment by pkieltyka** [comment]
done in https://github.com/go-chi/chi/pull/378 -- in v4, we will return 404 for an empty mux
