### ISSUE TITLE
How to use different ReadTimeout WriteTimeout and TimeoutHandler for different routes?

### ISSUE THREAD

**Issue by Tom29** [go-chi/chi#365]
I want to optimize resources to serve different routes with Go.
Like this:

 - `api/*` route will have only 5s to serve 1 request
 - `api/upload` route will have 30s request timeout to allow user to upload 10mb file.

After reading this https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/ i figure out that i can control them via using `ReadTimeout` , `WriteTimeout` and `TimeoutHandler`

But i have to separate them to different server and config them like this

 - `api/*` will have `TimeoutHandler` = `WriteTimeout` = 5s, `ReadTimeout`
   = 2s 
 - `api/upload` will have `ReadTimeout` = `TimeoutHandler` = 30s (to read request body) , `WriteTimeout` = 2s (to write response uploading has been successfully or not)

**Comment by VojtechVitek** [comment]
Use different Timeout middleware for each of these routes.

Take a look at examples:
https://github.com/go-chi/chi/blob/master/_examples/limits/main.go

**Comment by Tom29** [comment]
@VojtechVitek i've read it, i don't understand how it works.
After putting `	time.Sleep(30 * time.Second)` on top of it, it still take 30s to finish the task.
how is the way to use `TimeoutHandler`?
https://github.com/go-chi/chi/issues/198#issuecomment-302954438

**Comment by VojtechVitek** [comment]
That's because you need to listen on the `<-ctx.Done()` in your "worker" logic. `time.Sleep()` doesn't respect it the context deadline.

You'd have to use

```go
select {
	case <-ctx.Done():
		// force timeout
	case <- time.After():
		// this is the heavy work
		// in real world, you'd pass the ctx to the worker functions
}
```

For further questions about Go, please consult Gopher Slack or community forums.
