### ISSUE TITLE
Bring supported versions inline with Go release policy

### ISSUE THREAD

**Issue by SamWhited** [go-chi/chi#366]
I would like to propose that only supported versions of Go (the last two versions, per the release policy: https://golang.org/doc/devel/release.html#policy) be supported officially by Chi.

This would allow Chi to be more agile in introducing new features such as Go Modules (#364) which have compatibility built into supported versions (eg. a workaround for full module support was introduced in Go 1.9.7 and Go 1.10.3).

Unfortunately, to my knowledge no one is collecting Go version information so it's hard to estimate how many users would be affected by such a change.

Thank you for your consideration.

**Comment by pkieltyka** [comment]
done in chi v4 https://github.com/go-chi/chi/pull/378
