### ISSUE TITLE
Sending the Request ID to Caller

### ISSUE THREAD

**Issue by husainaloos** [go-chi/chi#368]
Chi provides a middle-ware for creating the request id and inserting it into the request context. This is helpful for tracing the life of the request inside the application. But it would also be helpful to return that request id to the caller so that they can trace the life cycle of the request from their side.

Does chi provides any method like that? Is it a good idea to begin with since the request ID seems to be generated based on the hostname.

**Comment by pkieltyka** [comment]
@husainaloos yea, you can write a middleware to take the request ID and do whatever you'd like with it after the response of sent, or right before..
