### ISSUE TITLE
Env var to force colored log?

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#372]
Env var to force colored log?

I'm trying to use `Taskfile` which natively doesn't handle tty. Is there a way to force colored log, like `Gulp` `--color`?

**Comment by frederikhors** [comment]
Same problem with https://github.com/cortesi/modd.

Is there a way to force color in shell when `chi` doesn't detect it?

**Comment by pkieltyka** [comment]
@frederikhors the best bet is for you to copy and fork the logger middleware for your purposes. Copy+paste it and modify for your own project
