### ISSUE TITLE
radical changes

### ISSUE THREAD

**Issue by tweenietomatoes** [go-chi/chi#373]
Dear Peter,
    Please betterise Chi logo,
    Please remove Go 1.7, 1.8 and 1.9 notices,
    Please create a gitter account

Your believer

**Comment by pkieltyka** [comment]
thanks @tweenietomatoes -- I quite like the logo, and I will be deprecating older Go versions in v4, see https://github.com/go-chi/chi/pull/378

as for gitter, that would be fun but unfortunately I don't have the bandwidth to manage such a channel. But Gophers slack is an amazing community with 35k members https://invite.slack.golangbridge.org/
