### ISSUE TITLE
filepath.Clean for fileserver example?

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#376]
Is it needed to use `filepath.Clean` as mentioned here: https://www.alexedwards.net/blog/serving-static-sites-with-go ?

Maybe we should update fileserver example (https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go) with `filepath.Clean`?

**Comment by pkieltyka** [comment]
the path is cleaned without the http.FileServer handler
