### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by 5teven** [go-chi/chi#381]
Hello

Building fails when i use <code>go get -d -v ./...</code> to fetch dependencies

Error:
<code>
package github.com/go-chi/chi/v4: cannot find package "github.com/go-chi/chi/v4" in any of:
	/usr/local/go/src/github.com/go-chi/chi/v4 (from $GOROOT)
	/go/src/github.com/go-chi/chi/v4 (from $GOPATH)
</code>

**Comment by pkieltyka** [comment]
try this against master, does not occur

**Comment by uRevivals** [comment]
Hello,

We got the same problem, it's located with other chi like package in go-chi/jwtauth and go-chi/docgen that ref github.com/go-chi/chi/v4 which does not exists.

**Comment by pkieltyka** [comment]
hey guys, I just caught the problem, ive fixed this with jwtauth and docgen -- can you try again

**Comment by uRevivals** [comment]
Works for me thanks for the reactivity! Do you know any way to freeze the package that we can use to avoid this problem in the future?

**Comment by pkieltyka** [comment]
@uRevivals just peg to specific tags/versions via some go dependency manager and you'll be okay

we tried to make chi a go module, but it backfired a bit. Go modules need more time in the oven

**Comment by 5teven** [comment]
Same thing. Check out this page https://github.com/golang/go/wiki/PackageManagementTools . Hope will help to understand go dep management

**Comment by pkieltyka** [comment]
thx for the tip @5teven but there is no learning a broken system. go modules need more work. the problem should now be resolved with reverts to jwtauth and docgen sub-deps in the examples.

further, chi doesn't even have any dependencies, so install it without -d. the _ in _examples should exclude it from installing those dependencies, but perhaps this has been changed in recent versions of Go? in any case, it was a big mistake for Go core to "leave modules up to community" for so long.. now its a mess. Hopefully they improve in Go 1.13+ when they attempt to remove $GOPATH completely
