### ISSUE TITLE
Redirect doesn't work after v4.0.0-rc1 

### ISSUE THREAD

**Issue by kromanow94** [go-chi/chi#385]
I've just updated the package and suddenly my redirects stopped working.
Doesn't matter if it goes to external page like google, internal, with query params or not.

Checked out a few latest releases and everything after v4.0.0-rc1 does not work.

My golang backend stands behind nginx proxy. Checked out if I have some errors in the nginx configuration, but it doesn't seem so.

I can place place some code or configuration but I don't suspect my configuration to be erogenous.

**Comment by VojtechVitek** [comment]
Please, provide reproducer code. Do you use `middleware.RedirectSlashes`?

**Comment by anurag** [comment]
@kromanow94 are you using Compress middleware? Your issue may be related to https://github.com/go-chi/chi/issues/382.

@VojtechVitek and @pkieltyka is it worth creating a 4.0.1 with the fix since it's breaking everyone who's using compress?

**Comment by kromanow94** [comment]
Sorry for replaying so late! I'm just in the middle of my project for diploma, not having much time for anything else.
Yes, I do. This is my router:
`
router.Use(                                       
    render.SetContentType(render.ContentTypeJSON),
    middleware.Logger,
    middleware.DefaultCompress,
    middleware.RedirectSlashes,
    middleware.Recoverer,
)
`

**Comment by anurag** [comment]
It should be fixed if you downgrade to the previous major version (3.3.4) or use master.

**Comment by kromanow94** [comment]
It does work now with master, thank you! :)

**Comment by VojtechVitek** [comment]
FYI, https://github.com/go-chi/chi/tree/v4.0.1 released.
