### ISSUE TITLE
Using the profile middleware with a router other then debug

### ISSUE THREAD

**Issue by diegobernardes** [go-chi/chi#389]
Here at the company, we have a namespace to set private endpoints on a API, but if I change the 
mount path from debug to another thing, the profile stops working. The index page render, and the profile works too, but other profiles don't work like allocs. Does anyone know a workaround for this problem?

```golang
r.Mount("/debug", middleware.Profiler()) // works
r.Mount("/private/debug", middleware.Profiler()) // don't works
```

**Comment by pkieltyka** [comment]
@diegobernardes copy the middleware.Profiler() code play around with it -- perhaps something inside of net/http/pprof is overriding this
