### ISSUE TITLE
Question: HTTP Status Code

### ISSUE THREAD

**Issue by milesje** [go-chi/chi#394]
How do you set the HTTP Status code to something other than 200?
I have a simple test case below and I'm unable to change the HTTP Status code. It is always a 200 OK. I can render my own text(JSON) but this still does NOT set the HTTP Status code to 401!
```
package main
func routes() *chi.Mux {
	router := chi.NewRouter()
	router.Use(
		render.SetContentType(render.ContentTypeJSON),
		middleware.Logger,
		middleware.DefaultCompress,
		middleware.RedirectSlashes,
		middleware.Recoverer,
		middleware.RealIP,
	)
	router.Get("/test", test)
	return router
}

func test(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(401)
	http.Error(w, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)
	render.Status(r, 401)
	render.Render(w, r, ErrInvalidRequest())
	return
}
type ErrResponse struct {
	Err            error `json:"-"` // low-level runtime error
	HTTPStatusCode int   `json:"-"` // http response status code

	StatusText string `json:"status"`          // user-level status message
	AppCode    int64  `json:"code,omitempty"`  // application-specific error code
	ErrorText  string `json:"error,omitempty"` // application-level error message, for debugging
}

func (e *ErrResponse) Render(w http.ResponseWriter, r *http.Request) error {
	render.Status(r, e.HTTPStatusCode)
	return nil
}

func ErrInvalidRequest() render.Renderer {
	return &ErrResponse{
		// Err:            err,
		HTTPStatusCode: 401,
		StatusText:     "Invalid request.",
		ErrorText:      "Invalid request.",
	}
}
func main() {
	router := routes()

	walkFunc := func(method string, route string, handler http.Handler, middlewares ...func(http.Handler) http.Handler) error {
		log.Printf("%s %s\n", method, route)
		return nil
	}
	if err := chi.Walk(router, walkFunc); err != nil {
		log.Panicf("Loggin err: %s\n", err.Error())
	}
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%d", cfg.SrvPort), router))
}
```
Results - The text is changed but NOT the HTTP status code
```
curl --request GET  --url http://localhost:8080/test -i
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 19 Feb 2019 16:56:46 GMT
Content-Length: 57

Unauthorized
{"status":401,"message":"Invalid request."}
```

**Comment by piotrkubisa** [comment]
In chi (like many other Go stdlib compatible routers) you have to memorize the acronym of Header-Status-Payload (HSP) acronym (just like TopRightBottomLeft in CSS). To illustrate the problem take a look at following unit test: https://gist.github.com/piotrkubisa/4b99eab4257f729abce8db853966b155

**Comment by pkieltyka** [comment]
I suggest you try some simpler examples to get a feel for how Go stdlib works, then read the source of the render package. render.Status() just sets the status, it does not write it to the responsewriter. You need to call render.Render()

**Comment by milesje** [comment]
@pkieltyka I think I will just move on to a different Router at this point. I don't see how I can make it any simpler than the code posted above. I spent about 10 minutes with Gorilla Mux as well as with just using net/http and both of those work as expected.

**Comment by milesje** [comment]
@pkieltyka did you even look at my supplied code... I **AM** calling `render.Render()` which is how it renders the plain/text. However `render.Render()` does **NOT** set the actual HTTP Status to what was specified in `render.Status()`, nor does it preserve what is set using `w.WriteHeader(401)`

**Comment by pkieltyka** [comment]
@milesje it's not my job to be your tech support. I offered the little bit of help I was able, good luck.

**Comment by pkieltyka** [comment]
if you provide a test case and report a bug, I'm happy to solve that when I find the time, or perhaps another contributor wants to help.

as well, the http://github.com/go-chi/render package is not core to the `chi` router, its in a separate repository as a convenience library for a reason. Perhaps try https://github.com/unrolled/render instead

**Comment by milesje** [comment]
OK, after looking over the examples and tests I have determined the problem/solution but I'm not 100% sure why it is or if it was intentional or not.
If I define my route as follows
```
func routes() *chi.Mux {
	router := chi.NewRouter()
	router.Use(
		render.SetContentType(render.ContentTypeJSON),
		middleware.Logger,
		middleware.DefaultCompress,
		middleware.RedirectSlashes,
		middleware.Recoverer,
		middleware.RealIP,
	)
	router.Get("/test", test)
	return router
}

func test(w http.ResponseWriter, r *http.Request) {
	render.Status(r, 401)
	render.Render(w, r, ErrInvalidRequest())
}
```
It always returns a 200 OK for the responses status code.
If I make a simple change...
```
func routes() *chi.Mux {
	router := chi.NewRouter()
	router.Use(
		render.SetContentType(render.ContentTypeJSON),
		middleware.Logger,
		middleware.DefaultCompress,
		middleware.RedirectSlashes,
		middleware.Recoverer,
		middleware.RealIP,
	)
	router.Get("/test", http.HandlerFunc(test))
	return router
}

func test(w http.ResponseWriter, r *http.Request) {
	render.Status(r, 401)
	render.Render(w, r, ErrInvalidRequest())
}
```
By wrapping the call to the test function in a `http.HandlerFunc` makes not return the specified response statusCode.

So my question is... Is this the intended functionality? If so fine I will have to add the wrapping of all of my routes in a http.HanderFunc. If not, you may need to add some test cases to the mux_test.go to check for this scenario. I found this by digging through the mux_test.go where all of the routes have the func to be called wrapped in the http.HanderFunc, but I did not see an documentation stating that this needs to be done.

**Comment by pkieltyka** [comment]
@milesje I've tried out both of your examples above, and both work correctly and return 401 as expected. I'm getting the feeling you might have an old compiled package in $GOPATH/pkg or some other strange linking. Or perhaps outdated deps.

the exact program I ran (and variation with http.HandlerFunc also worked..)

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/render"
)

func main() {
	r := routes()
	http.ListenAndServe(":3333", r)
}

func routes() *chi.Mux {
	router := chi.NewRouter()
	router.Use(
		render.SetContentType(render.ContentTypeJSON),
		middleware.Logger,
		middleware.DefaultCompress,
		middleware.RedirectSlashes,
		middleware.Recoverer,
		middleware.RealIP,
	)
	router.Get("/test", test)
	return router
}

func test(w http.ResponseWriter, r *http.Request) {
	render.Status(r, 401)
	render.Render(w, r, ErrInvalidRequest())
}

type ErrResponse struct {
	Err            error `json:"-"` // low-level runtime error
	HTTPStatusCode int   `json:"-"` // http response status code

	StatusText string `json:"status"`          // user-level status message
	AppCode    int64  `json:"code,omitempty"`  // application-specific error code
	ErrorText  string `json:"error,omitempty"` // application-level error message, for debugging
}

func (e *ErrResponse) Render(w http.ResponseWriter, r *http.Request) error {
	render.Status(r, e.HTTPStatusCode)
	return nil
}

func ErrInvalidRequest() render.Renderer {
	return &ErrResponse{
		// Err:            err,
		HTTPStatusCode: 401,
		StatusText:     "Invalid request.",
		ErrorText:      "Invalid request.",
	}
}
```

unfortunately I can't help you debug your system, but I can confirm the above code returns 401 in both instances on /test route with the handler as `router.Get("/test", test)` and `router.Get("/test", http.HandlerFunc(test))`

**Comment by milesje** [comment]
@pkieltyka I would like to see your output as I installed GO on a completely separate laptop (MacBook Pro) and I'm still getting a 200 OK as the response.
```
 curl --request GET  --url http://localhost:3333/test -i
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Mon, 25 Feb 2019 21:22:50 GMT
Content-Length: 57

{"status":"Invalid request.","error":"Invalid request."}

```
The texting being rendered is correct but the actual status code is still 200 OK, unless I use a http.HandlerFunc to wrap the call to the test function.

**Comment by pkieltyka** [comment]
```shell
curl --request GET  --url http://localhost:3333/test -i
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Mon, 25 Feb 2019 21:30:08 GMT
Content-Length: 57

{"status":"Invalid request.","error":"Invalid request."}
```

this is on a Linux computer wth go1.11.5

perhaps someone else can run on their Mac's to test..? @VojtechVitek if you have time..

**Comment by milesje** [comment]
OK, so I just spun up my Ubuntu VM and ran this here and I do get the 401 status code. But if running the code on Windows or MacOS I get a 200 OK.

```
curl --request GET --url http://172.16.1.34:3333/test -i
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Mon, 25 Feb 2019 21:39:25 GMT
Content-Length: 57

{"status":"Invalid request.","error":"Invalid request."}
```

**Comment by milesje** [comment]
I'm running these versions.
Windows: go version go1.11.5 windows/amd64
Linux: go version go1.11.5 linux/amd64
MacOS: go version go1.11.4 darwin/amd64

**Comment by pkieltyka** [comment]
lol. that is super weird. I'll try on my Mac when I'm home, but that is a curious one..

**Comment by milesje** [comment]
Yes, it is curious! I would have expected all 3 system to behave the same.

**Comment by pkieltyka** [comment]
@milesje sorry dude, I can't reproduce your problem. I just tried on my Mac with go 1.11.4 and the same code above returns a 401 unauth'd code.

unfortunately I'm quite loaded with other work and won't be able to tend to this problem. good luck though! hope it helps a bit

**Comment by milesje** [comment]
@pkieltyka after some testing I have found that if I remove the middleware.DefaultCompress everything works as expected... it returns the 401 on all systems (Windows, Mac, & Linux). If I include the middleware.DefaultCompress than I get a 200 on Windows & Mac and 401 on Linux. I have not looked at the DefaultCompress middleware code to see what it is doing but it somehow appears to be the culprit.

**Comment by pkieltyka** [comment]
good to kno! can you confirm you're using the latest (master) versions of all packages?

**Comment by milesje** [comment]
@pkieltyka how do I do that? I deleted my pkg folder and issued a `go get` prior to each of my tests.
