### ISSUE TITLE
Compress, weird behaviour

### ISSUE THREAD

**Issue by abenz1267** [go-chi/chi#396]
Hello,

i'm facing a certain issue with the compress middleware.

main.go
```go
func main() {
    r := chi.NewRouter()

    r.Use(middleware.Compress(5, "text/plain"))
    //r.Use(middleware.Logger)

    r.Get("/", index)

    http.ListenAndServe(":3000", r)
}

func index(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	w.Write([]byte("hello"))
}
```

This only works, if i use the logger middleware as well. It doesn't if i just use the compress middleware. However, i checked and it does indeed hit the `w.Header().Set("Content-Encoding", w.encoding)` if-branch in the `WriteHeader(code int)` function.

It also works if i set it on the handle through `r.With()`

I'm not exactly sure what i'm missing. Any idea?

Regards

**Comment by pkieltyka** [comment]
thx for report. fixedin 403a33cc14d759085d69fff973da96eefd02cc9c
