### ISSUE TITLE
rewrite Compress middleware

### ISSUE THREAD

**Issue by pkieltyka** [go-chi/chi#397]
the Compress middleware is a bit of a mess and needs a rewrite. As this is not core to the chi router, it's not something I have cycles to work on. However, I'd be happy to see a community contribution that deletes and replaces our current middleware.Compress handler.

A few suggestions/ideas for the new Compress middleware:

- [ ] Compress handler should be implemented as its own type/struct where additional encoders can be set. As opposed to currently the implementation is a single handler, and a lot of logic is outside of it in package-variables. ie. `middleware.SetEncoder()` pollutes the namespace and should be moved.

proposed syntax..

```go
r := chi.NewRouter()
compress := middleware.Compress(5, "text/other")
compress.SetEncoder("br", func(..) { ...})
r.Use(compress.Handler)
...
```

- [ ] Reduce GC overhead by using sync.Pool -- see https://github.com/go-chi/chi/issues/306

**Comment by awbraunstein** [comment]
I'd like to take a swing at rewriting the compress middleware. Can I take this issue?

**Comment by pkieltyka** [comment]
@awbraunstein thanks buddy :) yes, its all yours
