### ISSUE TITLE
How to fileserve for all requests?

### ISSUE THREAD

**Issue by mvrlin** [go-chi/chi#403]
Hey! I am making an SPA and I need to fileserve on every page and also have an REST API.
I tried the [fileserver example](https://github.com/go-chi/chi/tree/master/_examples/fileserver) but I am getting the `404 page not found`.

Using `net/http` **works**
```go
package main

import (
	"net/http"
	"time"
)

func main() {
        server := &http.Server{
		Addr:         ":8080",
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	http.HandleFunc("/foo", func(w http.ResponseWriter, r *http.Request) {
	        w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{ "message": "bar" }`))
	})

	http.Handle("/", http.FileServer(http.Dir("./web/dist")))

	panic(server.ListenAndServe())
}
```

Using `go-chi/chi`  **not found**
```go
package main

import (
	"net/http"
	"time"

        "github.com/go-chi/chi"
)

func main() {
        router := chi.NewRouter()
        server := &http.Server{
		Addr:         ":8080",
                Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	router.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
	        w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{ "message": "bar" }`))
	})

        // 404 Not Found
	router.Handle("/", http.FileServer(http.Dir("./web/dist")))

	panic(server.ListenAndServe())
}
```

**Comment by mvrlin** [comment]
Found the answer by myself.

```go
package cmd

import (
	"net/http"
	"os"
	"time"

	"github.com/go-chi/chi"
)

func main() {
	router := chi.NewRouter()
	server := &http.Server{
		Addr:         ":8080",
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

        router.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
	        w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{ "message": "bar" }`))
	})

	FileServer(router)

	panic(server.ListenAndServe())
}

// FileServer is serving static files.
func FileServer(router *chi.Mux) {
	root := "./website/dist"
	fs := http.FileServer(http.Dir(root))

	router.Get("/*", func(w http.ResponseWriter, r *http.Request) {
		if _, err := os.Stat(root + r.RequestURI); os.IsNotExist(err) {
			http.StripPrefix(r.RequestURI, fs).ServeHTTP(w, r)
		} else {
			fs.ServeHTTP(w, r)
		}
	})
}
```

**Comment by js02sixty** [comment]
I've been struggling with this for days, thank you!

**Comment by js02sixty** [comment]
I adapted your snippet to allow SPA to be served from sub path.  In vue cli its the publicPath config
`package main

import (
	"fmt"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/go-chi/chi"
)

const port = ":3333"

func main() {

	fmt.Printf("Starting Server on Port %v\n", port)
	router := chi.NewRouter()
	server := &http.Server{
		Addr:         port,
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	router.Get("/foo", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{ "message": "bar" }`))
	})

	FileServer(router, "/admin", "dist/")
	FileServer(router, "/", "../admin2/")

	panic(server.ListenAndServe())
}

// FileServer is serving static files
func FileServer(r chi.Router, public string, static string) {

	if strings.ContainsAny(public, "{}*") {
		panic("FileServer does not permit URL parameters.")
	}

	root, _ := filepath.Abs(static)
	if _, err := os.Stat(root); os.IsNotExist(err) {
		panic("Static Documents Directory Not Found")
	}

	fs := http.StripPrefix(public, http.FileServer(http.Dir(root)))

	if public != "/" && public[len(public)-1] != '/' {
		r.Get(public, http.RedirectHandler(public+"/", 301).ServeHTTP)
		public += "/"
	}

	r.Get(public+"*", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		file := strings.Replace(r.RequestURI, public, "/", 1)
		if _, err := os.Stat(root + file); os.IsNotExist(err) {
			http.ServeFile(w, r, path.Join(root, "index.html"))
			return
		}
		fs.ServeHTTP(w, r)
	}))
}
`

**Comment by TonyPythoneer** [comment]
Hi @js02sixty

I have a question about these lines:

```go
	if strings.ContainsAny(public, "{}*") {
		panic("FileServer does not permit URL parameters.")
	}
```

Why does it need to check the "{}*"? Is it for security? I want to know the detail. Thanks.

**Comment by js02sixty** [comment]
> Hi @js02sixty
> 
> I have a question about these lines:
> 
> ```go
> 	if strings.ContainsAny(public, "{}*") {
> 		panic("FileServer does not permit URL parameters.")
> 	}
> ```
> 
> Why does it need to check the "{}*"? Is it for security? I want to know the detail. Thanks.

Your probably right, i basically copied  pkieltyka's example:
[](https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go)

**Comment by pkieltyka** [comment]
@TonyPythoneer @js02sixty hey guys -- the reason we cheque for any parameter characters such as `{}*` is because everything after the routing path that is passed to chi is handled by the handler in http.FileSystem. Therefore chi can't support variables for the folder path, and so we check and error out.

**Comment by terdia** [comment]
This works for me, no need for a separate function

```
router := chi.NewRouter()
... 

fileServer := http.FileServer(http.Dir("./ui/static/"))
router.Handle("/static/*", http.StripPrefix("/static", fileServer))
```

**Comment by omarkohl** [comment]
I solved it by replacing
```go
router.Handle("/", http.FileServer(http.Dir("./web/dist")))
```
with
```go
router.Handle("/*", http.FileServer(http.Dir("./web/dist")))
```

To be precise, my code is a little different, but I _assume_ the example code in the original report would work by making that change.

My code:

```go
//go:embed frontend/build
var embeddedFiles embed.FS

func serveFrontend(router chi.Router) {
	fmt.Println("Serving with frontend")
	router.Handle("/*", http.FileServer(getFileSystem()))
}

func getFileSystem() http.FileSystem {
	fsys, err := fs.Sub(embeddedFiles, "frontend/build")
	if err != nil {
		panic(err)
	}
	return http.FS(fsys)
}
```

**Comment by yuki2006** [comment]
https://github.com/go-chi/chi/issues/403#issuecomment-468911337
With this code

`http://localhost/?query`

I couldn't handle it, so I did this.

`r.RequestURI -> r.URL.Path`

```
	router.Get("/*", func(w http.ResponseWriter, r *http.Request) {
		if _, err := os.Stat(root + r.URL.Path); os.IsNotExist(err) {
			http.StripPrefix(r.URL.Path, fs).ServeHTTP(w, r)
		} else {
			fs.ServeHTTP(w, r)
		}
	})
```
