### ISSUE TITLE
realip.go: X-Forwarded-For should take last address, not first 

### ISSUE THREAD

**Issue by leo-baltus** [go-chi/chi#408]
Hi,

I while browsing through the middleware I think that X-Forwarded-For is not interpreted safely.

Each proxy where a request is passing through adds an address of the remote side of the connection to X-Forwarded-For at the end, resulting in a possibly long list. You should trust only the entries added by your own infrastructure, so the last address. Possibly the nth-before-last address depending on how many proxies you have. On GCP e.g., where there are at least 2 proxies, the remote address is found in the 1-before-last address.

**Comment by Siiiimon** [comment]
The Documentation for `Header.Get` actually says the following:
> Get gets the first value associated with the given key.
...
To access multiple values of a key, or to use non-canonical keys, access the map directly.

I'm using a workaround in my current code to circumvent this issue already but i'm sure i could try for a fix in the actual middleware code.

**Comment by pkieltyka** [comment]
any suggestions what would resolve this in a consistent way?

**Comment by pkieltyka** [comment]
everywhere I've read, the realip is the first address. Perhaps its not consistent across servers so there isn't a single solution. However, one thing we should do is favor the X-Real-IP header over the X-Forwarded-For header when determining the "real ip"

https://github.com/go-chi/chi/commit/83778c0b55a6bbc0e8fe8a656165c07072351b90
