### ISSUE TITLE
Middleware.Compress breaks images (and possibly more?)

### ISSUE THREAD

**Issue by abenz1267** [go-chi/chi#409]
I just noticed it breaks content, if the extension is not in allowedTypes.

```go
r := chi.NewRouter()

c := middleware.Compress(5)
r.Use(c)

wDir, _ := os.Getwd()
path := filepath.Join(wDir, "/public")
fs.Serve(r, "/public", http.Dir(path))

http.ListenAndServeTLS(":3000", os.Getenv("CERT"), os.Getenv("KEY"), r)
```
"The image ... can not be displayed because it contains errors". Same issue in Firefox and Chrome.

Adding the extensions to the allowedTypes "solves" this, but i wouldn't call this solved nor expected behaviour. If i don't want a certain image type to be compressed, it shouldn't break.

Furthermore: adding single content-types seems very cumbersome at the moment, as you have to then also manually add the default content-types.

Regards

**EDIT: after adding the content-types manually it broke everything else. So: the middleware breaks everything that's not in the allowedTypes.**

Edit 2: it kinda makes sense, since the response will always be written through the encoder:
```go
Line 341: return cw.w.Write(p)
```

where `cw.w` = encoder

**Comment by abenz1267** [comment]
Possible fix:

```go
// Is the content type compressable?
if _, ok := cw.contentTypes[contentType]; !ok {
cw.w = cw.ResponseWriter
return
}
```

Although it would be nice to determine the content-type earlier and see if you can avoid every further computation, if it's not supposed to be compressed and instead of next.ServeHTTP(w,r) instead

**Comment by chenjie4255** [comment]
I meet this same issue and it took me a whole day to debug what was going wrong with my code. However, it finally turned out to be a ridiculous issue with the framework of chi, I suggest fixing this issue ASAP or at least adding some warn document about this broked middleware. It should stop people using it anymore if this bug must be fixed until the next major version.

**Comment by pkieltyka** [comment]
hey gents, sorry for the hiccups with this middleware.

This PR fixes the issues described, and doesn't require a major version update. https://github.com/go-chi/chi/pull/422

lmk feedback and I'll merge. I've tested it manually in a helper example something to the effect..

```golang
package main

import (
	"io/ioutil"
	"log"
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Compress(5, "image/png"))
	// r.Use(middleware.Compress(5))

	img, err := ioutil.ReadFile("/home/peter/Pictures/screenshot-1556733744.png")
	if err != nil {
		log.Fatal(err)
	}

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain")
		w.Write([]byte("hello world"))
	})
	r.Get("/img", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", http.DetectContentType(img))
		w.Write(img)
	})

	http.ListenAndServe(":3333", r)
}
```
