### ISSUE TITLE
add handler while server already running

### ISSUE THREAD

**Issue by vtolstov** [go-chi/chi#415]
does it possible to add handler to some new path while http server already running with this mux ?

**Comment by vtolstov** [comment]
my-use case - when some new "plugin" loaded it register own handlers

**Comment by piotrkubisa** [comment]
I don't understand a use-case, but one of the solution to problem is to set a "catch-all" middleware-like handler - take a look at https://github.com/go-chi/chi/issues/80#issuecomment-243436949 that will probably it is self-explaining about the implementation idea.
