### ISSUE TITLE
Does Route match by itself

### ISSUE THREAD

**Issue by jrozner** [go-chi/chi#419]
I'm implemented nested routes with Chi and running into some strange behavior with matching. I'm using more or less the following code:
```go
mux := chi.NewMux()

mux.Route("/things", func(r chi.Router) {
  r.Get("/", someHandler)
  r.Get("/{id}", someOtherHandler)
  r.Route("/{thing_id}", func(r chi.Router) {
    r.Get("stuff", anotherHandler)
  })
})
```
And expect the following routes to be matched.
```
/things
/things/1
/things/1/stuff
```
However, because r.Get("/{id}") is defined before the following r.Route() it doesn't match the nested routes.  Switching over to the following works.
```go
mux := chi.NewMux()

mux.Route("/things", func(r chi.Router) {
  r.Get("/", someHandler)
  r.Route("/{thing_id}", func(r chi.Router) {
    r.Get("/", someOtherHandler)
    r.Get("stuff", anotherHandler)
  })
})
```
This however does fix it, I assume because the shorter match routes are now defined after the longer ones.
```go
mux := chi.NewMux()

mux.Route("/things", func(r chi.Router) {
  r.Route("/{thing_id}", func(r chi.Router) {
    r.Get("stuff", anotherHandler)
  })
  r.Get("/", someHandler)
  r.Get("/{id}", someOtherHandler)
})
```
Is it possible to make the router recognize the longest match rather than the first match?

**Comment by pkieltyka** [comment]
hi @jrozner the router is built based on last-handler matches first. So its the correct behavior as you've done in your second example. It's something I've thought a lot about in the past and tried to design around, but there isn't any automatic way to detect this, other then allowing you to override a path by defining the intended route after your first definition. Hope that helps
