### ISSUE TITLE
RedirectSlashes should use 307-Temporary redirect

### ISSUE THREAD

**Issue by rickb777** [go-chi/chi#421]
RedirectSlashes sends a 301-Moved Permanently response code. This is deprecated in this use case and it would be better to use 307 `http.StatusTemporaryRedirect` to ensure that the redirected request behaves correctly.

More info: https://tools.ietf.org/html/rfc7231#section-6.4.2

**Comment by VojtechVitek** [comment]
307 is temporary redirect

however, RedirectSlashes is meant to issue permanent redirect, afaik

ie. `api.example.com/some/resource/` should permanently redirect to `api.example.com/some/resource`

**Comment by rickb777** [comment]
Perhaps it should use 308-Permanent-redirect, then. 308 replaces 301 because it does not allow a change of method (which is allowed for 301 and would often cause unwanted 405 errors)

https://tools.ietf.org/html/rfc7238
https://stackoverflow.com/questions/42136829/whats-difference-between-http-301-and-308-status-codes
