### ISSUE TITLE
Default URL handling changing when middleware.URLFormat is loaded

### ISSUE THREAD

**Issue by caquino** [go-chi/chi#429]
Hi,

Given the following code:
```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
)

func handler() *chi.Mux {
	router := chi.NewRouter()
	router.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})
	return router
}

func main() {
	router := chi.NewRouter()
	//router.Use(middleware.URLFormat)
	router.Route("/v1", func(r chi.Router) {
		r.Mount("/test", handler())
	})
	router.Route("/", func(r chi.Router) {
		r.Mount("/test/v1.0", handler())
	})
	http.ListenAndServe(":3000", router)
}
```

With middleware.URLFormat disabled:
- /v1/test Works fine
- /v1/test/ Works fine
- /test/v1.0 Works fine
- /test/v1.0/ Works fine

With middleware.URLFormat enabled:
- /v1/test Works fine
- /v1/test/ Works fine
- /test/v1.0 404
- /test/v1.0/ Works fine

I understand that URLFormat thinks that .0 is a file extension to define the format, but is it possible to specify a list of allowed formats or even to disable a middleware for a specific route?

Thanks for all the work on chi!

**Comment by pkieltyka** [comment]
Hey there, the best is to copy the URLFormat into your own app level middleware pkg and update the logic to however you like :)
