### ISSUE TITLE
Unresolved reference "Use"

### ISSUE THREAD

**Issue by johnknelsonintific** [go-chi/chi#430]
Hi All,

I've found myself unable to use any functions from chi's router class. I plan on using go-chi to set up CORS support in my app, but I can't even get the example to work:

```
package main

import (
	"net/http"
	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})
	http.ListenAndServe(":3000", r)
}
```

I am getting error in editor for ```router.Use``` and ```.Handler```: "Unresolved reference "Use"" and "Unresolved reference "Handler"". Why am I unable to use the router methods? I'm using GoLand IDE, and Go version 1.12.5. 

Thanks!

**Comment by pkieltyka** [comment]
hey @johnknelsonintific it appears you have some issue with your environment. Have you tried VSCode with the Go plugin? that is what I use, either way however, the above example should work for you just by running `go run yourcode.go`

this isn't a bug with chi, so going to close

**Comment by johnknelsonintific** [comment]
@pkieltyka Hmm you're right. It's funny I can't get the syntax errors/warning to disappear but you're right, when I run (even from my IDE) there is no runtime error or issue. Thanks for taking a look!
