### ISSUE TITLE
Different TTY detection

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#431]
I'm using https://github.com/cortesi/modd with a `modd.conf` like this:

```conf
**/*.go {
    daemon: go run .
}
```

and a `main.go` like this:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/logrusorgru/aurora"
)

func main() {
	fmt.Println("Hello,", aurora.Magenta("I'm Aurora, I'm colored"))

	r := chi.NewRouter()

	r.Use(middleware.Logger)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) { w.Write([]byte("welcome")) })
	http.ListenAndServe(":3000", r)
}
```

If you execute `modd` in your terminal you can see the line: `Hello, I'm Aurora` with colors and the chi logs with no colors.

I think we can fix this using a better way to detect TTY in `terminal.go`.

Using it on Windows (without unbuffer for Unix) is a big mess.

Thanks for your amazing work.

**Comment by pkieltyka** [comment]
cool, thx. I don't know what I'll be able to look at this. If its pressing for you, I suggest to fork your own middleware.Logger handler.

also, I use https://github.com/VojtechVitek/rerun for dev which works quite well
