### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by kabaluyot** [go-chi/chi#434]
Is the project still active? Because we want to consider using the chi in our microservices than using the echo framework. Last commit was on May.

**Comment by pkieltyka** [comment]
@kabaluyot yep, still very active. The project is pretty solid and doesn't need much changing

**Comment by kabaluyot** [comment]
Thanks God. A response from the creator itself is a relief. So we're good to "Go" :)

**Comment by pkieltyka** [comment]
@kabaluyot :) np

btw -- what's making you want to move off of echo?

**Comment by kabaluyot** [comment]
im coming from laravel and nodejs backend. I was looking for a framework for golang but in most forums they suggest that golang itself doesnt need a framework, instead look for a solid package. That's why I am really having a hard time if I will select Echo over Chi. It has very good documentation though.
