### ISSUE TITLE
Regex pattern matching more than one param within the same path segment

### ISSUE THREAD

**Issue by bgv** [go-chi/chi#441]
Hi, first of all thanks for the fantastic router :)

Not really an issue, just can't wrap my head around that and better ask in case I'm missing something.

So ideally I want to have such route pattern:

```
r.Get("/{name:[a-z0-9-]+}-{id:[a-z0-9]+}.html", HandlerFunc)
```

which should match:
```
/some-file-name-af768a.html
/another-file-name-df76.html
```

I know I can get just the filename and then run 2nd regex match to split it inside the HandlerFunc or just use a different separator between the 2 params. But ideally I'd prefer to have it in this form if possible.

Is this can be done at all in chi or I'm missing something?

Thanks

**Comment by pkieltyka** [comment]
thx Boris. As for your issue, perhaps you can wrangle your regexp to have it match as you intend, but at a glance I'm not sure.

However, an easily solution is to just use, `r.Get("/{name:[a-z0-9-]+}.html", HandlerFunc)` and then just parse it yourself in the handler or put a middleware in front of it

**Comment by bgv** [comment]
Thanks for the quick reply Peter,

Not sure I can wrangle it more, tried lots of different ways to get around the final dash as a separator to no avail :)

Didn't think of the possibility of middleware in front of it, excellent idea indeed, this will keep the handler code clean, thanks!
