### ISSUE TITLE
File server path name and conflict with Route()

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#442]
I'm using this code in `main.go`:

```go
package main

func main() {
	r := chi.NewRouter()

	FileServer(r, "/")

	r.Group(func(r chi.Router) {
		r.Route("/", paths.Web)
	})

	StartServer(r)
}
```

with `/paths/paths.go`:

```go
package paths

func Web(r chi.Router) {
	r.Get("/", HomeHandler())
	r.Get("/something", SomethingHandler())
	// and so on...
}
```

Now I start server and chi panics with:

`panic: chi: attempting to Mount() a handler on an existing path, '/'`

If I change `FileServer(r, "/")` in `FileServer(r, "/files")` it works.

It works also if I remove `r.Route("/", paths.Web)` replacing directly with:

```go
r.Get("/", HomeHandler())
r.Get("/something", SomethingHandler())
```

**Why does this happen?**

- `Get()` handle this different from `Route()`?

- Is there a best practice in GO for file server path name? "`/files`" or something else?

**Comment by VojtechVitek** [comment]
You're mounting multiple routes onto the "/" path.

I think you want to

```go
r.Mount("/", paths.Web) // where Web() returns a new subrouter
r.Get("/*", FileServer)
```

**Comment by frederikhors** [comment]
It now works but I now I need to use `/*/css/base.css` isntead of `/static/css/base.css`.

Something wrong? `StripPrefix` is wrong?

**Comment by VojtechVitek** [comment]
well, replace `*` with `files`?

**Comment by frederikhors** [comment]
> well, replace `*` with `files`?

I opened this for 2 reasons:

- is there a convention / best practice in Go for file server path name?
- is there a way for use `Mount()` with same "`/`" `Get()` path?

**Comment by VojtechVitek** [comment]
There's no such convention in Go. Afaik, people usually use `/public` or `/static` or `/assets` path to serve static assets on many the webpages.

Mounting two subrouters on the same path is always problematic, as they might overlap. I suggest you handle the static/known paths first, ie.
```go
r.Mount("/home", homeRouter)
r.Mount("/something", smthgRouter)
r.Get("/robots.txt", robotsTxtHandler)
```
and then let the FileServer handle the rest of the routes (anything that wasn't matched yet) via a wildcard:
```go
r.Handle("/*", FileServer)
```
