### ISSUE TITLE
is there support session middleware?

### ISSUE THREAD

**Issue by thinkgos** [go-chi/chi#443]
chi is a good web frame, i want to use chi in embeded, so is there session management with multi-backend support , such as cookie? i can not find it.

**Comment by pkieltyka** [comment]
Hi @thinkgos — for creating a cookie from code, look into http.Cookie

If you’d like jwt based auth (which you can store in a cookie for the client), see github.com/go-chi/jwtauth

**Comment by thinkgos** [comment]
Thanks for the quick reply ,
This is also a good choice！

**Comment by idc77** [comment]
jwt auth middleware is a different context.
sessions are for ssr classic websites.
