### ISSUE TITLE
Include Allow header in 405 Method Not Allowed response

### ISSUE THREAD

**Issue by alexedwards** [go-chi/chi#446]
At the moment the default [methodNotAllowedHandler](https://github.com/go-chi/chi/blob/43097498be03c1a12a01dd82d36f4465cde9bcb4/mux.go#L457) doesn't include an `Allow` header containing the resource's supported methods.

I've made a minimal runnable example here: [https://play.golang.org/p/CSUjlf8e30S](https://play.golang.org/p/CSUjlf8e30S)

According to the [HTTP RFC](https://tools.ietf.org/html/rfc7231#section-6.5.5) the `Allow` header must be included in 405 responses, so it would be good if there is a way that chi could support this.

**Comment by pkieltyka** [comment]
I'd recommend to implement this kind of behavior as a middleware where it will test for the route by accessing the router directly, and if not found, you can include the methods which are supported. As much as the RFC is cool, I don't see that this should be a "requirement"

**Comment by alexedwards** [comment]
> you can include the methods which are supported

@pkieltyka I've looked through the docs but I can't see how to get this information from the router. Could you point me in the right direction? Or do you mean that the middleware would need to contain its own secondary mapping of paths to available HTTP methods to perform the lookup?

**Comment by jeffwidman** [comment]
nudge @pkieltyka, I'm also interested in answers to ☝️.

**Comment by pkieltyka** [comment]
your middleware could function similarly to GetHead where it would do a quick-pass to search the router for the method, serve if found, otherwise compile a list of methods on the route which are available instead and handle the response

https://github.com/go-chi/chi/blob/master/middleware/get_head.go#L24-L35 for how to search the router in a middleware

**Comment by alexedwards** [comment]
> otherwise compile a list of methods on the route which are available instead

@pkieltyka It's this part that I don't get. It sounds like we would need to maintain a separate listing of all routes and their available methods. Is that what your suggesting, or do I misunderstand?

I'm happy to dig into the code to see if there's a way to achieve this without making any breaking changes 🙂 But I don't want to waste the time on that if there's no desire to fix the issue?

**Comment by pkieltyka** [comment]
just curious, but why are you so keen on this feature?

**Comment by pkieltyka** [comment]
@alexedwards it is possible, see the GetHead middleware, its all there for you if you desire. Jump into the code and play around

**Comment by RadhikaHBhatt** [comment]
I am interested in this too. Currently, Is there another method that returns `405` along with `allow` headers?
