### ISSUE TITLE
Router HandleFunc method does not match http.ServeMux

### ISSUE THREAD

**Issue by anzboi** [go-chi/chi#447]
Here are the two methods side by side

```go
// http
func (mux *ServeMux) HandleFunc(pattern string, handler func(ResponseWriter, *Request))

// chi router interface
type Router interface {
    HandleFunc(pattern string, handlerFn http.HandlerFunc)
}
```

This prevents you writing an interface that is implemented by both a `ServeMux` and a `Router`, despite the fact that `httpHandleFunc` is an alias for `func(http.ResponseWriter, *http.Request)`.

```go
type HttpMux interface {
    // Cannot accept a chi.Router
    HandleFunc(pattern string, handerFn func(http.ResponseWriter, *http.Request))
}

type HttpMux interface {
    // Cannot accept a ServeMux
    HandleFunc(pattern string, handerFn http.HandlerFunc)
}
```

The current workaround it to wrap any inline function in `http.HandlerFunc(fn)` and pass it to `Handle` instead of `HandleFunc`, but this feels like it could be simplified with a small change.

**Comment by pkieltyka** [comment]
hi @anzboi we've discussed this before in a few issues. Have a look at https://github.com/go-chi/chi/issues/423

**Comment by anzboi** [comment]
I don't think thats quite what I was thinking. Consider the following
```go
func MyHandler(http.ResponseWriter, *http.Request) {}

router.HandleFunc("path", MyHandler)
mux.HandleFunc("path", MyHandler)
```

This compiles despite the two methods having the slightly different signature. My proposed change supports the case in #423
