### ISSUE TITLE
Throttle middleware timer issue

### ISSUE THREAD

**Issue by lpy-neo** [go-chi/chi#448]
https://github.com/go-chi/chi/blob/43097498be03c1a12a01dd82d36f4465cde9bcb4/middleware/throttle.go#L70-L101

In the above function, a new timer(line 77) is created for each incoming request, and this timer isn't destroyed until it is timeout. But in normal case, this function returns quickly. 
Do I have some misunderstanding for this function or for go timer? Or this function really need to be modified to release those timers manually?

**Comment by tianchaijz** [comment]
@lpy-neo you are right. As the `time.After` doc says(should also apply to this issue):

```
 // After waits for the duration to elapse and then sends the current time
 // on the returned channel.
 // It is equivalent to NewTimer(d).C.
 // The underlying Timer is not recovered by the garbage collector
 // until the timer fires. If efficiency is a concern, use NewTimer
 // instead and call Timer.Stop if the timer is no longer needed.
```

**Comment by davidporos92** [comment]
I would happily take this issue if it's still a thing.
Just to make sure I understand the issue correctly: the problem is that the timer is not being fired unless the `timer.C` channel receives an input. In any other cases we should call `Stop` on the timer, right?

**Comment by tianchaijz** [comment]
@davidporos92 you are right. The `backlogTimeout` timer should be stopped explicitly to reduce cpu usage and gc overhead.

**Comment by pkieltyka** [comment]
thanks guys for the report, and thank you @davidporos92 for the quick PR.
