### ISSUE TITLE
Can add an example of gacefully restart (hot restart) ?

### ISSUE THREAD

**Issue by imxxiv** [go-chi/chi#450]
Because our project may increase functionality from time to time, We hope to be able to gacefully restart.
Is the following solution feasible?
[golang-ssh-bastion-graceful-restarts](https://gravitational.com/blog/golang-ssh-bastion-graceful-restarts/)
If the plan is feasible, how to use it correctly in chi?

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/blob/master/_examples/graceful/main.go is one approach and might give you some ideas. but, issues are not a place for stackoverflow type questions
