### ISSUE TITLE
Wildcard route overriding group

### ISSUE THREAD

**Issue by alshdavid** [go-chi/chi#458]
The following route table will select the `/a` when that URL is accessed

```go
r := chi.NewRouter()
r.Get("/a", handler.A)
r.Get("/*", handler.NotFound)
```

The following prefers the `/*` over the group 
```go
r := chi.NewRouter()

r.Route("/", func(r chi.Router) {
  r.Get("/a", handler.A)
})
r.Get("/*", handler.NotFound)
```

**Comment by rof20004** [comment]
I think this is meaningless, because if you create a group router with "/", why you created another route with "/*". Are you only testing? About API design this is not correctly, "/*" means that all other paths will be respond with handler.NotFound, but you have anothers handlers in "/" context.
