### ISSUE TITLE
Middleware calling chi.URLParam doesn't get params from nested routes?

### ISSUE THREAD

**Issue by thequailman** [go-chi/chi#468]
Hello, I have a bunch of nested routes that look like this:

```
r.Route("/someroute", func(r chi.Router) {
  r.Use(aMiddleware)
  r.Route("/{some_id}", func(r chi.Router) {
    ...
  }
}
```

In the above example, if `aMiddleware` calls `chi.URLParam(r, "some_id")`, it will return an empty string.  If I move `r.Use` under the route, it will work OK.  Is this expected?  This behavior is a little concerning if `aMiddleware` performs an authorization check against `some_id`

**Comment by pkieltyka** [comment]
It’s correct and expected. No need to be concerned as you can handle the request in the middleware before it hits the handler. But usually a bad idea to put auth tokens in the uri path unless they’re temporary
