### ISSUE TITLE
Best practices for unit testing

### ISSUE THREAD

**Issue by kbokarius** [go-chi/chi#478]
What's the right approach for testing handlers that require middleware and a context? We have middleware that get a URL variable (an ID), retrieves an object from the database based on that ID, and then does a: 

`ctx := context.WithValue(reader.Context(), "object", object)`
`next.ServeHTTP(writer, reader.WithContext(ctx))`

The handler then gets the object with:
`reader.Context().Value("object")`

How do we include the middleware in the unit test when using the standard httptest Recorder approach for testing handlers:

`recorder := httptest.NewRecorder()`
`handler := http.HandlerFunc(post)`
`handler.ServeHTTP(recorder, request)`

**Comment by pkieltyka** [comment]
`chi.NewRouter()` implements the http.Handler interface, so just run your test functions across your chi router with middlewares attached
