### ISSUE TITLE
implement chaining of middleware with route method

### ISSUE THREAD

**Issue by nitinjaiswal** [go-chi/chi#486]
I am looking for implementing multiple middleware on a specific GET request endpoint and will execute in order. Standard way would be to just recursively pass it, but I have found a Chain function in the documentation, but couldn't find an example for it. Can this be useful in my case to implement this? If yes, can someone share an example? If no, how can I implement it?

**Comment by pkieltyka** [comment]
hey @nikhilsaraf check the _examples folder

Specifically for how to use middleware so a request flows through the stack, use the `.Use()` method. Example: https://github.com/go-chi/chi/blob/master/_examples/hello-world/main.go#L11-L16
