### ISSUE TITLE
How about HTTP/2 support?

### ISSUE THREAD

**Issue by rsjethani** [go-chi/chi#489]

**Comment by pkieltyka** [comment]
done :) chi supports HTTP2 out of the box since it depends on net/http which provides http2 support. Just make sure you enable SSL in order to take advantage of http2

**Comment by rsjethani** [comment]
> done :) chi supports HTTP2 out of the box since it depends on net/http which provides http2 support. Just make sure you enable SSL in order to take advantage of http2

Glad to hear that thanks!!
