### ISSUE TITLE
Required path parameters requires regular expressions

### ISSUE THREAD

**Issue by leighmcculloch** [go-chi/chi#492]
Path parameters in chi are optional whenever a path has components following that parameter. For example the following route registered on a chi router can be matched with the following requests.

```go
router.Get("/accounts/{account_id}/payments", ...)
```

```
GET /accounts/GBWQZBF26VAAWPSJ6M6O5CKK4F5TNRHWDRXGERV4VIPO6QAK6LCLLXKF/payments
GET /accounts//payments
```

To make a path parameter required a regular expression can be used. Using the same example the account_id parameter can be made required with the following.

```go
router.Get("/accounts/{account_id:\\w+}/payments", ...)
```

Using regular expressions in routes seems overkill given we just want to require the field to have some value and we do no need to validate its format at this point.

**Comment by leighmcculloch** [comment]
One solution to remove the need for regular expressions in this instance could be to add syntax to path parameters for specifying that a parameter is required.

As an example and using @bartekn's idea that was posted here https://github.com/stellar/go/pull/2155#discussion_r370574999, we could prefix the parameter with `!`.

```go
router.Get("/accounts/{!account_id}/payments", ...)
```

**Comment by leighmcculloch** [comment]
I'm open to implementing this or something like this if there would be interest in accepting it.

**Comment by pkieltyka** [comment]
@leighmcculloch what you should do is check `chi.URLParam("account")` in a middleware and return an error response that the account is missing or invalid.

For example, 

```go
func ValidateURL(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		accountParam := chi.URLParam(r, "account")
		if accountParam == "" {
			w.WriteHeader(422)
			w.Write([]byte("error"))
			return
		}

		next.ServeHTTP(w, r)
	})
}
```

however, i'd recommend a helper response method that returns error codes and payload likely some kind of json response.

even better is to do something like this which handles validation and also prepares the data for the account and puts it on the request context -- see https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L88 and https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L124-L148

**Comment by pkieltyka** [comment]
FYI, you can do.. 

`r.With(SomeMiddleware).Get("/etc/{account}", h)`

for a specific route, or of course use `.Use()` or `.Group()` to a group of routes. And finally, you could get fancy and write a middleware like

`r.Use(RequireParams("account_id", "blah", "another"))`

which would be a higher-order middleware that takes `... params` and you'd loop to ensure they are included, etc..

all depends on your logic. Point is, chi is designed to be a minimal system, and middlewares give you full control of everything on the request flow

**Comment by leighmcculloch** [comment]
@pkieltyka Thanks for the tips!

We extract path parameters a little differently because we keep that extraction close to where the normal request parsing logic lives rather than disconnecting that farther high up the chain.

Regardless, I see what you're saying that we can use a middleware to catch if a parameter isn't specified and prevent a route match. Below is how I'm thinking it might play out with a generic middleware that makes a parameter required and hit the normal 404 Not Found without using regex.

What do you think? If you think this could be included in chi's middleware package I'd be happy to add it with tests, etc.

```go
func RequiredParam(param string) func(http.Handler) http.Handler {            
    return func(next http.Handler) http.Handler {                             
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            value := chi.URLParam(r, param)                                   
            if value == "" {                                                  
                notFoundHandler := http.NotFound                              
                rctx, _ := r.Context().Value(chi.RouteCtxKey).(*chi.Context)  
                if rctx != nil {                                              
                    notFoundHandler = mux.Routes.NotFoundHandler()            
                }                                                             
                notFoundHandler(w, r)                                         
                return                                                        
            }
            next.ServeHTTP(w, r)                                              
        })                                                                    
    }                                                                         
}                                                                             
```

**Comment by pkieltyka** [comment]
looks good, and could have `RequiredParams` version too which accepts `params ...string` -- sure, if you want to add `middleware/params.go` with this, lets do it.

I still think someone putting in an invalid value is the same as an empty one though, so it doesn't preclude having the handle the param value correctly

**Comment by leighmcculloch** [comment]
Thanks! I'll slot sometime in to contribute this back soon.

**Comment by rof20004** [comment]
@leighmcculloch @pkieltyka 

What about response messages?

Can be configured or will be a generic message?

Example: id is required

What message will send to client?

Thanks :)

**Comment by pkieltyka** [comment]
@rof20004 totally, that is the beauty of how simple the middlewares hook into the request-response flow. You can handle responses in middlewares too, and they can be contextual by looking at `r.Context()` or other data in `r`

**Comment by wisdommatt** [comment]
You can create a middleware that checks if some url params are not empty.

`func UrlParamsNotEmpty(params ...string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, param := range params {
				parameter := chi.URLParam(r, param)
				if parameter == "" {
					// Handle 404 error.
					return
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

r := chi.NewRouter()
r.Use(UrlParamsNotEmpty)
`

**Comment by wisdommatt** [comment]
You can create a middleware  that checks if some url params are not empty.

```go
func UrlParamsNotEmpty(params ...string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, param := range params {
				parameter := chi.URLParam(r, param)
				if parameter == "" {
					// Handle 404 error.
					return
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

r := chi.NewRouter()
r.User(UrlParamsNotEmpty)
```

**Comment by wisdommatt** [comment]
You can create a middleware  that checks if some url params are not empty.

```go
func UrlParamsNotEmpty(params ...string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, param := range params {
				parameter := chi.URLParam(r, param)
				if parameter == "" {
					// Handle 404 error.
					return
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

r := chi.NewRouter()
r.Use(UrlParamsNotEmpty("account", "user_id"))
```

**Comment by wisdommatt** [comment]
You can create a middleware  that checks if some url params are not empty.

```go
func UrlParamsNotEmpty(params ...string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, param := range params {
				parameter := chi.URLParam(r, param)
				if parameter == "" {
					// Handle 404 error.
					return
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

r := chi.NewRouter()
r.Use(UrlParamsNotEmpty("account", "user_id"))
// OR
r.With(UrlParamsNotEmpty("account", "user_id")).Get("/etc/{account}", h)

```

**Comment by wisdommatt** [comment]
You can create a middleware  that checks if some url params are not empty.

```go
func UrlParamsNotEmpty(params ...string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, param := range params {
				parameter := chi.URLParam(r, param)
				if parameter == "" {
					// Handle 404 error.
					return
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

r := chi.NewRouter()
r.Use(UrlParamsNotEmpty("account", "user_id"))
// OR
r.With(UrlParamsNotEmpty("account")).Get("/etc/{account}", h)

```

**Comment by Goldziher** [comment]
lol, this is bad design
