### ISSUE TITLE
Proper way of creating a subrouter

### ISSUE THREAD

**Issue by ribice** [go-chi/chi#494]
I've used `gorilla/mux` and `echo` before and they support creating a subrouter from router:

```
router:= mux.NewRouter()
subRouter := router.Subrouter()
productSubrouter := router.PathPrefix("/products").Subrouter()
```

The subrouter inherits all the middleware from its parent router. Any middleware defined on subrouter doesn't affect the parent router, which is the primary functionality I'm aiming for.

I tried using `Group`:

```
router := chi.NewMux()
subRouter := routerGroup(nil)
authMiddleware := auth.Middleware()
subRouter2 := router.With(authMiddleware)
```

The problem is, subRouter and subRouter2 don't inherit the middleware from router. What's the best way to achieve this functionality (creating a subrouter while inheriting middleware from parent router) with Chi?

**Comment by Mentioum** [comment]
Hi @ribice 

I believe what you are looking for is `Mount`

You can see an example [here](https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L100)

**Comment by ribice** [comment]
I don't see the middleware being copied anywhere. In fact, the `Route` method even has a comment:

```
// Route creates a new Mux with a fresh middleware stack and mounts it
// along the `pattern` as a subrouter. Effectively, this is a short-hand
// call to Mount.
```

**Comment by Mentioum** [comment]
I'm confused why you'd want to 'copy' the middleware to the subrouter since it runs through the parents middleware before going the subrouter.

Is there a reason you want the middleware to run multiple times?

**Comment by ribice** [comment]
I don't see it running through parent's middleware before reaching the subrouter. I have CORS defined on primary router, but there is no CORS on subrouters created with `Group` or `With`.

**Comment by Mentioum** [comment]
I'm mounting my subrouters as sub-resources like in the todos resource example and it seems to work for me.

Not sure why in your working for you.  Are you creating your subrouters inside of the parent router?

**Comment by Mentioum** [comment]
On GitHub mobile and don't see how to edit comments, here's the URL for the todos-resource example I referenced above:

https://github.com/go-chi/chi/tree/master/_examples/todos-resource

**Comment by ribice** [comment]
`r` has CORS properly set.

```
subRouter := chi.NewMux()
subRouter.Use(aMiddleware)
subRouter.Get("/someRoute", someRoute)
r.Mount("/", authR)
```

Invoking `/someRoute` returns CORS error. All other routes registered directly on `r` work properly.

**Comment by Mentioum** [comment]
I definitely don't get that problem.  I can't post an example of what I've done right now as I'm on mobile but will do so later if you'd find that useful?

**Comment by ribice** [comment]
Please do.

**Comment by pkieltyka** [comment]
you should use https://github.com/go-chi/cors middleware

see https://github.com/go-chi/cors/blob/master/_example/main.go

**Comment by pkieltyka** [comment]
it looks something like this..

```
	r := chi.NewRouter()

	// Basic CORS
	// for more ideas, see: https://developer.github.com/v3/#cross-origin-resource-sharing
	cors := cors.New(cors.Options{
		AllowOriginFunc:  AllowOriginFunc,
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: true,
		MaxAge:           300, // Maximum value not ignored by any of major browsers
	})
	r.Use(cors.Handler)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})

	r.Route("/subrouter", func(r chi.Router) {
		r.Get("/", subHandlerIndex)
	})
	// note: look through other examples, you can also use r.Mount("/subrouter", subrouter)
	// where subrouter := chi.NewRouter()

	http.ListenAndServe(":3000", r)
```

**Comment by Mentioum** [comment]
@pkieltyka thanks and yup, my code looks pretty much like that except I'm using dependency injection with my mounted subrouters.

**Comment by fspaniol** [comment]
Hi @pkieltyka, I am running into sort of a similar issue here. I want to have some sort of common middlewares for all of my routes (such as prometheus, loggers, etc...). However, If I look at the function definitions in the interface, it says:

```golang
	// Group adds a new inline-Router along the current routing
	// path, with a fresh middleware stack for the inline-Router.
	Group(fn func(r Router)) Router

	// Route mounts a sub-Router along a `pattern`` string.
	Route(pattern string, fn func(r Router)) Router

	// Mount attaches another http.Handler along ./pattern/*
	Mount(pattern string, h http.Handler)
```

However, if checking the actual `chi.Mux` implementation, it says that all of them generate a fresh middleware stack:

```golang
// Group creates a new inline-Mux with a fresh middleware stack. It's useful
// for a group of handlers along the same routing path that use an additional
// set of middlewares. See _examples/.
func (mx *Mux) Group(fn func(r Router)) Router {

// Route creates a new Mux with a fresh middleware stack and mounts it
// along the `pattern` as a subrouter. Effectively, this is a short-hand
// call to Mount. See _examples/.
func (mx *Mux) Route(pattern string, fn func(r Router)) Router {

// Mount attaches another http.Handler or chi Router as a subrouter along a routing
// path. It's very useful to split up a large API as many independent routers and
// compose them as a single service using Mount. See _examples/.
//
// Note that Mount() simply sets a wildcard along the `pattern` that will continue
// routing at the `handler`, which in most cases is another chi.Router. As a result,
// if you define two Mount() routes on the exact same pattern the mount will panic.
func (mx *Mux) Mount(pattern string, handler http.Handler) {
```

I know that I could specify each route with all the middlewares that I want, but I'd prefer to optimize that somehow, any ideas?

**Comment by fspaniol** [comment]
One way that has occurred to me is:
```golang
	r.Group(func(r2 chi.Router) {
		r2.Use(r.Middlewares()...)
		r2.Use(myR2Middleware)
		r2.Handle("/path*", PathHandler)
	})
```

Is this recommended?
