### ISSUE TITLE
Breaking API change in 4.0.4 release (middleware.DefaultCompress)

### ISSUE THREAD

**Issue by edmorley** [go-chi/chi#497]
Hi!

In v4.0.4 `middleware.defaultCompressor` was removed:
https://github.com/go-chi/chi/commit/baf4ef5b139e284b297573d89daf587457153aa3

Whilst there was a code comment in that file indicating that the method was deprecated:
* the comment was only [added](https://github.com/go-chi/chi/commit/52e06e680d664b612e3e968bbe57257bc987313c) in v4.0.3 (and not say in v3.x)
* removing a deprecated API is still a breaking change

Could `DefaultCompress` be re-added and removed in v5 instead?

Many thanks :-)

**Comment by pkieltyka** [comment]
please upgrade your code. the change has already been made but I'll be more careful in the future. thanks for the report
