### ISSUE TITLE
redirect http to https?

### ISSUE THREAD

**Issue by Gys** [go-chi/chi#498]
Hi

I use Chi for an app that is deployed on Heroku. The app has https enabled (a Heroku feature). I noticed however that http is still enabled and accessable as well. For safety I prefer the http to be disabled or otherwise just redirected to https.

I also found this publication by Heroku: https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

It basically says 

> Redirects need to be performed at the application level as the Heroku router does not provide this functionality

The page also provides some code examples, but not for Go. Seems like a middleware thing to me. I searched for something like that (for Chi or not) but could not find anything. So I wonder, does it exist?

**Comment by pkieltyka** [comment]
Sounds like time to write your first middleware :)

**Comment by pkieltyka** [comment]
@Gys or you could use https://github.com/unrolled/secure if you're not up for writing your own middleware handler

**Comment by Gys** [comment]
That package really looks very interesting. Also for other projects. Thank you!!!
