### ISSUE TITLE
Lowercase-urlencoded url template variables not decoded

### ISSUE THREAD

**Issue by tograh** [go-chi/chi#499]
If I call an endpoint with a url template, and my variable is url-encoded in lowercase, the variable is not unencoded when accessed with chi.URLParam (go 1.14, chi 4.0.4).  Attaching example.
[chitest_go.txt](https://github.com/go-chi/chi/files/4411664/chitest_go.txt)

**Comment by tograh** [comment]
I wonder whether either net/url’s setPath() needs to do a strings.EqualFold() comparison before it sets RawPath, or chi’s mux routeHTTP() needs to somehow adjust its deference to using the RawPath when it’s set.

**Comment by pkieltyka** [comment]
I don't understand your problem sorry. Perhaps you can try to rephrase and include example here in github.

**Comment by tograh** [comment]
I attached an example to my first post.  (If you saw it, was it not helpful?)  I'll paste it below in case the attachment didn't work:

package main

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi"
)

// Handler from https://github.com/go-chi/chi/tree/master/_examples/custom-handler
type Handler func(w http.ResponseWriter, r *http.Request) error

func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if err := h(w, r); err != nil {
		// handle returned error here.
		w.WriteHeader(503)
		_, _ = w.Write([]byte("bad"))
	}
}

func main() {

	const domain = "localhost:8084"
	const mbcsName = "지도폴더"

	handler := func(w http.ResponseWriter, r *http.Request) error {
		fmt.Printf("Received to url %s with parameter %s.\n", r.URL.String(), chi.URLParam(r, "name"))
		name := chi.URLParam(r, "name")
		//assert.True(t, name == "aardvark" || name == mbcsName, fmt.Sprintf("aardvark or %s matches %s", mbcsName, name))
		fmt.Printf("aardvark or %s matches %s\n", mbcsName, name)
		return nil
	}

	r := chi.NewRouter()

	r.Method("GET", "/test/{name}", Handler(handler))

	srv := &http.Server{Addr: domain, Handler: r}
	go func() { _ = srv.ListenAndServe() }()

	tests := []struct {
		url string
	}{
		{fmt.Sprintf("http://%s/test/%s", domain, "aardvark")},
		{fmt.Sprintf("http://%s/test/%s", domain, mbcsName)},
		{fmt.Sprintf("http://%s/test/%s", domain, strings.ToUpper(url.PathEscape(mbcsName)))},
		{fmt.Sprintf("http://%s/test/%s", domain, strings.ToLower(url.PathEscape(mbcsName)))},
	}

	for _, r := range tests {
		http.Get(r.url)
	}

	_ = srv.Shutdown(context.Background())

}

/*

[ Lowercase-urlencoded url template variables not decoded ]

Output (last two lines are incorrect/unexpected):

Received to url /test/aardvark with parameter aardvark.
aardvark or 지도폴더 matches aardvark
Received to url /test/%EC%A7%80%EB%8F%84%ED%8F%B4%EB%8D%94 with parameter 지도폴더.
aardvark or 지도폴더 matches 지도폴더
Received to url /test/%EC%A7%80%EB%8F%84%ED%8F%B4%EB%8D%94 with parameter 지도폴더.
aardvark or 지도폴더 matches 지도폴더
Received to url /test/%ec%a7%80%eb%8f%84%ed%8f%b4%eb%8d%94 with parameter %ec%a7%80%eb%8f%84%ed%8f%b4%eb%8d%94.
aardvark or 지도폴더 matches %ec%a7%80%eb%8f%84%ed%8f%b4%eb%8d%94

For go.mod:

module chitest

go 1.14

require (
	github.com/go-chi/chi v4.0.4+incompatible
	github.com/stretchr/testify v1.5.1
)

*/

**Comment by pkieltyka** [comment]
chi routes based on Go's request.URL.RawPath

https://github.com/go-chi/chi/blob/master/mux.go#L413

perhaps someone else can help you but I don't have the time to debug your particular situation

**Comment by tograh** [comment]
It does when the request's RawPath is set.  But it uses the request's Path when its RawPath is unset.  Of the 4 urls attempted in the example, the chi's routeHTTP() uses the request's Path for the first 3.  Those 3 work (that is, their path parameters get unencoded).   In the last (the lowercased one), chi's routeHTTP() uses the request's RawPath (and the path parameter remains encoded).

I'm confident that this isn't an issue unique to my situation, although I confess that I don't know what (or where) the solution should be.

**Comment by tograh** [comment]
Others are complaining about golang's net/url setPath() case-sensitive behavior (https://github.com/golang/go/issues/33596).  I'll look there.  If they don't fix it, we'll have to compensate in our handlers.
