### ISSUE TITLE
Breaking API change in 4.1.0 release (middleware.LogEntry interface)

### ISSUE THREAD

**Issue by chrisvaughn** [go-chi/chi#500]
The middleware.LogEntry interface changed between the 4.0.4 and 4.1.0 releases causing custom logger middleware to break. This was unexpected on a minor update.  The logger example needs to be updated as well.

**Comment by pkieltyka** [comment]
Yea that’s why it’s a minor update and not tiny. The rule I’ll stick with for chi is tiny will be seemless update, and minor when there is a simple api change. And of course major for anything significant which is very rare in chi as architecturally the project is the same for over 3 years. Good catch to update the logger example, that’ll be a simple fix

**Comment by chrisvaughn** [comment]
Thanks for your work on this project, it's been great to use and has helped us tremendously.

Thanks for the explanation of versioning that'll help in the future. I think there would be a better understanding across your community of users if you were to use SemVer definitions of [Major](https://semver.org/#spec-item-8) and [Minor]( https://semver.org/#spec-item-7). Thanks again for your work on this.

**Comment by pkieltyka** [comment]
np. https://github.com/go-chi/chi/commit/a0d61e3faf52e5d93a91a8921fb2a27c64bfefb4 is the logging fix

**Comment by pkieltyka** [comment]
however, the 4.1 LogEntry api change would only affect those who have built custom loggers on top of chi, using anything with the std package wouldnt cause any breaking changes. Either way, a minor fix/update.
