### ISSUE TITLE
Incorrect middleware calling behavior inside Group

### ISSUE THREAD

**Issue by dobegor** [go-chi/chi#502]
Given a set of a handler and middleware:
```go
func SomeMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("Middleware called")
		w.Header().Add("Some-Middleware", "1")
		next.ServeHTTP(w, r)
	})
}
func SomeHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Some-Handler", "1")
}
```

We observe different behavior:
1. Middleware gets called no matter what
```go
func main() {
	r := chi.NewRouter()
	r.Use(SomeMiddleware)

	r.Group(func(r chi.Router) {
		r.Get("/url1", SomeHandler)
	})
	http.ListenAndServe(":12345", r)
}
```
```
~ curl -i http://localhost:12345/url1
HTTP/1.1 200 OK
Some-Handler: 1
Some-Middleware: 1
Date: Fri, 10 Apr 2020 13:46:02 GMT
Content-Length: 0

~ curl -i http://localhost:12345/url12
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Some-Middleware: 1
X-Content-Type-Options: nosniff
Date: Fri, 10 Apr 2020 13:46:03 GMT
Content-Length: 19

404 page not found
```

2. Middleware does not get called if route does not match (missing header in this example)
```go
func main() {
	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Use(SomeMiddleware)
		r.Get("/url1", SomeHandler)
	})
	http.ListenAndServe(":12345", r)
}
```
```
~ curl -i http://localhost:12345/url1
HTTP/1.1 200 OK
Some-Handler: 1
Some-Middleware: 1
Date: Fri, 10 Apr 2020 13:47:10 GMT
Content-Length: 0

~ curl -i http://localhost:12345/url12
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 10 Apr 2020 13:47:11 GMT
Content-Length: 19

404 page not found
```

**Comment by pkieltyka** [comment]
hi there, I know this can be a bit confusing but it isn't a bug, its just how `.Group` works. See https://github.com/go-chi/chi/blob/master/chi.go#L77-L79 

the idea is that Group() is a short hand for .With() which provide an inline middleware for a handler. It means only matching handlers will be triggered with those middlewares. 

Try `.Use()` or `.Route()` + `.Use()`

**Comment by dobegor** [comment]
Yeah I realised that just a few moments after I filed an issue. Though I left it open just to have a little discussion around the question: imagine having a large set of endpoints, some API. And I need to expose only a few of them to a browser (using CORS middleware). It appears that the only correct way to do that in chi now is to use `AllowOriginFunc` in CORS middleware options and manually list all the endpoints that should be accessible via browser. Is there any other sane way to achive this?

**Comment by pkieltyka** [comment]
the `AllowOriginFunc` in the cors middleware doesn't have much to do with this.

You can still use .Group() with the cors middleware just fine, the only change in how Group() works i the middleware will only be called for an endpoint that is found. For anything not found, it will return a 404 and will not trigger the middleware. In the cors situation, this is what you'd want.

**Comment by dobegor** [comment]
The problem with CORS middleware inside group is that middleware won't get called - because no endpoint inside group was matched, because I did not define any OPTIONS endpoints. The only workaround that works is to define some kind of an endpoint inside group like this: `r.Options("*", nil)` only to make chi call the middleware inside group.

**Comment by dobegor** [comment]
I.e. I a have a bunch of POST and GET endpoints inside my group and CORS middleware won't ever be invoked - because no route inside the group matches the OPTIONS request that browser makes.

**Comment by pkieltyka** [comment]
yea good point about the Options method issue here in this scenario. Perhaps `r.Options("*", corsStub)` is a reasonable solution, but not great. In most cases you should be able to use r.Route() though, it just depends how your routes are organized, sometimes a .Group() is all that will work. 

I think best solution for your case is to do as you suggested and include a Options method stub. I wouldn't route to "nil", but certainly a stub handler that returns a 400
