### ISSUE TITLE
Match patterns 

### ISSUE THREAD

**Issue by nicola-spb** [go-chi/chi#507]
Hello.

I have code where I wanna check patterns (exists pattern for path or not and ignore some patterns for checking).
I try use:
1) mux.Match - but it return only bool value. 
2) mx.tree.FindRoute - use in params private map methodMap

How can I do it with current API? May be Match should return patterns?
Thanks.

**Comment by pkieltyka** [comment]
hi @nicola-spb the supported APIs are mux.Match as you mentioned, and there are walk methods on the tree, you can get a glimpse of that here https://github.com/go-chi/chi/blob/master/_examples/router-walk/main.go -- hope that helps
