### ISSUE TITLE
Public API change introduced without bumping MAJOR

### ISSUE THREAD

**Issue by trevrosen** [go-chi/chi#508]
Hi,
Unless I'm mistaken, it appears that [this commit](https://github.com/go-chi/chi/commit/1a43680df08fbdeae828c03891ee08282ec8f2a4) extends an exported interface (and therefore breaks downstream integrators),  but you're not bumping the major version of the release when doing this.

Is this project attempting to follow semantic versioning as the version numbers would seem to indicate? If you're *not* following semantic versioning, can you provide a statement of guidance to the community on how to leverage your version tags so as to ensure that we don't experience breaking changes in our own code when you make backwards-incompatible alterations like this one? Thanks!

**Comment by pkieltyka** [comment]
this project does not follow semver. See

https://github.com/go-chi/chi/issues/500

**Comment by trevrosen** [comment]
Ok but you're following *some* de facto version scheme that *resembles* semver, so my original request still seems relevant: can you provide some kind of documentation of what causes you to bump these numbers or not in any given release? 😄

**Comment by dandee** [comment]
@trevrosen I agree with you. And it's not the first time someone rises this issue. I find @pkieltyka approach a bit arrogant and I think that doesn't bode well for the future of the project. I'm planning to switch over to another package with my work's projects.

**Comment by pkieltyka** [comment]
@dandee sorry you're not satisfied with my support for the project, best of luck to you on other projects.

I do what I can with limited time to answer support questions I've already answered and direct people to other links quite promptly. Again, I don't care if you don't approve -- you get what you pay for
