### ISSUE TITLE
ServerBaseContext suppresses original request context cancellation signal

### ISSUE THREAD

**Issue by e-zhydzetski** [go-chi/chi#509]
`ServerBaseContext` is a very convenient wrapper, but it inherits only values from original request context.  
So, original request context cancellation logic will be suppressed, and we will lost possibility to capture cancellation signal from network connection.  
So, we can't efficiently handle client-side connection interruptions, or any other network middleware problems.

Is it a bug or expected behaviour of `ServerBaseContext` ?

**Comment by e-zhydzetski** [comment]
Maybe, this wrapper should be marked as deprecated in favor of standard go1.13+ `net/http.Server.BaseContext`, or, at least, provided with relevant comment in godoc.

**Comment by pkieltyka** [comment]
yes, good point. This needs some review in light of the `net/http.Server.BaseContext` as well the ConnContext (https://golang.org/pkg/net/http/#Server.ConnContext) method.

feel free to submit a proposed PR or drop some sample code if you come to a nice pattern

**Comment by e-zhydzetski** [comment]
After update to go 1.13+ this simple fix works like a charm: 
```diff
                server := &http.Server{
                        Addr:    addr,
-                       Handler: chi.ServerBaseContext(ctx, handler),
+                       Handler: handler,
+               }
+               server.BaseContext = func(_ net.Listener) context.Context {
+                       return ctx
                }
```

As for `net/http.Server.ConnContext` - it may be usefull for per-request context update: tracing, contextual logging or configuration injection..., but handler-level middleware is more convenient and flexible, IMHO.

So, the main question about `ServerBaseContext` is support of go1.12-. 
If it is needed - correct implementation of contexts merge with minimal performance impact will be not a trivial job: signals fan-in -> additional goroutine, maybe custom `context.Context` implementation...

**Comment by e-zhydzetski** [comment]
May be usefull: https://medium.com/@dlagoza/playing-with-multiple-contexts-in-go-9f72cbcff56e

**Comment by pkieltyka** [comment]
@e-zhydzetski just checking if you have any final recommendations for this ticket? I'd prefer to not worry about go 1.12-, as users can use an older version of chi if they require, and Go's backwards-compat promise then developers will just upgrade to the latest and greatest Go, thus, Chi only cares about the last 2 versions of Go for "official" support. Can we adapt `ServerBaseContext` so it avoids the problem you experienced? Or rather, maybe we should just remove it

**Comment by e-zhydzetski** [comment]
I would recommend to remove this ambiguous feature in favour of standard library.

**Comment by pkieltyka** [comment]
done
