### ISSUE TITLE
Logger for Routes

### ISSUE THREAD

**Issue by Janther** [go-chi/chi#510]
Is there a way to have the logger not only the `time`, `request`, and `duration` but also the `Route` that was matched or the `function` that was executed?

**Comment by pkieltyka** [comment]
hey @Janther check out the logging example here https://github.com/go-chi/chi/blob/master/_examples/logging/main.go#L46

it uses the standard logger and sets additional fields to a structured logger. You could write a middleware that sets the RoutePattern to the logger. Aside from that, you could fork the logger code.

Another example / pkg that I use for many of my projects: https://github.com/goware/httplog
