### ISSUE TITLE
Why does fileserver need to check public containing "{}*" in _examples/fileserver?

### ISSUE THREAD

**Issue by TonyPythoneer** [go-chi/chi#513]
Excuse me. I have read the examples but I haven't understood.
Could you help me with what it means?

I have a question about these lines from https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go#L54-L56:

	if strings.ContainsAny(public, "{}*") {
		panic("FileServer does not permit URL parameters.")
	}

Why does it need to check the "{}*"? Is it for security? I want to know the detail. Thanks.

**Comment by mfridman** [comment]
@TonyPythoneer see answer https://github.com/go-chi/chi/issues/403#issuecomment-633561720
