### ISSUE TITLE
CSRF Protection middleware.

### ISSUE THREAD

**Issue by Faares** [go-chi/chi#522]
Hi, I just wondering is there any CSRF Protection middleware for **go-chi**?
I searched in the middleware directory, but I didn't find anything related to it.

if not, does [this middleware](https://github.com/gorilla/csrf) compatible with go-chi or not?
I assume yes, but I want to be more confident.

**Comment by pkieltyka** [comment]
yes definitely gorilla/csrf will work with chi :) good choice
