### ISSUE TITLE
What is the recommended way to pass values between middlewares?

### ISSUE THREAD

**Issue by maxdelia** [go-chi/chi#524]
Hi!

I would like to process some data inside a middleware, and then pass the resulted value to the next one.
What is the best way to achieve this in a secure way, without have to change the request headers, cookies or body?
I tried adding a key to the context, but I'm not able to see the usual `context.WithValue`.

Thanks in advance!

**Comment by pkieltyka** [comment]
hi @maxdelia -- have you gone through the _examples folder?

have a look at https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L88 https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L127-L148 and finally, https://github.com/go-chi/chi/blob/df86a5eddf269fc0d4de61404f0a53661dcad9e6/_examples/rest/main.go#L180

in the above code, ArticleCtx is a middleware which will set an *Article object on the request context, and then return the request with the updated context here: https://github.com/go-chi/chi/blob/df86a5eddf269fc0d4de61404f0a53661dcad9e6/_examples/rest/main.go#L145-L146

```go
ctx := context.WithValue(r.Context(), "article", article)
next.ServeHTTP(w, r.WithContext(ctx)
```

please lmk if that helps or if you're still figuring it out

**Comment by pkieltyka** [comment]
@Keith-Ball that's correct, it only sets values from that point and onward. You could set an object on the context at a higher-level though, set it on the request context and access/set values on that object. In most cases though, just getting the order to what you want and keeping middlewares pretty isolated by responsibility keeps things working well

**Comment by Keith-Ball** [comment]
The specific situation I had was a Sentry middleware which was looking for the user in the context. -- Sentry middleware existed early in the chain and `ValidatePopulateUser` existed later.

The issue I was having was a dereferencing problem. -- Honestly I don't know why:
`r = r.WithContext(...)` wasn't updating the reference in the previous middleware, but it wasn't.

Instead I had to do:
`*r = *r.WithContext(...)`

While I agree that isolated middleware is best, there are certain times (Like error/stats logging) where you need references to a context item that was populated later in the chain.
