### ISSUE TITLE
Using two handlers for a GraphQL project; handle query with the second one if the first one is not capable of

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#526]
I'm trying to use both [SuperGraph as-a-library](https://github.com/dosco/super-graph/) and [GqlGen](https://github.com/99designs/gqlgen).

So I have two handlers:

1. the first one is **SuperGraph**; this checks that it can carry out the operation

1. the second one is **GqlGen**; this checks that it can carry out the operation if the first one can't

The code I'm using is this:

```go
type reqBody struct {
	Query string `json:"query"`
}

func Handler(sg *core.SuperGraph, next http.Handler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		bodyBytes, _ := ioutil.ReadAll(r.Body)
		r.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))

		var rBody reqBody
		err = json.NewDecoder(bytes.NewBuffer(bodyBytes)).Decode(&rBody)

		ctx := context.WithValue(r.Context(), core.UserIDKey, "user_id")
		res, err := sg.GraphQL(ctx, rBody.Query, nil)
		if err == nil {
			render.JSON(w, r, res) // go-chi "render" pkg
		} else {
			next.ServeHTTP(w, r)
		}
	}
}

func main() {
	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Post("/graphql", Handler(supergraph, gqlgen))
	})
}
```

### QUESTIONS

1. Can I avoid these lines at all?

    ```go
      bodyBytes, _ := ioutil.ReadAll(r.Body)
      r.Body = ioutil.NopCloser(bytes.NewReader(bodyBytes))
    ```

1. Is there a better way to handle all this with **go-chi**?

**Comment by pkieltyka** [comment]
looks correct to me :+1:

**Comment by frederikhors** [comment]
@pkieltyka is there a way to avoid these lines manually written by me?

```go
  bodyBytes, _ := ioutil.ReadAll(r.Body)
  r.Body = ioutil.NopCloser(bytes.NewReader(bodyBytes))
```

**Comment by pkieltyka** [comment]
sorry, but I don't have bandwidth to offer general Go support but please try Gopher Slack channel, its awesome.
