### ISSUE TITLE
Should I use a LimitReader?

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#527]
Is there already a limit for a request's body?

Is there a middleware for this?

Should I use a `LimitedReader` for a `router.Post()` handler?

**Comment by pkieltyka** [comment]
You could, but it's not required. Please use other channels for general Go questions, I recommend Gophers slack at: https://invite.slack.golangbridge.org/

Please limit issues to bug reports or specific documentation questions of chi. This is an open source effort and I'm unable to provide general Go support.
