### ISSUE TITLE
URLFormat chops at the First dot rather than the last dot.

### ISSUE THREAD

**Issue by derekbassett** [go-chi/chi#530]
Currently URLFormat chops everything after the first dot which means if you have a path like `/articles/i.am.a.really.really.really.cruel.person.json` URLFormat will match on path `i` rather then on path `/articles/i.am.a.really.really.really.cruel.person` 

I will update the issue with a simple pull request to fix this issue.

**Comment by pkieltyka** [comment]
thx for the report + fix
