### ISSUE TITLE
Is chi still being maintained?

### ISSUE THREAD

**Issue by dustinmoris** [go-chi/chi#535]
Hi, I'm new to Go and came across this library as one of the main web frameworks used by the Go community. I really like it, but I'm not sure if this project is still being maintained by looking at some of the issues and PRs which have been stale for many months now.

What's the current status with this and is there any roadmap or a need for some extra helping hands if the current author doesn't have the time and/or desire to maintain this project (not suggesting this is the case, but very much appreciate that this can happen and I'm just checking in what the status is and possibly if I could help)?

**Comment by pkieltyka** [comment]
chi is rock solid and has been maintained for years. it still is very much so maintained :)

the issues and PRs outstanding are not pressing and some aren't even valid/correct, but still need review

**Comment by dustinmoris** [comment]
Thank you, glad to hear :)
