### ISSUE TITLE
RealIP allows any value, including non-IP addresses and private IP addresses

### ISSUE THREAD

**Issue by arp242** [go-chi/chi#536]
The `RealIP` accept any value. Since clients can set this themselves this is perhaps not a good idea; for example:

    X-Forwarded-For: 192.168.1.1
    X-Forwarded-For: -- `some injected malicious value?`

It's perhaps better to 1) lock this down to just IP addresses, and 2) not allow non-public IP addresses?

This rolled out of a security evaluation of my product. For what it's worth, here's the code I'm using now: https://github.com/zgoat/zhttp/blob/master/realip.go#L18

**Comment by cilindrox** [comment]
from [the docs](https://pkg.go.dev/github.com/go-chi/chi/middleware#RealIP): 

> You should only use this middleware if you can trust the headers passed to you (in particular, the two headers this middleware uses), for example because you have placed a reverse proxy like HAProxy or nginx in front of Goji. If your reverse proxies are configured to pass along arbitrary header values from the client, or if you use this middleware without a reverse proxy, malicious clients will be able to make you very sad (or, depending on how you're using RemoteAddr, vulnerable to an attack of some sort).

Seems like this is expecting a reverse proxy sitting in front of the app, and that's where the actual filtering should occur

**Comment by arp242** [comment]
You may not be running a proxy but clients can still set this header.

**Comment by cilindrox** [comment]
Precisely, in those scenarios (no proxy, untrusted network) then I’d argue you shouldn’t be trusting arbitrary user input, which is what the docs mention

**Comment by arp242** [comment]
It's worth remembering that everything sent over the network is "arbitrary user input"; you can fake the RemoteAddr value too if you want, it's just a little bit more effort. There is never any guarantee that you're getting the "real" IP address.

It's not a problem if I fake this to 1.2.3.4, since that's just a random IP address. But 127.0.0.1 or 10.0.0.5 is a local address or address in the local network and may, in some situations, lead to some sort of abuse, so it's probably best to filter those out while we're processing these headers anyway. Come to think of it, I should probably change my implementation to account for a faked RemoteAddr.

At any rate, the practical problem is that I want to ship an app people can run with or without a proxy, depending on what works best for them, which seems a common use case.

**Comment by pkieltyka** [comment]
this isn't really a bug with chi as it relies on the headers from the upstream -- we can only assume each upstream is forwarding the correct ip address of its sender. The other issue is that upstream's sometimes have this in the opposite order, so it's a bit inconsistent. If anyone can point me on some definitive text on the best way to get the real IP from a proxied request, as in which ordering is the most correct, we'll stick to that.

**Comment by arp242** [comment]
Well, like I said; "upstream" can just be the client itself. If you're shipping a Go webserver (i.e. some open source project) then people can decide for themselves if they want to run a proxy or not, and many actually don't.

**Comment by lrstanley** [comment]
Also FWIW, the docs here:

https://github.com/go-chi/chi/blob/2283e4951adbd82c8f6427117bd6b2a1c315e725/middleware/realip.go#L14-L16

Say:
> parsing either the X-Forwarded-For header or the X-Real-IP header (in that order).

However it looks like the logic is the reverse:

https://github.com/go-chi/chi/blob/2283e4951adbd82c8f6427117bd6b2a1c315e725/middleware/realip.go#L43-L45

**Comment by JohnMaguire** [comment]
> Also FWIW, the docs here:
> 
> https://github.com/go-chi/chi/blob/2283e4951adbd82c8f6427117bd6b2a1c315e725/middleware/realip.go#L14-L16
> 
> Say:
> 
> > parsing either the X-Forwarded-For header or the X-Real-IP header (in that order).
> 
> However it looks like the logic is the reverse:
> 
> https://github.com/go-chi/chi/blob/2283e4951adbd82c8f6427117bd6b2a1c315e725/middleware/realip.go#L43-L45

I was just noticing this as well - this is a bit of a problem since AWS tends to set X-Forwarded-For. The docs may lead one to believe that that header will be set, when in actuality an X-Real-IP may override it.
