### ISSUE TITLE
ANSI colour escape codes not working on windows (middleware.Logger)

### ISSUE THREAD

**Issue by jawadcode** [go-chi/chi#538]
Powershell by **default** does not support ANSI colour escape codes so, it would be much appreciated if the colour codes were turned off if GOOS == windows or if there was some sort of configuration option to disable colour, I believe this would also help when trying to log to a text file.

**Comment by pkieltyka** [comment]
hey @jawadcode I think turning off colors when GOOS == windows can work as a default for sure.

Alternatively, you can use the following..

`r.Use(middleware.RequestLogger(&middleware.DefaultLogFormatter{Logger: log.New(os.Stdout, "", log.LstdFlags), NoColor: true}))`

or..

`middleware.DefaultLogger = middleware.RequestLogger(&middleware.DefaultLogFormatter{Logger: log.New(os.Stdout, "", log.LstdFlags), NoColor: true}))`

**Comment by jawadcode** [comment]
Quick thing, the last `)` is unnecessary

**Comment by pkieltyka** [comment]
Fixed in https://github.com/go-chi/chi/commit/3479a89b95fc9b97f931da6f9f8bbc8c2c636817
