### ISSUE TITLE
Reliance on io.ReaderFrom from unexposed `response` in net/http

### ISSUE THREAD

**Issue by titpetric** [go-chi/chi#543]
Hello,

I'm trying to use elastic apm agent apmhttp which wraps http.ResponseWriter for it's own purposes. The package implements a http.ResponseWriter, and http.Hijack, but it doesn't implement io.ReaderFrom. While this is an inconvenience for apmhttp, unfortunately chi relies on io.ReaderFrom presence, and hijacking doesn't work without it as a middleware.flushWriter is created.

1. Can we have a reader that supports hijacking but doesn't have a io.ReaderFrom?
2. Is it sensible to assert io.ReaderFrom compatibility, as this isn't a http package interface, over an unexported struct?

- apmhttp upstream issue: https://github.com/elastic/apm-agent-go/issues/826
- go-chi/chi implementation issue: https://github.com/go-chi/chi/blob/12ebe3332f86ee21554ecfbef430bdf376be7f5f/middleware/wrap_writer.go#L26-L30

I'm currently using this as a work around to get the underlying ResponseWriter:

~~~go
// pre-websocket check
if mw, ok := w.(middleware.WrapResponseWriter); ok {
        w = mw.Unwrap();
}
~~~

**Comment by pkieltyka** [comment]
sounds like a bug with apmhttp? alternatively, dont use the logger chi/middleware which causes this to appear

**Comment by titpetric** [comment]
I think there's a bit of shared responsibility here. The io.ReaderFrom interface over ResponseWriter is implemented on an unexported struct. The http package doesn't document any conformance to io.ReaderFrom. At the very least, this is undocumented functionality, as you can't figure this out without reading the actual http package source code.

And secondly, implementing Hijacker interface doesn't rely on implementing the ReaderFrom interface. While I agree that in the end, both should, *hopefully* be implemented, it wouldn't hurt to treat them as individual interfaces. It's not expected that the Hijacker interface would be lost, if the ReaderFrom interface isn't implemented. For some reason, here they are tightly coupled.

**Comment by VojtechVitek** [comment]
Perhaps the code in chi should be more relaxed
```diff
- 		if fl && hj && rf {
+ 		if fl || hj || rf { // if flusher, hijacker or readerFrom, then wrap with the fancy writer
 			return &httpFancyWriter{bw}
 		}
```

this should be a backward compatible change, unless I'm missing something

**Comment by titpetric** [comment]
@VojtechVitek As per http package docs:

> The default ResponseWriter for HTTP/1.x connections supports Hijacker, but HTTP/2 connections intentionally do not. ResponseWriter wrappers may also not support Hijacker. Handlers should always test for this ability at runtime.

The assertion for http.Hijacker over httpFancyWriter will always succeed, regardless of parent writer capabilities. The same also goes for http.Flusher. The implementation for fancy writer doesn't take this into account, it would satisfy the interfaces and then panic due to lack of error handling there.

If io.ReaderFrom is implemented in all stdlib ResponseWriter implementations - I'd argue that much like Hijacker and Flusher, support for io.ReaderFrom for ResponseWriter wrappers implementation is optional, based on existing documentation for those interfaces that http package publishes. That being said, I've seen references to it from 2014, so it exists in the standard library for a long time now - albeit i'm not even sure the go compatibility promise applies to an unexported struct.

I'd suggest:

- implement ReadFrom on basicWriter (return http.ErrNotSupported from function if type assertion on wrapped writer fails),
- implement Flusher on basicWriter (just do nothing if type assertion on wrapped writer fails),
- a specific writer with Hijacker support - people are doing assert type checking for this capability,
- a specific writer for http.Pusher for http2 (http2 also doesn't have Hijack, so an union struct isn't needed)

I'm up for fielding a PR if you think this looks legit, I guess I can base it on master?

**Comment by titpetric** [comment]
Any comment regarding my suggestions here? I’d like to leave some time for comments in case I missed something glaringly obvious. Looking at the current tests, I think I’m missing something about flusher side effects, but I can’t pinpoint it right now. The function returns nothing but affects the state somehow (wroteHeaders checks)?

**Comment by pkieltyka** [comment]
this is a tricky one as it may have whack-a-mole implication with other libraries. I'd have to dive back into the problem space in order to give proper advice and I'm not available for that at the moment

**Comment by pkieltyka** [comment]
hey all, if someone can produce a breaking test case to demonstrate the problem (with stdlib), then I'll include it in the middleware tests and find a solution
