### ISSUE TITLE
NewWrapResponseWriter: http.Hijacker not wrapped in flushWriter

### ISSUE THREAD

**Issue by nsemikov** [go-chi/chi#544]
In my code, gorilla Websocket upgrader fails after NewWrapResponseWriter: https://github.com/go-chi/chi/blob/cf97bef8b1405c9177bd88eca166ed4f16b9fc80/middleware/wrap_writer.go#L15-L36
It print to stdout:
```websocket: response does not implement http.Hijacker```

Seems it happens because there no `Hijack` method in `flushWriter`.

Sorry for my English =)

**Comment by VojtechVitek** [comment]
Looks like a duplicate of #543. Closing. Please feel free to reopen.

**Comment by titpetric** [comment]
@nsemikov are you using Elastic APM or something else that would wrap the http ResponseWriter?

**Comment by nsemikov** [comment]
I am using [gqlgen](https://github.com/99designs/gqlgen).

**Comment by titpetric** [comment]
It’s likely gqlgen doesn’t implement os.ReaderFrom on their ResponseWriter
wrap. I’d suggest you file the issue upstream too.
