### ISSUE TITLE
Sub Domain Example

### ISSUE THREAD

**Issue by jeffreyantony** [go-chi/chi#547]
I am a beginner to Chi

Can anyone post an example for handling subdomain ? 

For example if I have the domain example.com and sub domain blog.example.com

From the Chi example I know the below code is enough to handle example.com. But how to handle blog.example.com subdomain ?

```
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})
	http.ListenAndServe(":3000", r)
}
```

**Comment by VojtechVitek** [comment]
Take a look at https://github.com/go-chi/hostrouter.

**Comment by jeffreyantony** [comment]
I already tried this hostrouter but the subdomain part didn't work for me.

One thing that confused me was, why the sub domain and the main domain are pointing towards the same function ? 

```
  // Requests to api.domain.com
  hr.Map("", apiRouter()) // default
  hr.Map("api.domain.com", apiRouter())
```

**Comment by pkieltyka** [comment]
This is even better: https://github.com/go-chi/chi/blob/master/middleware/route_headers.go

See comments for usage

**Comment by pkieltyka** [comment]
Btw, it points at the same function because the function returns the routing handlers for the endpoints, and each address specifies a router
