### ISSUE TITLE
Global middleware not invoked on not found and method not allowed handler

### ISSUE THREAD

**Issue by xyluet** [go-chi/chi#548]
Why global middleware is not called with these scenario?

```go
func Test(t *testing.T) {
	ch := make(chan struct{})
	router := chi.NewRouter()
	router.Use(
		func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				ch <- struct{}{}
				next.ServeHTTP(w, r)
			})
		},
	)
	router.NotFound(func(w http.ResponseWriter, r *http.Request) {})
	w, r := httptest.NewRecorder(), httptest.NewRequest("", "/", nil)
	router.ServeHTTP(w, r)
	select {
	case <-time.After(100 * time.Millisecond):
		t.Fatal("timeout")
	case <-ch:
	}
}

```

**Comment by pkieltyka** [comment]
@xyluet what version of chi are you running? 

The test here shows the notfound handler to be triggering the middleware stack: https://github.com/go-chi/chi/blob/master/mux_test.go#L319-L393

**Comment by hacdias** [comment]
I am having exactly the same issue and I really can't understand what's wrong. Let me know if I can help somehow debug this. The exact same code from the test gives `9: interface conversion: interface {} is nil, not string` on my machine. I'm using v1.5.1.

**Comment by pkieltyka** [comment]
@hacdias can you paste/submit a failing test case?

**Comment by hacdias** [comment]
I copied this bit from the test:

```go
sr1.Group(func(sr1 Router) {
		sr1.Use(func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				r = r.WithContext(context.WithValue(r.Context(), ctxKey{"mw2"}, "mw2"))
				next.ServeHTTP(w, r)
			})
		})
		sr1.NotFound(func(w http.ResponseWriter, r *http.Request) {
			chkMw2 := r.Context().Value(ctxKey{"mw2"}).(string)
			w.WriteHeader(404)
			w.Write([]byte(fmt.Sprintf("sub 404 %s", chkMw2)))
		})
	})
```

I run it as:

```go
package main

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r = r.WithContext(context.WithValue(r.Context(), "mw2", "mw2"))
			next.ServeHTTP(w, r)
		})
	})
	r.NotFound(func(w http.ResponseWriter, r *http.Request) {
		chkMw2 := r.Context().Value("mw2").(string)
		w.WriteHeader(404)
		w.Write([]byte(fmt.Sprintf("sub 404 %s", chkMw2)))
	})

	http.ListenAndServe(":4444", r)
}
```

I navigate to the page and it panics:

```
2021/02/05 23:14:40 http: panic serving [::1]:55693: interface conversion: interface {} is nil, not string
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc00010aaa0)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:1801 +0x147
panic(0x1272ea0, 0xc00007afc0)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:975 +0x47a
main.main.func2(0x130d940, 0xc0001400e0, 0xc000154000)
	/whatever/test.go:21 +0x19f
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2042
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00006c2a0, 0x130d940, 0xc0001400e0, 0xc000154000)
	/Users/henriquedias/go/pkg/mod/github.com/go-chi/chi@v1.5.1/mux.go:62 +0x553
net/http.serverHandler.ServeHTTP(0xc000140000, 0x130d940, 0xc0001400e0, 0xc000154000)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00010aaa0, 0x130dd40, 0xc000022340)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2969 +0x36c
```

I agree it's odd that the test is passing. I am using the newest version so it's quite odd.

**Comment by pkieltyka** [comment]
@hacdias thanks for that, thats helpful. What is the goal with your router above btw? How come you're making a router without any routes defined on it? In any case, for completeness + better dev experience I have resolved this in: https://github.com/go-chi/chi/commit/894714a52f0c36c24e608bd18723cd7fc7285092

**Comment by hacdias** [comment]
@pkieltyka that is not my use case. I just wanted to show you that it is not working. My use case is as follows:

1. I have a set of defined routes.
2. Then I need a "catch-all" which checks if there is a file (after sanitizing the URL very well) in the file system in a certain location, if so, it renders the post.

As far as I understood, the only way to make a catch all route with chi is using the Not Found handler. However, I also wanted it to use the middleware!

**Comment by pkieltyka** [comment]
@hacdias I've started writing a basics DOCS.md to help with some of the basic operations -- this issue has helped me realize thats been missing: https://github.com/go-chi/chi/pull/580

FYI, for a catch-all you can use `/*` pattern, such as ..

```go
r := chi.NewRouter()
r.Get("/*", myCatchAllHandler)

func myCatchAllHandler(w http.ResponseWriter, r *http.Request) {
  catchAllParam := chi.URLParam(r, "*")
  w.Write([]byte(catchAllParam))
}
```

for file-serving, etc. see https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go
