### ISSUE TITLE
Empty path param always passes regexp validation

### ISSUE THREAD

**Issue by kasparjarek** [go-chi/chi#551]
Empty path param passes regexp validation regardless the regexp used.

Chi version `v4.1.2`

**Reproducer**
```
package main

import (
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	mux := chi.NewMux()
	mux.Get("/foo/{x:.+}/bar", func(w http.ResponseWriter, r *http.Request) {
		if _, err := w.Write([]byte("passed\n")); err != nil {
			panic(err)
		}
	})
	http.ListenAndServe(":8080", mux)
}
```
Execute `curl -v 'http://localhost:8080/foo//bar'`. 

**Expected**

- the 404 status code be returned without  executing handler fnc

**Actual**

- handler executed and `passed` string returned

**Notes**

- From my point of view the non-empty path param should be validated by default, even without specifying regexp. The regexp `.*` would have to be used to allow empty path param. This is also how [Gorilla mux](https://github.com/gorilla/mux) works and it's intuitive in my opinion.

**Comment by Jleagle** [comment]
+1, also having this issue with this route:
`r.Mount("/{type:(type1|type2)}", handler)`

Which matches the path:
`//foo`

**Comment by pkieltyka** [comment]
There may be a very small edge case for the extra "/" which is matching with the regexp. Feel free to submit a PR with a test included.
