### ISSUE TITLE
Ambiguous trailing slash matching

### ISSUE THREAD

**Issue by destag** [go-chi/chi#556]
I've found out that chi matches request with trailing slash depending on whether the matching route is root of sub-router.

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)

	r.Get("/user", welcome)

	r.Route("/nested", func(r chi.Router) {
		r.Route("/user", func(r chi.Router) {
			r.Get("/", welcome)
		})
	})

	http.ListenAndServe(":3000", r)
}

func welcome(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("welcome"))
}
```

Output of the above example:
```
2020/11/26 16:08:35 "GET http://localhost:3000/user HTTP/1.1" from [::1]:47514 - 200 7B in 10.175µs
2020/11/26 16:08:37 "GET http://localhost:3000/user/ HTTP/1.1" from [::1]:47516 - 404 19B in 47.045µs
2020/11/26 16:08:43 "GET http://localhost:3000/nested/user HTTP/1.1" from [::1]:47518 - 200 7B in 45.487µs
2020/11/26 16:08:45 "GET http://localhost:3000/nested/user/ HTTP/1.1" from [::1]:47520 - 200 7B in 17.615µs
```

`user/` hasn't been matched because of trailing slash but `nested/user/` has been matched despite of it.
My expected behavior is that none of the trailing slash requests should be matched.

If it is not a bug then, in my opinion, this should be explicitly documented

**Comment by pkieltyka** [comment]
thanks @destag `nested/user/` matches because of the `r.Get("/", welcome)` on the `/user` subrouter. It's true this could be a bit more explicit in the README, thanks for bringing up the issue so hopefully others can read and learn from it in the future.
