### ISSUE TITLE
Cleaning the Request URL?

### ISSUE THREAD

**Issue by mariusor** [go-chi/chi#558]
Hello, I have a small issue but I'm not sure it's not desired behaviour. I've looked through the examples and issues and couldn't find anything relevant.

Basically I am wondering what the stance is for URLs with non-canonical paths. As an example I have two routes:

    /users
    /users/{id}

If by mistake someone types `//users` as the path of the request, it will resolve to the second route instead of the first (which in my opinion makes more sense).

So, if this is desired behaviour, what would the idiomatic way of fixing this be?

**Comment by pkieltyka** [comment]
> If by mistake someone types //users as the path of the request, it will resolve to the second route instead of the first (which in my opinion makes more sense).

hmm, if the user passes "//users", it will resolve to a 404/Not found -- how did you make it resolve to either endpoint? Please provide a mini-example main.go (copy _examples/hello-world and modify to demonstrate the resolution you're seeing)

If you'd like to clean the url path, you can write a middleware.. here's a quick one I just whipped up:

```go
func CleanRequestPath(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rctx := chi.RouteContext(r.Context())

		routePath := rctx.RoutePath
		if routePath == "" {
			if r.URL.RawPath != "" {
				routePath = r.URL.RawPath
			} else {
				routePath = r.URL.Path
			}
			rctx.RoutePath = path.Clean(routePath)
		}

		next.ServeHTTP(w, r)
	})
}
```

**Comment by pkieltyka** [comment]
also FYI: https://github.com/go-chi/chi/commit/5fe292dcdcd32fe71fba2b35ba664e3420d50349

**Comment by mariusor** [comment]
Thank you.

**Comment by mariusor** [comment]
@pkieltyka the example is wrong though, you need to clean the path outside of the `if` block.

**Comment by pkieltyka** [comment]
@mariusor the example is correct. Give it a try first.

**Comment by mariusor** [comment]
The call to path.Clean is done only if `rctx.RoutePath` is an empty string. From what I can see the Request Context is already populated with the request path at the time when the middlewares are being invoked, but maybe I'm missing something.
