### ISSUE TITLE
How can I deploy my API made with Chi?

### ISSUE THREAD

**Issue by luisfelipesdn12** [go-chi/chi#563]
How you guys deployed your applications? It's possible with the `File Manager` of and regular cPanel? What process I must do?

**Comment by pkieltyka** [comment]
hey @luisfelipesdn12 there are many options, I'd suggest to check out DigitalOcean or Heroku to deploy your chi web service.

Search "digitalocean how to deploy docker golang container" or "digitalocean how to deploy docker go container". Surprisingly though I'm not finding as good of content as I'd expect out there, but DigitalOcean + docker is a fine choice and should be easy.

Another approach would be to use Heroku, I found: https://devcenter.heroku.com/articles/getting-started-with-go?singlepage=true
