### ISSUE TITLE
Feature request: expose native handler lookup

### ISSUE THREAD

**Issue by bokwoon95** [go-chi/chi#564]
This might be an unusual request but could you expose the native routing capability of the router? Something that looks like

```go
handler, err := chi.FindHandler(mux, "GET", "/some/path")
if err != nil {
    panic(err)
}
// serve the request
handler.ServeHTTP(w, r)
```

My use case is for non-technical users to be able to define their own vanity URLs that redirect to existing handlers. This would be done at runtime, without recompilation, so I can't just do it by registering new routes on the router. Basically I'll associate vanity URLs with handler URLs , and whenever a vanity URL request comes in I lookup the associated handler URL + handler, and serve the request with that handler. `http.Redirect` can't do this because it changes the URL entirely. I just want the handler obtained by looking up the URL in the router, without actually serving the request.

This can be done with `chi.Walk`, but I don't want to walk the entire router looking for the handler I want. I want to leverage the routing algorithm to directly lookup a handler for a given URL. Do you think it's worth exposing this feature?

**Comment by pkieltyka** [comment]
Yes, you can do it with https://github.com/go-chi/chi/blob/master/mux.go#L350

check tests or middlewares for example usage, we use it in GetHead middleware

**Comment by bokwoon95** [comment]
That is very cool, thanks. Didn't realize I could simply reach into the *chi.context, modify the route and call the next handler.
