### ISSUE TITLE
URL param containing slashes

### ISSUE THREAD

**Issue by nawa** [go-chi/chi#566]
Is it possible to define and read and URL param containing slashes?

```go
router.Get("/prefix/{key:.+}", func(w http.ResponseWriter, r *http.Request) {
  w.Write([]byte(chi.URLParam(r, "key")))
})
```

Current behavior:
```sh
curl localhost/prefix/some/path/with/slashes

404 error
```

Expected behavior
```sh
curl localhost/prefix/some/path/with/slashes

some/path/with/slashes
```

For instance, such regexp pattern `{key:.+}` works in `gorilla/mux` as expected

**Comment by pkieltyka** [comment]
hey @nawa chi and gorilla mux are not the same and I can’t speak for it’s pattern matching. 

With chi, use ‘Get(“/prefix/*”, ..)’ and then retrieve the param with ‘chi.URLParam(r, “*”)’
