### ISSUE TITLE
Is possible to handle subdomains with chi?

### ISSUE THREAD

**Issue by luisfelipesdn12** [go-chi/chi#568]
Is there a feature like that?

```go
router.Route("{subdomain}.localhost", func(r chi.Router) {
     // control routes...
})
```

**Comment by fuadarradhi** [comment]
you need to read the doc,
https://github.com/go-chi/hostrouter

**Comment by luisfelipesdn12** [comment]
> you need to read the doc,
> https://github.com/go-chi/hostrouter

Thank you! How it works in deployment? To me, it used to work just in my localhost.

**Comment by fuadarradhi** [comment]
set on the web server configuration, the same as on localhost (/etc/host)
