### ISSUE TITLE
path regex won't match slashes routes even the any digit {.*} regex is used

### ISSUE THREAD

**Issue by kabaluyot** [go-chi/chi#569]
I wanted to detect this route `/verify-email/send` and the second slash doesn't seems detected by the regex.

r.HandleFunc("/{path:.*}", gatewayController)

**Comment by kabaluyot** [comment]
Im doing this because Im making a reverse proxy for my api-gateway

**Comment by fuadarradhi** [comment]
not detected when using a proxy or when not using proxy ?

**Comment by kabaluyot** [comment]
With or without proxy. Even when used in normal routing.

**Comment by fuadarradhi** [comment]
you can use 
r.HandleFunc("/*", gatewayController)
or
r.HandleFunc("/{path:.*}/{subpath:.*}", gatewayController)

**Comment by kabaluyot** [comment]
For the first option, no since its not a base route. For the second option,
it works for the first depth but how about n depth? (actually I have a
workaround for this now)

**Comment by kabaluyot** [comment]
So the .* regex will include the / in the route..

**Comment by fuadarradhi** [comment]
"/{path:.*}" and "/*" is the same,
what makes the difference,
both read path from base

**Comment by kabaluyot** [comment]
yes correct. However, The regex is for the "/" after the base. So with "/{path:.*}", it won't work with `/verify-email/send`, the "/" before send is not detected and matched
