### ISSUE TITLE
Serving static files and rendering HTML pages

### ISSUE THREAD

**Issue by darienmiller88** [go-chi/chi#574]
Hey, I just started using chi for smaller projects, and I was curious how static file serving and HTML/template rendering is handled here. What's the shortest way to accomplish it?

Here's what I tried for file serving
```
router := chi.NewRouter()
fs := http.FileServer(http.Dir("../client/static"))
router.Handle("/client/static/", http.StripPrefix("/client/static", fs))
log.Fatal(http.ListenAndServe(":3333", router))
```
Folder structure:

```
api
   -main.go

client
   static
       -css
       -img
       -js

   -index.html
```

**Comment by pkieltyka** [comment]
hey @darienmiller88 -- check out the example here https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go#L46 .. its a one liner once you define the FileServer method somewhere in your packages

**Comment by maheshkumar2150** [comment]
Refused to apply style from 'http://localhost:3000/static/css/style.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

```
workDir, _ := os.Getwd()
filesDir := http.Dir(filepath.Join(workDir, "static"))
FileServer(r, "/static/", filesDir)
```

**Comment by kateile** [comment]
@maheshkumar2150 did you solve it?

I have the same problem and I have reporoduce it [here](https://github.com/kateile/flutter-web-with-golang-server) 
@pkieltyka can you have a look?
