### ISSUE TITLE
URL parameters with hyphens divided by hyphens

### ISSUE THREAD

**Issue by AlexanderMatveev** [go-chi/chi#578]
I'm trying to create a path pattern for URLs like `/some-path/some-slug-VENzc2dP`, where:
- `some-slug` may have hyphens
- `VENzc2dP` is youtube-like generated ID, that can't have hyphens

Is is possible to write route like this, without need to combine params in one and parse manually?

Something like:

```golang
r.Get("/some-path/{slug:[a-zA-Z0-9-]+}-{key:[a-zA-Z0-9]+}", s.SomeHandler)
```

**Comment by pkieltyka** [comment]
how about .. `r.Get("/some-path/{slug}-{key}", s.SomeHandler)` ?

**Comment by AlexanderMatveev** [comment]
Nope, because how would router know if path part between hyphens belongs to `slug` or `key`:

`/some-path/some-long-slug-divided-by-hyphens-sOMeKey`

**Comment by pkieltyka** [comment]
I’ll have to try it, but I imagine it’ll take first component with first - as slug and the rest as key. I suggest to read the tests of tree_test.go which I wrote similar tests for

**Comment by AlexanderMatveev** [comment]
Yes, that's the point.

Slug with hyphens generated from some string and identifier at the end of path is common case for search engines optimisation.

**Comment by pkieltyka** [comment]
I suggest to read the tests, and build your routes and url path according to what is available. If something is missing, then use `some-path/{slug}` matcher instead, and parse it for your format.

```go
r.Get("/articles/{key}-{slug}", func(w http.ResponseWriter, r *http.Request) {
	key := chi.URLParam(r, "key")
	slug := chi.URLParam(r, "slug")
	w.Write([]byte(fmt.Sprintf("key:%s slug:%s", key, slug)))
})
```

```
$ curl http://localhost:4444/articles/23234234-some-great-article
key:23234234 slug:some-great-article
```

I understand you want {slug}-{key} .. see if you can bend the supported matchers to make it happen, perhaps with regexp but I think the best option and most efficient is to use a param and parse it at application level.
