### ISSUE TITLE
Using r.Use(middleware.Logger) breaks w.(http.CloseNotifier).CloseNotify()

### ISSUE THREAD

**Issue by gilgameshskytrooper** [go-chi/chi#582]
I understand that `CloseNotifier` has been deprecated on chi@v4 according to [https://github.com/go-chi/chi/issues/347](https://github.com/go-chi/chi/issues/347).

However, I had a problem which I could only solve by using the following code in my handler func:

```go
func HandlerFunc(w http.ResponseWriter, r *http.Request) {
	notify := w.(http.CloseNotifier).CloseNotify()

	go func() {
		<-notify
		log.Println("HTTP Client prematurely killed the request before the ProcessLivenessVideoForVerificationV1 handler func could respond!!!")
	}()

}
```

If there is a way to do this same thing in `Request.Context`, please show me. I looked around, but could not find anything that fit the exact need: which was to detect when an HTTP client terminated the request before the HandlerFunc had the chance to respond.

Back to my issue:

When registering the above endpoint to `r := chi.NewRouter`, and using: `r.Use(middleware.Logger)`, I get a stacktrace I do not quite understand:

```
 panic: interface conversion: *middleware.httpFancyWriter is not http.CloseNotifier: missing method CloseNotify
```

When I take out the Logger middleware, the HandlerFunc operates just fine even with the CloseNotifier deprecation.

---

## Full Example

```go
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {

	router := chi.NewRouter()
	router.Use(middleware.RealIP)
	router.Use(middleware.RequestID)
	router.Use(middleware.Recoverer)
	router.Use(middleware.Logger) // Commenting this out makes the code work

	router.Get("/", func(w http.ResponseWriter, r *http.Request) {

		notify := w.(http.CloseNotifier).CloseNotify()

		go func() {
			<-notify
			fmt.Println("HTTP Client prematurely killed the request")
		}()

		time.Sleep(10 * time.Second)

		w.Write([]byte("Hello World"))
	})

	http.ListenAndServe(":9000", router)

}
```

**Comment by yursan9** [comment]
I don't know if you still need this or not, but you can write something like this:
```
func(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    go func() {
	    <-ctx.Done()
	    fmt.Println("HTTP Client prematurely killed the request")
    }()
    
    time.Sleep(10 * time.Second)
    w.Write([]byte("Hello World"))
}
```
