### ISSUE TITLE
How to disable fileserver directory listings?

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#585]
I saw this example here: https://github.com/go-chi/chi/blob/master/_examples/fileserver/main.go.

Is there a way to disable directory listings?

**Comment by pkieltyka** [comment]
I'm not sure. This isn't really chi related, perhaps post on Stackflow?

**Comment by frederikhors** [comment]
I thought it might be useful to enrich that example. That's all.

**Comment by gilgameshskytrooper** [comment]
I would also like to know.

**Comment by VojtechVitek** [comment]
https://stackoverflow.com/a/51170557

**Comment by gilgameshskytrooper** [comment]
> https://stackoverflow.com/a/51170557

tyvm
