### ISSUE TITLE
Possible regression in 1.5.2: middleware got instantiated and invoked twice

### ISSUE THREAD

**Issue by unext-wendong** [go-chi/chi#587]
We noticed the following behavior changes between 1.5.1 and 1.5.2+ (1.5.2 and 1.5.3) related to middleware handlers.
- Middleware handlers got instantiated twice in 1.5.2+. It's once in 1.5.1.
- Middleware handlers got invoked twice for URLs routed to NotFound handlers in 1.5.2+. It's once in 1.5.1.

Example code:
```
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi"
)

func main() {
	r := chi.NewRouter()

	r.Use(func(next http.Handler) http.Handler {
		fmt.Println("Instantiating test middleware...")
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			fmt.Println(r.URL.Path, "going through middleware...")
			next.ServeHTTP(w, r)
		})
	})

	r.NotFound(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(404)
		w.Write([]byte("Resource not found\n"))
	})

	r.Get("/hello", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		w.Write([]byte("Hello world!\n"))
	})

	svr := &http.Server{
		Addr:    ":6060",
		Handler: r,
	}

	fmt.Println("Starting server...")
	if err := svr.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fmt.Println("Server stopped with error:", err)
	} else {
		fmt.Println("Server stopped normally")
	}
}
```

Output after one `GET /hello` and one `GET /nihao` requests in 1.5.2+:
```
Instantiating test middleware...
Instantiating test middleware...
Starting server...
/hello going through middleware...
/nihao going through middleware...
/nihao going through middleware...
```

Output of the same case in 1.5.1:
```
Instantiating test middleware...
Starting server...
/hello going through middleware...
/nihao going through middleware...
```

**Comment by pkieltyka** [comment]
thanks for the report. I thought there was a test cases in the code checking against this very issue but perhaps not. I suspect the issue started from here https://github.com/go-chi/chi/commit/894714a52f0c36c24e608bd18723cd7fc7285092

**Comment by vadimi** [comment]
it seems like `MethodNotAllowed` middleware has the same issue: 00cc734b678d2a08839ee2e35904e0b0e46c479d

**Comment by stephenafamo** [comment]
Just ran into this same thing.

If `NotAllowed()` is called **AFTER** setting middlewares, the middlewares will be called twice when the route is not found.

**Comment by pkieltyka** [comment]
Yes it’s a known regression. I’ll fix it when I have time

**Comment by pkieltyka** [comment]
released a new version with the fix, https://github.com/go-chi/chi/releases/tag/v5.0.2

**Comment by atombender** [comment]
Still seeing this with 5.0.2. Basic code:

```go
r := chi.NewRouter().With(someMiddleware)
r.Route("/v1", func(r chi.Router) {
  r.Get("/", someHandler)
})
r.NotFound(func(w http.ResponseWriter, r *http.Request) {
  ...
})
```

When the `NotFound` handler is invoked, the `someMiddleware` middleware is invoked twice.

Notice the use of `With()` here. Does not happen if I move the `With()` into the nested router.
