### ISSUE TITLE
GoLand cannot resolve newest version of chi

### ISSUE THREAD

**Issue by nimabrownlee** [go-chi/chi#592]
Installed it by `go get -u github.com/go-chi/chi/v5`

and imported it by using

```
"github.com/go-chi/chi/v5"
"github.com/go-chi/chi/v5/middleware"
```
Might be because the v5 github page don't even exist? Or is there something I've missed?

**Comment by pkieltyka** [comment]
Lol please report to Go team. I'm done supporting SIV with chi. Next stop I will be archiving this project and starting a new one from v0

**Comment by nimabrownlee** [comment]
@pkieltyka Hey, sorry if I offended you. I'm new to the Go world and your router seems to be the best when I was researching. Best wishes with your other work/projects.

**Comment by pkieltyka** [comment]
@nimabrownlee you most certainly did not offend me. I am just upset about Go tooling issues I'm faced with. 

To me, software is art, and I intentionally spent so much time to craft chi as it brings me lots of joy in doing so. As a result of the Go module system, the issue you're facing is a result from its design decisions, and its quite upsetting to me after all of my efforts to produce the best possible developer experience, I'm unable to provide that.

**Comment by pkieltyka** [comment]
@nimabrownlee https://github.com/oxyno-zeta/s3-proxy/pull/158/files#r584305332 @oxyno-zeta

**Comment by nimabrownlee** [comment]
@pkieltyka I read that thread and I definitely understand you. This is your baby and pride, you've put a lot of time and effort it into it. And it really shows because I've only seen positive things about chi. Hopefully this road block doesn't stop you from continuing your great open source work.

Anyway, best of luck with whatever you choose to do. At the end of the day, you should do things that makes you happy. You're not obligated to do anything even though the community is frustrated. Thanks for chi. People certainly love it.

**Comment by oxyno-zeta** [comment]
The aim of the denied PR on my side was because I was waiting a end on this go module story :) . 
I was following all the story across all issues and I prefer to wait to have something stable in order to upgrade my project. I'm definitly not against upgrading !

Hope I haven't upset you @pkieltyka ... I love your project, that's why I'm using it in my S3-proxy code :). Thanks for chi from me too !
