### ISSUE TITLE
bug?: return 404 if the request link end with `/`

### ISSUE THREAD

**Issue by a1012112796** [go-chi/chi#594]
Hello, I found a problem that if append an ``/`` at the end of link (for example: ``http://127.0.0.1:8088/test/``), It will response 404 instead of the defined logic. I think maybe it's a bug. Thanks. example result:
![tmpb](https://user-images.githubusercontent.com/25342410/109519385-295d9e00-7ae6-11eb-96ad-63e35a5fb3dd.png)

**Comment by chemidy** [comment]
Check the middleware StripSlashes : 


| chi/middleware Handler | description                                                             |
| :--------------------- | :---------------------------------------------------------------------- |
| [StripSlashes]         | Strip slashes on routing paths                                          |

[StripSlashes]: https://pkg.go.dev/github.com/go-chi/chi/middleware#StripSlashes
