### ISSUE TITLE
open redirect vulnerability

### ISSUE THREAD

**Issue by bataras** [go-chi/chi#595]
https://github.com/go-chi/chi/blob/fb48a47641af106c7eae2f09864e7fecd54237bf/middleware/strip.go#L23

RedirectSlashes returns a path the begins with //, causing the browser to go to an external website...

curl mychiapp.com//example.com redirects to http://example.com

**Comment by pkieltyka** [comment]
@bataras I'm unable to reproduce this redirects to example.com .. can you provide an example program or test case?

**Comment by pkieltyka** [comment]
```go
package main

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

func main() {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	r.Use(middleware.StripSlashes)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hello world"))
	})

	r.Get("/hi", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hi"))
	})

	r.Get("/blah*", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("blah"))
	})

	http.ListenAndServe(":3333", r)
}
```

this above program should cover the cases. Let me know the curl command you're using to cause the issue.

**Comment by pkieltyka** [comment]
closing as problem is incorrectly reported as there is no issue with the current master that I can determine through my testing
