### ISSUE TITLE
GO1.16 is too new for Google Cloud App Engine Standard

### ISSUE THREAD

**Issue by jaylee185** [go-chi/chi#597]
Question regarding default go language version. Is v5 has to use 1.16? I have encountered some issue while deploying code to Google Cloud. The latest version they support is 1.14. 

And it doesn't look like `go mod` command is providing any help. It basically ignores the version we have in our `go.mod` file. It still pulls the latest release any way. 

```Error message: # github.com/go-chi/chi/v5
../../google.go.gomod/gopath/pkg/mod/github.com/go-chi/chi/v5@v5.0.0/tree.go:60:20: invalid operation: 2 << n (shift count type int, must be unsigned integer)
note: module requires Go 1.16```

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/pull/599

this should resolve the issue
