### ISSUE TITLE
GO1.16 is too new for Google Cloud App Engine Standard

### ISSUE THREAD

**Issue by jaylee185** [go-chi/chi#600]
Sorry, I want to reopen this issue.
I suspect the issue is actually in the `go.mod`
I believe GCP for some reason is checking the version there.
```
module github.com/go-chi/chi/v5

go 1.16
```
Do you think we can use a lower go version there?

**Comment by pkieltyka** [comment]
@jaylee185 I don't believe the go.mod file and version of go it announces is causing the problem. Can you provide more details or links to docs stating this issue?

See https://github.com/go-chi/chi/actions where we do CI testing with go 1.14, 1.15, 1.16

**Comment by mfridman** [comment]
This is a GCP limitation, which only now supports 1.15 in "preview" mode. Indeed 1.16 is too new :/ 

afacis there are no _new_ Go features (1.15 or 1.16) being used by chi, so setting the go directive to 1.14 would indicate the minimum supported version for the project.

**Comment by mfridman** [comment]
Having said that, @jaylee185 can you confirm what version you're using on GCP ? The error you linked in the other ticket may be the result of your using go1.12, and so thew solution is likely to update your config to using 1.14 (which is the latest, non-preview version)

**Comment by jaylee185** [comment]
Yeah, I'm developing using 1.12. Though, the latest GCP support is 1.14. I can try to use 1.14, but I'm wondering how GCP found 1.16.

**Comment by mfridman** [comment]
Ye, the error you mentioned is more related to a change in the Go standard library in Go 1.13, see last [2 paragraphs](https://golang.org/doc/go1.13#language). So your best solution is to upgrade from 1.12 to at least 1.13 (or even better 1.14) which _likely_ solve your issue

But chi cannot set its go directive to 1.12, so ya'll have to meet in the middle haha.

I still believe @pkieltyka should consider setting the directive to the minimum supported version: go1.14. At least that was my interpretation of reading [linked issue](https://github.com/golang/go/issues/30791)

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/pull/601

please lmk if this unblocks and works
