### ISSUE TITLE
Allow custom HTTP methods like PURGE

### ISSUE THREAD

**Issue by titpetric** [go-chi/chi#602]
Currently, if we try to register a custom HTTP method with MethodFunc()/Method() like `PURGE`, it results in a panic.

```
panic: chi: 'PURGE' http method is not supported.

goroutine 1 [running]:
github.com/go-chi/chi.(*Mux).Method(0xc000115620, 0xb3c775, 0x5, 0xb3b365, 0x2, 0xc01380, 0xc0002a1110)
	/root/users/black/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:120 +0x14c
github.com/go-chi/chi.(*Mux).MethodFunc(...)
	/root/users/black/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:128
```

Particularly, the PURGE keyword isn't in the HTTP RFCs, but at least three places implement it:

- [varnish cache purge](https://varnish-cache.org/docs/trunk/users-guide/purging.html)
- [nginx cache purge](https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/#purge)
- [curl supports anything](https://curl.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html)

Even if PURGE is not officially registered in the RFCs/iana, the vendor-specific implementations in the wild are common. Ideally, it's expected that Method/MethodFunc would allow non-standard methods to implement compatible behaviour.

**Comment by pkieltyka** [comment]
hey @titpetric did you call `chi.RegisterMethod("PURGE")` first..? perhaps I can relax this someday and auto-register methods through use, but right now you need to register non-standard methods first

**Comment by titpetric** [comment]
Nope, I didn't, I haven't looked at the code yet if exceptions are possible, thanks for the info. My google-fu failed me today.

Let's consider the problem resolved. Should I keep the issue open, for this "some day" when RegisterMethod can be removed? :)

**Comment by titpetric** [comment]
Confirming: RegisterMethod resolves the issue.
