### ISSUE TITLE
middleware.DefaultLogger logs partial contents multiple times

### ISSUE THREAD

**Issue by masseelch** [go-chi/chi#604]
Hi, great package. We use it a lot. 

We recently decided to add the logger to our file-server. We noticed that streamed responses with bigger files result in all chunks sent being reported (partial content). 

This is not rellay a bug, since there are indeed multiple PartialContent http responses. But we'd like a way to log the incoming request and the time it finished.

**Comment by mfridman** [comment]
@masseelch Would the [middleware.WrapResponseWriter](https://pkg.go.dev/github.com/go-chi/chi/v5@v5.0.3/middleware#WrapResponseWriter) be something you could use?

In the middleware wrap the response writer? Something like this:

```
func LoggerHandler(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)
		start := time.Now()
		defer func() {
			since := time.Since(start).Milliseconds()
			status := ww.Status()

			log.Printf("request completed in %dms: HTTP %d", since, status)
		}()
		next.ServeHTTP(ww, r.WithContext(ctx))
	}

	return http.HandlerFunc(fn)
}
```

**Comment by VojtechVitek** [comment]
@masseelch @mfridman are there any action items on this issue? Any proposals to change chi's behavior?

If not, should we close this issue?

Thanks

**Comment by mfridman** [comment]
No action here, safe to close afaics. The snippet I shared should do the right thing and there are other ways to structure this as well.

**Comment by VojtechVitek** [comment]
OK, cool :) Closing.

@masseelch FYI, chi has alternative logger pkg - https://github.com/go-chi/httplog, which might be of help too.

In fact, we're just working towards v3 of the pkg. Here's a prototype of `github.com/go-chi/httplog/v3`: https://github.com/golang-cz/httplog
