### ISSUE TITLE
Context Parameter Question

### ISSUE THREAD

**Issue by jonleopard** [go-chi/chi#607]
Hello!

Sorry for the trivial question, but I'm in the process of migrating over to Chi from [httptreemux](https://github.com/dimfeld/httptreemux). With httptreemux, I've essentially extracted [httptreemux.ContextParams](https://github.com/dimfeld/httptreemux/blob/ebfe087278c7efe283236a9ee656b10ccffabb4e/context.go#L146) for use in my handlers (see `user.go`).

My question is, what would be Chi's closest function comparable to `ContextParams` that I could extract?

Thanks!

`/web/request.go`
```
// Params returns the web call parameters from the request.
func Params(r *http.Request) map[string]string {
	return httptreemux.ContextParams(r.Context())
}



// Decode reads the body of an HTTP request looking for a JSON document. The
// body is decoded into the provided value.
//
// If the provided value is a struct then it is checked for validation tags.
func Decode(r *http.Request, val interface{}) error {
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(val); err != nil {
		return err
	}

	return nil
}
```

`/handlers/user.go`

```
func (ug userGroup) queryByID(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
	ctx, span := trace.SpanFromContext(ctx).Tracer().Start(ctx, "handlers.userGroup.queryByID")
	defer span.End()

	v, ok := ctx.Value(web.KeyValues).(*web.Values)
	if !ok {
		return web.NewShutdownError("web value missing from context")
	}

	claims, ok := ctx.Value(auth.Key).(auth.Claims)
	if !ok {
		return errors.New("claims missing from context")
	}

	params := web.Params(r)
	usr, err := ug.store.QueryByID(ctx, v.TraceID, claims, params["id"])
	if err != nil {
		switch errors.Cause(err) {
		case database.ErrInvalidID:
			return validate.NewRequestError(err, http.StatusBadRequest)
		case database.ErrNotFound:
			return validate.NewRequestError(err, http.StatusNotFound)
		case database.ErrForbidden:
			return validate.NewRequestError(err, http.StatusForbidden)
		default:
			return errors.Wrapf(err, "ID: %s", params["id"])
		}
	}

	return web.Respond(ctx, w, usr, http.StatusOK)
}


```

**Comment by pkieltyka** [comment]
same thing, just use `r.Context()` to get the context object, its on the *http.Request object

**Comment by jonleopard** [comment]
Sorry, still a bit lost :(

Would something like this work for my use case?

```
// Params returns the web call parameters from the request.
func Params(r *http.Request) *chi.Context {
	return chi.RouteContext(r.Context())
}
```

Thanks again :)

**Comment by mfridman** [comment]
I think the closest to what you're looking for is described here: https://github.com/go-chi/chi#url-parameters

**Comment by jonleopard** [comment]
@mfridman That does the trick! Thanks a lot for the explanation as well! Gonna close this now. 

Cheers

**Comment by mfridman** [comment]
@jonleopard One thing I'll call out that might be useful.. chi also has a way to inspect the current path dynamically (similar to the `.Route()` method in that other linked router).

`chi.RouteContext(r.Context())` returns *chi.Context on which you can call `.RoutePattern()`

https://github.com/go-chi/chi/blob/2283e4951adbd82c8f6427117bd6b2a1c315e725/context.go#L108-L125

**Comment by jonleopard** [comment]
@mfridman  that certainly seems more useful, but I'm not sure how I could implement it with the `Atoi` type I'm using in `user.go`


web/request.go

```
// Params returns the web call parameters from the request.
func Params(r *http.Request) string {
	return chi.RouteContext(r.Context()).RoutePattern()
}
```
The previous router was returning `map[string]string `, which worked with the `strconv.Atoi(params["page"])` value. The new Chi router wants to return a string, rather than a map.  So when I go to use it in `user.go`, I get this error:
`cannot use params["page"] (value of type byte) as string value in argument to strconv.Atoi`.

handlers/user.go 

```
params := web.Params(r)

pageNumber, err := strconv.Atoi(params["page"])
if err != nil {
    return validate.NewRequestError(fmt.Errorf("invalid page format: %s", params["page"]), http.StatusBadRequest)
}
rowsPerPage, err := strconv.Atoi(params["rows"])
if err != nil {
    return validate.NewRequestError(fmt.Errorf("invalid rows format: %s", params["rows"]), http.StatusBadRequest)
}
```


I'm still a bit new to Go (and typed languages, for that matter), so I'm sure there's something painfully obvious that I'm doing wrong here.

**Comment by mfridman** [comment]
@jonleopard I assume you are referring to query params as part of the URL? E.g.,

```
https://example.com/api/v1/post/{postid}?page=1&rows=2
```

If so, use the standard library to grab the `url.Values` like so:

Assuming this request: `https://example.com/api/v1/post/12?page=1&rows=2`

```
postID := chi.URLParam(r, "postid")
// postID = 12

r.URL.Query()
// returns all values, but use the helper method:

rows := r.URL.Query().Get("rows")
// rows = 2

page := r.URL.Query().Get("page")
// page = 1

where r is the *http.Request
```
