### ISSUE TITLE
Sub-Router not handling Root /

### ISSUE THREAD

**Issue by iwilltry42** [go-chi/chi#612]
Hi there,
I just started using Chi for a new API Server.
I followed the REST example and at first it was working.
After some restructuring however, I'm facing 404s on sub-routers.
Here's the setup:

- Directory Structure
  ```
  main.go
    |- server/
      |- server.go
    |- routes/ 
      |- entries.go
  ```

- `main.go`
  ```Go
  func main() {
    log.Fatalln(
      server.Server{
        ListenAddress: ":3000",
      }.Serve(),
    )
  }
  ```

- `server/server.go`
  ```Go
  type Server struct {
    ListenAddress string
  }

  func (server Server) Serve() error {
    router := chi.NewRouter()

    // Attach Middlewares
    router.Use(middleware.RequestID)
    router.Use(middleware.RealIP)
    router.Use(middleware.Logger)
    router.Use(middleware.Recoverer)
    router.Use(middleware.Timeout(1 * time.Minute)) // requests should timeout after 1 minute

    // Sub-Routers
    router.Mount("/entries", routes.EntriesResource{}.Routes())

    return http.ListenAndServe(server.ListenAddress, router)
  }
  ```

- `routes/entries.go`
  ```Go
  type EntriesResource struct {}

  func (res EntriesResource) Routes() chi.Router {
    router := chi.NewRouter()

    router.Get("/", res.List) // does not work
    // router.Get("/entries", res.ListCopy) // works

    return router
  }

  func (res EntriesResource) List(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("Listing Entries"))
  }

  func (res EntriesResource) ListCopy(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("Listing Entries Copy"))
  }
  ```

So basically, I have to mirror the route that the sub-router was mounted at again in the sub-router.
From what I understand from the docs, I should start from `/` in the sub-router as well, so I'm a bit confused here :thinking:

**Comment by iwilltry42** [comment]
That's embarrassing... 
Apparently, I used `import "github.com/go-chi/chi"` in `server.go` unknowingly (auto-import), while it was correct (`"github.com/go-chi/chi/v5"`) everywhere else :roll_eyes: 
Works with v5 :+1:

**Comment by seal** [comment]
Just had this issue, quite a tricky one to find 
Thanks sir :)
