### ISSUE TITLE
Opencensus tracing middleware

### ISSUE THREAD

**Issue by krzysztofreczek** [go-chi/chi#615]
@pkieltyka, I have implemented a simple opencensus tracing middleware for chi router: https://github.com/krzysztofreczek/chi-opencensus-tracing

Are you interested in hooking it up somewhere closer to the router itself? I believe it could be useful for others.

Greetings!

**Comment by pkieltyka** [comment]
@krzysztofreczek neat! the go-chi/chi has a 0 dependency goal, but we do have https://github.com/go-chi/httptracer — have you seen it? Perhaps we can make the package over there better? Lmk

**Comment by krzysztofreczek** [comment]
Cool, I looked there but found it a bit incompatible with my problem. Let me have another look and check what we can do here. I will get back to you with some ideas. Maybe you have any?
