### ISSUE TITLE
standalone path matching lib

### ISSUE THREAD

**Issue by vtolstov** [go-chi/chi#616]
Hi. I'm maintain a fork of go-micro, and want to use chi pattern matching func instead of grpc-gateway (that used now)
most of the time i need based on request url path match some func and also have ability to extract url placeholder {some_var} inside url to map[string]string.

Doe it possible to utilize chi component for it without all other stuff?

**Comment by pkieltyka** [comment]
@vtolstov neat, however chi is what it is, you're free to copy the tree.go file and fork it as you'd like though

**Comment by vtolstov** [comment]
nice, thanks!
