### ISSUE TITLE
logger: alexedwards/scs combined with gorilla/websocket

### ISSUE THREAD

**Issue by bernhardreisenberger** [go-chi/chi#617]
Hi @pkieltyka Sorry to bother you again with this topic. related to #610 #584 #562

So i followed up with the changes from #584, tested the latest master with my app, and the websocket upgrade error described in #562 happens again. My test (`TestRequestLogger` in logger_test.go) did not cover the code correctly.

The function `NewWrapResponseWriter` in wrap_writer.go is crucial in this case.

You told me that you swore that gorilla/websocket did work prior my fix in #562 and now i know it did and why it wasn't in my case. 
In my setup, i use scs by alexedwards. He uses a custom writer bufferedResponseWriter (session.go)
This bufferedResponseWriter supports the hijacker, but not readerFrom nor Flusher interface.
This is why gorilla/websocket worked for you, but did not work for me, because with the middleware from scs the original responsewriter is wrapped in this bufferedResponseWriter.

Coming back to the `NewWrapResponseWriter` function. 
The httpFancyWriter is only used, if flusher and hijacker are supported. bufferedResponseWriter does not support the flusher, therefore `NewWrapResponseWriter` returns the basicWriter which does not support either of the three interfaces. :-(
This is where i messed up the test. the httptest writer supports the hijacker and the flusher interface -> `NewWrapResponseWriter` returns the httpFancyWriter.

interface support summary:
basicWriter: nothing
scs bufferedResponseWriter: hijacker
httptest writer: flusher, hijacker
httpFancyWriter: flusher, hijacker, readerFrom

in my application: bufferedResponseWriter -> basicWriter -> websocket.Upgrade fails...hijacker missing
in #583 and #610 case: httptest Writer -> httpFancyWriter -> readerFrom should not be supported, but is -> method missing (is now fixed with #584 by having a fallback implementation)

suggested solution:
add a type for each possibility to wrap with the same supported interfaces.
e.g.: bufferedResponseWriter supports hijacker only -> wrap with type that supports hijacker only
e.g.: httptest writer supports flusher and hijacker -> wrap with type that supports flusher and hijacker but not readerFrom.

adding fallback implementations would work too, but the option to check if an interface is supported will not be possible anymore.
e.g.: 
`_, fl := wrappedWriter.(http.Flusher)`. `fl` will always be `true` even though the underlying writer does not support the flusher.

i will open an issue in alexedwards/scs and ask him to add the flusher interface too. so my problem will be fixed and you do not have to deal with this. i opened this issue to let you know about my findings.

**Comment by pkieltyka** [comment]
I’m too busy to get into these weeds. I may just revert all community submissions relating to this and use my original code?

**Comment by pkieltyka** [comment]
Seems best solution is to revert the last few changes to wrap_writer.go — before https://github.com/go-chi/chi/pull/562/files

**Comment by bernhardreisenberger** [comment]
the test TestRequestLoggerReadFrom provided by @zlogic would still pass. so i guess this will work.

**Comment by bernhardreisenberger** [comment]
i tried to add the flusher to the bufferedResponseWriter in alexedwards/scs but that was not possible.

i rewrote wrap_writer.go so it can support alexedwards/scs and gorilla/websocket by adding the necessary types. this is the code that would be necessary (based on your original code):

```
type hijackWriter struct {
	basicWriter
}
func (f *hijackWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	hj := f.basicWriter.ResponseWriter.(http.Hijacker)
	return hj.Hijack()
}
var _ http.Hijacker = &hijackWriter{}

type flushHijackWriter struct {
	basicWriter
}
func (f *flushHijackWriter) Flush() {
	f.wroteHeader = true
	fl := f.basicWriter.ResponseWriter.(http.Flusher)
	fl.Flush()
}
func (f *flushHijackWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	hj := f.basicWriter.ResponseWriter.(http.Hijacker)
	return hj.Hijack()
}
var _ http.Flusher = &flushHijackWriter{}
var _ http.Hijacker = &flushHijackWriter{}
```

and applied them in NewWrapResponseWriter 

```
if fl && hj {
	return &flushHijackWriter{bw}
}
if hj {
	return &hijackWriter{bw}
}
```

i can make a pull request if you want.

**Comment by pkieltyka** [comment]
@bernhardreisenberger https://github.com/go-chi/chi/pull/618 can you try this and lmk?
