### ISSUE TITLE
Multiple HTTP Verbs Matching Methods

### ISSUE THREAD

**Issue by lesichkovm** [go-chi/chi#620]
Can we have something similar to the bellow code (example taken from Laravel's router)

````
Route::match(['get', 'post'], '/', function () {
    //
});

Route::any('/', function () {
    //
});
````

The first matching multiple HTTP verbs, the second matching all HTTP verbs (GET. POST, PUT, DELETE, HEAD)

This will be quite handy for "catch-all" routes

**Comment by pkieltyka** [comment]
Read examples and docs, it’s possible

**Comment by lesichkovm** [comment]
Thank you for replying.

I have checked the documentation multiple times as well as the examples. I also checked the closed issues so far and only HEAD and GET requests were mentioned.

Can you give an example for this?

**Comment by lesichkovm** [comment]
@pkieltyka can you give an example, I could not see it in the documentation or the examples

**Comment by VojtechVitek** [comment]
I think you wanna take a look at `r.Handle(` which is a catchall for all method types and in the body of the handler, you'll want to `switch r.Method { }` explicitly.

**Comment by lesichkovm** [comment]
@VojtechVitek it looks like you are correct. Thank you.
