### ISSUE TITLE
Consider enabling GitHub discussions for go-chi/chi repo

### ISSUE THREAD

**Issue by mfridman** [go-chi/chi#621]
GitHub recently introduced https://docs.github.com/en/discussions. Would you consider adding discussions to go-chi ?

Given most issues (nowadays) are questions, how-tos and general inquiries this might be a good way to separate "code issues" vs everything else.

It's also possible you'd prefer to have everything tracked as Issues and that's totally cool too. Just a suggestion.

**Comment by pkieltyka** [comment]
I think would be great, but I wouldn’t have time to manage it. If you want to help moderate I’m happy to add you as maintainer / owner to set it up.. no pressure / rush

**Comment by mfridman** [comment]
Its worth a try, I've noticed this working quite well in a few other oss repos, e.g., https://github.com/benbjohnson/litestream/discussions

Given the stability of chi, most "issues" coming in are just general support questions.

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/discussions done
