### ISSUE TITLE
A middleware which converts all http.Error calls to JSON

### ISSUE THREAD

**Issue by mitar** [go-chi/chi#622]
I have API implementations which call `http.Error` internally on errors. Is there already some middleware which would be able to wrap text written as error to something like `{"error": <original text>}` JSON? How would one approach implementing such a middleware? It should do the transformation only on errors.

**Comment by pkieltyka** [comment]
sorry, I don't have bandwidth for general support questions

**Comment by VojtechVitek** [comment]
@mitar see https://github.com/go-chi/render
