### ISSUE TITLE
How do I listen for syscall.SIGINT

### ISSUE THREAD

**Issue by myuid** [go-chi/chi#627]
I want to listen for syscall.SIGINT to do some subsequent operations when pressing Ctrl + C. I don't know how to write the corresponding code, could you give me some advice or demo?

**Comment by mfridman** [comment]
@myuid This is less a chi issue as it is a question on how to compose package `main` to listen for interrupts.

There are plenty of examples out there, here are a few: 

https://gobyexample.com/signals
https://medium.com/@pinkudebnath/graceful-shutdown-of-golang-servers-using-context-and-os-signals-cc1fa2c55e97
