### ISSUE TITLE
Customize Context

### ISSUE THREAD

**Issue by tamalsaha** [go-chi/chi#628]
Hello,
Is it possible to customize the chi route Context? 

Thanks.

**Comment by pkieltyka** [comment]
what do you have in mind?

**Comment by tamalsaha** [comment]
Something along the lines of https://echo.labstack.com/guide/context/ . Basically we want to add more stuff to context. (1) One way to do that will be use one key and put everything in the req.Context(). (2) The other way will be to add different objects using different keys in req.Context(). Option 1 seems to be better since it needs fewer allocation. Option 2 can be done without any modification to chi.

**Comment by pkieltyka** [comment]
to do this with chi, you should make a separate AppContext, and set it however you like, and then assign it on the req.Context(). Chi's Context is also present on the req.Context() under a different key, and you shouldn't need to add state to it.
