### ISSUE TITLE
[Suggestion] Clarification in docs about potential docgen error?

### ISSUE THREAD

**Issue by medge-leaflink** [go-chi/chi#630]
I was attempting to follow `https://github.com/go-chi/chi/blob/master/_examples/rest/main.go` for an example to set up DocGen but when calling `api := docgen.JSONRoutesDoc(router)`, it was giving the following error:

```
InvalidIfaceAssign: cannot use router (variable of type *chi.Mux) as chi.Routes value in argument to docgen.JSONRoutesDoc: wrong type for method Match (have func(rctx *github.com
/go-chi/chi.Context, method string, path string) bool, want func(rctx *github.com/go-chi/chi/v5.Context, method string, path string) bool)
```

The reason was that I had the following imports (thanks to my IDE):

```
import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/docgen"
)
```

(missing the v5 import)

Would it be worth calling that out anywhere in the docs / examples? I think it's easy to avoid if you're copy/pasting imports but I was running from scratch and didn't think to check the imports my IDE auto-populated!

**Comment by pkieltyka** [comment]
Yes indeed, this is another problem with Go's enforcement of SIV.. I recommend reporting it to the Go modules team as well.

Good suggestion though, I think go-chi/docgen could use a README with an example there and highlighting the use of /v5
