### ISSUE TITLE
Is there anyway to attach a middleware to a particular route on a router, and not to the router itself?

### ISSUE THREAD

**Issue by darienmiller88** [go-chi/chi#634]
I'm having an issue where I want to rate limit how often users can sign up for a web app on the `/api/users/signup`  route without also rate limiting the `/api/users/signin`  and `/api/users/signout`  routes. How can I do this?

```
func (u *UserController) init(){
        u.Router.Use(httprate.LimitByIP(1, 30 * time.Second)) //This should only work on the signup, but not the other ones.
        u.Router.Post("/signup", u.signup)
        u.Router.Post("/signin", u.signin)
        u.Router.Post("/signout", u.signout)
}

```

**Comment by pkieltyka** [comment]
@dannyvankooten hey there -- yes, you can use `.With()`

`u.Route.With(middlewareJustOnThisEndpoint).Post("/signup", u.signup)`

You may also find `.Group()` interesting. Check the _examples
