### ISSUE TITLE
Adding new keys/value to the log entry with the logging middleware 

### ISSUE THREAD

**Issue by Dmdv** [go-chi/chi#655]
If we are using logging middleware, how possible to add a new key and a value to the log entry?

**The case:**
I've been developing authentication middleware and in the middleware I need to have an access to the http logger and add entries to it

> If we need to pass values between handlers, such as the ID of the authenticated user, or a request or trace ID, we can the use the context.Context attached to the *http.Request via the *Request.Context() method introduced back in Go 1.7.

Does this logging middleware allow for adding key/value to the entries?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/805238/131631736-0e88da4d-bffd-4f7b-a3e2-99e2826bb77f.png">

**Comment by pixelrazor** [comment]
It looks like the logging middleware supports [extension](https://github.com/go-chi/chi/blob/master/middleware/logger.go), so it should be able to support whatever you would like it to

**Comment by pkieltyka** [comment]
See https://github.com/go-chi/chi/blob/master/_examples/logging/main.go and https://github.com/go-chi/httplog
