### ISSUE TITLE
New oAuth 2.0 middleware

### ISSUE THREAD

**Issue by jeffreydwalter** [go-chi/chi#656]
Hi @pkieltyka, I just ported [this](https://github.com/maxzerbini/oauth) gin oAuth 2.0 middleware package to a [go-chi package oAuth 2.0 package](https://github.com/jeffreydwalter/oauth), and am wondering if you'd like me to submit a PR to add it to the middleware collection.

Please have a look and let me know what you think.

**Comment by pkieltyka** [comment]
hey @jeffreydwalter looks good!

I've made a new repo: https://github.com/go-chi/oauth -- can you submit the PR here..?

I read some of your branch code and a few requests as well:
1. https://github.com/jeffreydwalter/oauth/blob/master/go.mod#L6 -- here you are using go-chi v1.5.4 -- please update import paths to /v5, so github.com/go-chi/chi/v5
2. Let's remove dependency on github.com/go-chi/render and instead just add a method called `renderJSON` inside of your package which does the same thing

**Comment by jeffreydwalter** [comment]
Awesome! I made the changes you requested and made a PR here:
https://github.com/go-chi/oauth/pull/1

Cheers!

**Comment by pkieltyka** [comment]
thanks :) merged in other repo
