### ISSUE TITLE
Small typo in comment

### ISSUE THREAD

**Issue by bramvandewalle** [go-chi/chi#662]
I think there is a small typo in a comment [here](https://github.com/go-chi/chi/blob/master/middleware/compress.go#L117-L118).

I think it should be "That's why we prefer gzip over deflate. It's just more reliable and not significantly slower than **deflate**" instead of "That's why we prefer gzip over deflate. It's just more reliable and not significantly slower than **gzip**".

**Comment by Swastyy** [comment]
Hi @bravdwal , have you opened a PR for this or Can I take this up?

**Comment by bravdwal** [comment]
I have not because I couldn't push to the repo (permission denied).

**Comment by Swastyy** [comment]
> I have not because I couldn't push to the repo (permission denied).

Ohh, let me try once.
