### ISSUE TITLE
Misuse of mount results in infinite loop when calling unregistered method

### ISSUE THREAD

**Issue by carmo-evan** [go-chi/chi#663]
When misusing `Mount` like so:

```go
func main() {
	r := chi.NewRouter()
	mux := r.Group(func(r chi.Router) {
		r.Use(middleware.Logger)
		r.Group(func(r chi.Router) {
			r.Get("/products", printPath)
		})
		r.Mount("/", r)
	})
	if err := http.ListenAndServe(":3004", mux); err != nil {
		log.Fatal(err)
	}
}

func printPath(w http.ResponseWriter, r *http.Request) {
	log.Println(r.URL.Path)
}
```

Calling unregistered methods on the /products path (POST /products, PUT /products, etc) results in Chi entering an infinite loop. This could be used maliciously by an attacker. The expectation is that either this should still work as intended, or an error should be thrown.

**Comment by j1cs** [comment]
this happens to me too. there's any advice to avoid this?

**Comment by VojtechVitek** [comment]
technically, we could check for pointer equality in the `Mount()` method and `panic()`

thoughts?

**Comment by pkieltyka** [comment]
I don’t think we should do anything.. you can write an infinite loop in Go easily too

**Comment by j1cs** [comment]
I added a prefix like `/v1`and the loop stopped.
