### ISSUE TITLE
Calling (*T).Fatal() inside a goroutine in mux_test.go

### ISSUE THREAD

**Issue by everton-dk9** [go-chi/chi#668]
In [mux_test.go#L1577](https://github.com/go-chi/chi/blob/df44563f0692b1e677f18220b9be165e481cf51b/mux_test.go#L1577)

```go
func TestMuxContextIsThreadSafe(t *testing.T) {
	router := NewRouter()
	router.Get("/{id}", func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), 1*time.Millisecond)
		defer cancel()

		<-ctx.Done()
	})

	wg := sync.WaitGroup{}

	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := 0; j < 10000; j++ {
				w := httptest.NewRecorder()
				r, err := http.NewRequest("GET", "/ok", nil)
				if err != nil {
					t.Fatal(err) // got a warning here
				}

				ctx, cancel := context.WithCancel(r.Context())
				r = r.WithContext(ctx)

				go func() {
					cancel()
				}()
				router.ServeHTTP(w, r)
			}
		}()
	}
	wg.Wait()
}
```
In VScode I got a warning at line 1577 in mux_test.go. So I start searching for a solution and end up finding some discussions recommending to use `t.Error() return` or `t.Errorf() return` instead of `t.Fatal()`. The method `t.Fatal()` or `t.Fatalf()` should be called from the same goroutine of the Test function.

See minio/minio#6682

**Comment by pkieltyka** [comment]
thanks, fixed in https://github.com/go-chi/chi/commit/ba10645980b4076b0f9a057574457db9bcf6ebd8
