### ISSUE TITLE
How to separate routes into route package?

### ISSUE THREAD

**Issue by bcodus** [go-chi/chi#672]
This should be trivial but I could not separate go-chi routes into a separate package and could not find the answer in the docs. Here is what I tried:

    package route
    
    import (
    	"havgin/app/controller"
    	"net/http"    
    	"github.com/go-chi/chi/v5"
    	"github.com/go-chi/chi/v5/middleware"
    )
    
    func RegisterRoutes() *chi.Router {
    	r := chi.NewRouter()
    	r.Use(middleware.Logger)
     	r.Get("/", controller.HomePaget)
     	r.Get("/latest", controller.GetLatest)
    	return r
    }

And then in `package main`, I'd like to import it like:

    package main
    import (
    	"myapp/app/route"
    	"myapp/config"
    	"net/http"
    )
     
    var conf = config.Config()
    func main() {  
    	r:= route.RegisterRoutes()
    	http.ListenAndServe(conf.Server.ServerPort, r)
    }

But the code does not compile and in vscode I get `could not import myapp/app/route (no required module provides package "myapp/app/route")compiler`

Appreciate your help to resolve this.

**Comment by VojtechVitek** [comment]
Perhaps you have an issue with your import path or go.mod file. This is not a go-chi specific question. Please consult Golang Slack or StackOverflow.
