### ISSUE TITLE
Regex OR not matching correctly

### ISSUE THREAD

**Issue by hacdias** [go-chi/chi#673]
Hi - I was building a router where I need to have yearly, monthly and daily archives where each of the fields can also be "any". To match any, we decided on `x`. Thus, we used the following route regex:

```go
const year = `/{year:x|\d\d\d\d}`
```

It should match either `/x` or `/0000` where `0` is any digit. However, it matches `x\d*` and `\d\d\d\d\d*`.

We couldn't find any examples on the documentations/tests where you use the `or` operator. So I'm not 100% sure if this is a bug or not.

Thanks! Let me know if you need more info.

/cc @jlelse

**Comment by jlelse** [comment]
I found a working regex:

```golang
const year = `/{year:^(x|\d\d\d\d)$}`
```

**Comment by jlelse** [comment]
It's probably *not* a bug. Compare `^x|\d\d\d\d$` and `^(x|\d\d\d\d)$` on https://regex101.com. I don't have enough regexp-knowledge to explain the background though.

**Comment by js-everts** [comment]
The expression `^x|\d\d\d\d$` is somewhat similar to writing `(^x|\d\d\d\d$)`. Notice how the `^` and `$` anchor points are split to either side of the alternation (`|`), while `^(x|\d\d\d\d)$` ensures the anchor points belong to the entire expression.

Or if you want to write the regex without parenthesis then `^x$|^\d\d\d\d$` works
