### ISSUE TITLE
ignore case in path elementes

### ISSUE THREAD

**Issue by vtolstov** [go-chi/chi#674]
i need rarely used option to ignore case of path segments, for example i want to catch /v1/create and /v1/CREATE and /v1/CreAte does it possible to add option to ignore case ?

**Comment by mfridman** [comment]
You could add a "case insensitive" middleware. Middleware functions are called before route matching, so something like this should work for you..

```go
r := chi.NewRouter()
r.Use(func(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		r.URL.Path = strings.ToLower(r.URL.Path)
		next.ServeHTTP(w, r)
	}
	return http.HandlerFunc(fn)
})
r.Get("/v1/create", func(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte(r.URL.Path))
})
```

**Comment by vtolstov** [comment]
yeah, looks good. thanks!
