### ISSUE TITLE
Trailing slash with (*chi.Context).RoutePattern()

### ISSUE THREAD

**Issue by lewislbr** [go-chi/chi#676]
Hi, first of all thanks for Chi, it's so nice.

I noticed that the path reported by RoutePattern sometimes includes a trailing slash. Example:

```go
func main() {
	r := chi.NewRouter()
	r.Use(routeMiddleware)
	r.Route("/foo", func(r chi.Router) {
		r.Route("/bar", func(r chi.Router) {
			r.Get("/", handler)
		})
	})

        http.ListenAndServe(":8080", r)
}

func routeMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.ServeHTTP(w, r)
		path := chi.RouteContext(r.Context()).RoutePattern()

		fmt.Println(path)
	})
}

func handler(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
}
```

Calling `localhost:8080/foo` will print `/foo`.
Calling `localhost:8080/foo/` will print `/foo/`.
Calling `localhost:8080/foo/bar` will print `/foo/bar/`.
Calling `localhost:8080/foo/bar/` will print `/foo/bar//`.

I'm wondering if it'd be worth it to add something like
```go
p = strings.TrimSuffix(p, "//")
p = strings.TrimSuffix(p, "/")
```
in https://github.com/go-chi/chi/blob/d32a83448b5f43e42bc96487c6b0b3667a92a2e4/context.go#L129

**Comment by pkieltyka** [comment]
thanks for the suggestion, I agree this is cleaner.

updated in https://github.com/go-chi/chi/commit/3e5747d1f803ed5fd2324c24fb4e2c767241e8a0
