### ISSUE TITLE
dedupe/deduplicate middleware

### ISSUE THREAD

**Issue by komuw** [go-chi/chi#680]
`chi` does not seem to deduplicate middlewares. I don't know if this is a bug or a feature but it can lead to surprising behaviour. 
Imagine we have a middleware that collects metrics, or does logging

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"

	"github.com/go-chi/chi"
)

func homehandler() http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(""))
	}
	return http.HandlerFunc(fn)
}

func metricsMiddleware(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		// Increment some metric counters and send to our metrics dashboard
		fmt.Println("metricsMiddleware called.")
		next.ServeHTTP(w, r)
	}
	return http.HandlerFunc(fn)
}

func main() {
	r := chi.NewRouter()
	r.Use(metricsMiddleware)  // bug, middleware added thrice.
	r.Use(metricsMiddleware)  // bug, middleware added thrice.
	r.Use(metricsMiddleware)  // bug, middleware added thrice.
	r.Handle("/home", homehandler())

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/home", nil)
	r.ServeHTTP(rec, req)
}
```
```sh
metricsMiddleware called.
metricsMiddleware called.
metricsMiddleware called.
```

Now, our middleware is called thrice and we have triple counted our metrics.   
The fix, would be to remove the bug and not add the middleware twice. But I feel like `chi` could help us here and dedupe middlewares.

**Comment by vtolstov** [comment]
this is possible if all middlewares will have some method like Name() string
and r.Use cast middleware to such interface and check middlewares slice for this name

**Comment by komuw** [comment]
an alternative would be to use `reflect.ValueOf(middleware)` for comparison. Though I don't know if use of reflect is acceptable.

**Comment by vtolstov** [comment]
reflect not useful. for example:

mw1 := NewMetricsMiddleware()
mw2 := NewMetricsMiddleware()

via reflect mw1 and mw2 different, but this is the same middleware

**Comment by komuw** [comment]
> reflect not useful. for example:
> 
> mw1 := NewMetricsMiddleware() mw2 := NewMetricsMiddleware()
> 
> via reflect mw1 and mw2 different, but this is the same middleware

It wouldn't be reflect on `NewMetricsMiddleware()` but on `NewMetricsMiddleware`   
ie, the code https://github.com/go-chi/chi/blob/0316d5a1df8598eceb137f5f77945be56810b564/mux.go#L98-L103 would change to something like;
```go
func (mx *Mux) Use(middlewares ...func(http.Handler) http.Handler) {
	if mx.handler != nil {
		panic("chi: all middlewares must be defined before routes on a mux")
	}
     for mid := range middlewares{
          if !contains(mx.middlewares, mid){
	      mx.middlewares = append(mx.middlewares, mid)
          }
  }
}

func contains(a []func(http.Handler) http.Handler, x func(http.Handler) http.Handler) bool {
	for _, n := range a {
		if reflect.ValueOf(x) == reflect.ValueOf(n) {
			return true
		}
	}
	return false
}
```

But as I said, I'm not sure whether this is a good way to deal with the issue.

**Comment by pkieltyka** [comment]
Out of scope, you’ll have to be more careful

**Comment by VojtechVitek** [comment]
@komuw You might wanna create a wrapper function around your middleware that returns it only for the first time and returns a NOP middleware otherwise.

I don't think this is something that belongs to Chi core either.
