### ISSUE TITLE
Incorrect code snippet for AllowContentType middleware on go-chi.io 

### ISSUE THREAD

**Issue by wisaTong** [go-chi/chi#681]
code snippet for https://go-chi.io/#/pages/middleware?id=allowcontenttype is incorrect
```go
r.Use(middleware.AllowContentEncoding("application/json","text/xml"))
```
should be
```go
r.Use(middleware.AllowContentType("application/json","text/xml"))
```

Just want to contribute :) Love this project

**Comment by pkieltyka** [comment]
Thanks :) we’ll correct

**Comment by pkieltyka** [comment]
thanks :) fixed in https://github.com/go-chi/docs/commit/e283fe72b1d0ae9b6ec574405ee7ac8cb2f7573d
