### ISSUE TITLE
Support debug mode like Gin

### ISSUE THREAD

**Issue by shenghui0779** [go-chi/chi#682]
`gin.SetMode(gin.DebugMode)`

**Comment by mfridman** [comment]
Could you elaborate what are your trying to accomplish?

If you want to log every request, consider a middleware logger ? e.g.,

```
r.Use(middleware.Logger)  
```

https://github.com/go-chi/chi/blob/0316d5a1df8598eceb137f5f77945be56810b564/middleware/logger.go#L35-L43

**Comment by shenghui0779** [comment]
I hope to print the defined routes during initialization.
