### ISSUE TITLE
No error on redeclared routes

### ISSUE THREAD

**Issue by iFrozenPhoenix** [go-chi/chi#687]
Currently it is possible to redeclare a route without throwing an error or warning.
Wouldn't it make sense to throw an error or at least a warning on redeclared routes as the routing becomes unpredictable?

Additions: As I have currently seen there is a check in mux.go line 289. But somehow I get no error.
See code example below

```go
rtr := chi.NewRouter()
rtr.Delete("/user/{id}", middleware.Authenticated(del).ServeHTTP)
rtr.Delete("/user/{id}", del)
```

**Comment by mfridman** [comment]
What you described is intentional, `chi` recognizes the last handler matched and overrides existing handler (this is by design)

This issue might be of interest to you. https://github.com/go-chi/chi/issues/336#issuecomment-411415945

You can "wrap" those routes using `.Route()` .. and this will panic:

```
r := chi.NewRouter()
r.Route("/users", func(r chi.Router) {
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("here1")
	})
})
r.Route("/users", func(r chi.Router) {
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("here2")
	})
})
log.Fatal(http.ListenAndServe("localhost:9091", r))
```

**Output:**

```
panic: chi: attempting to Mount() a handler on an existing path, '/users'
```

**Comment by iFrozenPhoenix** [comment]
I've tried it and it works like in your example. But when the subroutes are added to the resulting router object it doesn't panic.
Wouldn't it be possible to make the NewRouter function an variadic function to initialize with options and let it have an options object with strict mode where all redeclared routes panic?
This approach would also allow further customizations if needed.

**Comment by pkieltyka** [comment]
overriding handlers is allowed by design
