### ISSUE TITLE
docs: example code of AllowContentType has typo

### ISSUE THREAD

**Issue by iyorozuya** [go-chi/chi#689]
In [link](https://go-chi.io/#/pages/middleware?id=allowcontenttype), the example code of AllowContentType has a typo. In place of AllowContentType, AllowContentEncoding is written.

**Comment by pkieltyka** [comment]
thank you -- fixed in https://github.com/go-chi/docs/commit/e283fe72b1d0ae9b6ec574405ee7ac8cb2f7573d
