### ISSUE TITLE
👋 ❤️ Hi, creator of chi, looking to hire passionate/awesome Go developers to join my company :)

### ISSUE THREAD

**Issue by pkieltyka** [go-chi/chi#696]
Hi all,

Chi is used by thousands upon thousands of amazing developers around world. It's been a pleasure to build chi and contribute to it the open source community to help power infrastructure around the world. 

I know there are so many amazing developers that come through this repo and use it in their projects too. 

Aside from creating / working on Chi, I'm also the cofounder + CEO of Horizon Blockchain Games -- https://horizon.io -- we are a blockchain infrastructure company helping power virtual worlds on the Internet. We've built a video game Skyweaver (www.skyweaver.net) and a Web3 wallet+infrastructure stack called Sequence (www.sequence.build). Yes, I'm a CEO who codes, and I love it -- I code a lot, and if you think the Chi source code is clean, you should see the entirety of our product architecture through and through :) Our team is insanely talented too and so diverse (we're 40 people distributed across 13 countries without an office -- we take the open source model of collaboration to our bones).

We're not just a video game company, even though Skyweaver is amazing and players love it (https://twitter.com/search?q=skyweaver&f=live). The catch is, everything on the Internet is a virtual world in our eyes, even github :D We know virtual worlds from games where they originate -- a place where we come together in a digital environment to play, create, converse, share, and identify. I believe most of the Internet is a virtual world -- like twitter, github, reddit, wikipedia, and of course video games.

Horizon is focused on making virtual worlds on the Web, even more real than ever before. Philosophically, we see our digital and physical worlds coming together, blurring the lines, and being ever more tangible. Practically, Web3 is about transforming networks as we know them into full blown digital economies. These economies, powered by Internet-native currencies provides the Internet with new powers to give users more ownership, voice, value-exchange, programmability and community control. What is so cool, is the things that are breeding in the digital worlds, of which ideas we borrowed from the physical world, will go full circle and bleed back into our physical worlds -- aka, Web3 will change the world and make it better. Web3 will make the world more fair, more open, and more efficient.

Horizon is focused on making Web 3.0 fun, accessible, and real for everyone. The protocols and systems of Web3 are still very primitive, and therein lies the great opportunity to make history and contribute to open source systems that we all grew up living in.

For some people, they hear web3/crypto/blockchain and they love it, for others they hear it and think "scam". Haha, yes, so many scams and bullshit projects it makes me roll my eyes and sick to my stomach too -- but I see truth in the architecture to provide systems, worlds and experiences which are greatly to the end-user. It's all about the users, and the idea is to give users more power, voice, ownership and value.

To sum-up Web3 app design: "reciprocate value to your valuable users". It's kinda how Bitcoin works at a fundamental level (even though, I don't own any BTC tbh, I don't see a future for it, because it has very little utility or anything towards what I mentioned above, and as a store-of-value, I think ETH can do all that and so much more -- but I digress). Bitcoin rewards those users who help secure the network -- that is it. Provide value to a network (mining blocks+replicating state), then as that user, you shall also gain value native to that network. This is my philosophy on how Web 3.0 advances the state of the Internet, regardless of the end-state blockchain protocols which manifest as the dominate standard. I do believe this to be Ethereum for many reasons of values, morales, vision, and openness -- but, if I'm wrong, it matters not, it's all an evolution.

Some of you might be thinking, *right on*, Ethereum, *yes*. Others might be thinking, Ethereum? What? it's PoW, bad for the environment, it doesn't scale, it's expensive, etc. Here is what I'll say: 1. PoW is a fantastically clever algorithm but actually leads to less decentralized networks (in comparison to PoS) and definitely a huge waste of energy, agree 2. Vitalik (creator of Ethereum) was the first person in the world to ever speak of the words, PoS (Proof of Stake), so many years ago and after so many years and after all his success he stays laser focused and committed to see through Web3 in the ways I'm describing in a very pure way, and he's to this day, still one of the best researchers in the entire world, and of course he's mega rich, but he does it because he loves it and still one of the hardest working people in the space to this day -- I argue one of the most influential people of our time. 3. Eth 2.0 is PoS and its shipping this year, (so energy problem solved), and it also makes the network even more decentralized 4. Scalability of networks has come extremely far over with so many teams working to solve this problem, and many great teams have done so -- the result is the idea of "Layer2" networks, which are adjacent networks which stay connected to the Ethereum base network (aka Layer1), and even inherit their security from the base chain, it's a fascinating design and its working / happening now. A key to the success however of Ethereum / layer2 networks and all of this stuff, is the user's "Wallet". User's access these Web3 networks through a wallet app which can interface with the protocols of these networks -- aka, a client for the blockchain network and a connector for systems built upon it. This is of course why we have spent 4 years creating https://Sequence.build -- the wallet is the gateway / browser to access these Web3 worlds, and it must be designed with the shape of the network and protocols in mind. 

Finally, from a tech perspective -- this stuff is super fun to build and explore. Ever hear of P2P networks..? distributed systems..? It's like APIs as we know them with Chi, but they are autonomous, they are built-in high availability by design but their organic nature, and they are unstoppable. Distributed networks are like a fabric that lives on it's own. Just look at Bittorrent and how powerful so many peers, sharing bits can make distribution of content so damn efficient -- it's beautiful. To sum up the tech architecture of a Web3 system or blockchain: 1. P2P networking where anyone can operate a server/node 2. Cryptography which ensures signed-state updates to a database 3. Economic design of the system which are the actual thing which provides security 4. A public good / protocol which is autonomous and runs on its own, is extensible by its community and is composable by other apps on the network. Btw, yea, isn't it cool that the part which brings security to the network is the economics. 

---

Finally, if this resonates with you, please send me an email at pk@horizon.io -- come write some amazing Go with us and join us our journey to make Web 3.0 real, fun and fair for citizens of the Internet. More info: https://horizon.io/careers

We're also hiring React.js developers.

thanks for reading,
-Peter

**Comment by wojtekwtf** [comment]
i met peter and absolutely love the games horizon is building — anybody interested should chat with him!

**Comment by mewwts** [comment]
Peter is an amazing individual and you should work for him.

**Comment by avdb13** [comment]
Hey Peter, pretty cool projects you have! Big fan of cryptography but my technical knowledge of it is still lacking. Not a fan of web3 hype either but these seem like projects with potential. Good luck with hiring!

**Comment by pkieltyka** [comment]
thank you @avdb13 -- I appreciate that, and agree tons of hypey projects, but also lots of truth to the primitives of web3

**Comment by simonepelosi** [comment]
Hey @pkieltyka pretty cool project! I'm interested!
