### ISSUE TITLE
heartbeat middleware response

### ISSUE THREAD

**Issue by mahmud2011** [go-chi/chi#697]
https://github.com/go-chi/chi/blob/master/middleware/heartbeat.go#L18

`w.Write([]byte("."))`

Is there any specific reason for the `.` as response? It's hard to notice at first glance.

May be something like this would be more readable from client.

`w.Write([]byte(http.StatusText(http.StatusOK)))`

**Comment by pkieltyka** [comment]
It’s just helpful to see some body instead of empty body as might have some other error through the request flow
