### ISSUE TITLE
Why name it `URLParam()`?

### ISSUE THREAD

**Issue by mpuels** [go-chi/chi#703]
It seems as if the world has agreed on that a "URL parameter" is this

```
https://www.foo.io/path?param=value
```

Chi on the other hand says "no, no, you're all wrong, a URL parameter is this":

```
https://www.foo.io/{param}
```

I'm just curious about that naming decision in Chi.

# Chi

![Screenshot from 2022-02-02 12-42-32](https://user-images.githubusercontent.com/2924816/152147287-ecea7417-c6ba-4cb1-bee5-9b4d803b3140.png)
https://github.com/go-chi/chi#url-parameters

# World

![Screenshot from 2022-02-02 12-33-58](https://user-images.githubusercontent.com/2924816/152146166-aa255c82-a592-4532-9238-f94fcdac1725.png)
https://www.botify.com/learn/basics/what-are-url-parameters

---

![Screenshot from 2022-02-02 12-30-49](https://user-images.githubusercontent.com/2924816/152145738-8bdb65d7-7bce-40e5-8e68-1aa301e529b2.png)
https://swagger.io/docs/specification/describing-parameters/

---

![Screenshot from 2022-02-02 12-34-41](https://user-images.githubusercontent.com/2924816/152146260-bddf4876-fb21-4207-bc79-a5d0afb3f701.png)
https://support.google.com/google-ads/answer/6277564?hl=en

---

![Screenshot from 2022-02-02 12-36-26](https://user-images.githubusercontent.com/2924816/152146502-4e8e4019-adb9-4ad5-acd2-27dd218a4b05.png)
https://www.semrush.com/blog/url-parameters/

---

![Screenshot from 2022-02-02 12-38-27](https://user-images.githubusercontent.com/2924816/152146769-168a7006-bea1-4983-a349-684246d27612.png)
https://support.clickmeter.com/hc/en-us/articles/211032666-URL-parameters-How-to-pass-it-to-the-destination-URL

**Comment by obtusedev** [comment]
@mpuels 
> It seems as if the world has agreed on that a "URL parameter" is this
> ```https://www.foo.io/path?param=value```

This is a **url query parameter**
Where you would use `r.URL.Query.Get("param")` to get the value.

>Chi on the other hand says "no, no, you're all wrong, a URL parameter is this":
> ```https://www.foo.io/{param}```

This is a **url path parameter**
Where you would use `chi.URLParam(r, "param")` to get the value.

>https://swagger.io/docs/specification/describing-parameters/

This resource you linked shows the different types of parameters.
I suppose they all fall under the general category of url parameters.

See this for more clarification: https://stackoverflow.com/questions/59639450/go-chi-router-with-url-parameters-and-mysql-db-not-working-properly#answers-header

**Comment by mpuels** [comment]
Thanks for your answer!

Yes, after reading chi's docs I understood what `URLParam()` means.

Let me briefly tell you why I opened this issue regarding the name of `URLParam()`.

At work I read an internal's project source code that uses chi. I saw a statement that uses `URLParam()`. Since I wasn't certain what that function does, I googled for "URL parameter". The search results suggested that "URL parameter" means "URL query  parameter". Assuming that "URL parameter" means "URL query parameter", the code in the internal's project didn't make much sense to me.

Now I know that `URLParam()` actually reads a URL path parameter:

|             | Google results consensus (query string param)    | chi (path param)                      |
|-------------|--------------------------------------------------|---------------------------------------|
| "URL Param" | `https://www.foo.io/path?queryStringParam=value` | `https://www.foo.io/users/{pathParam}`|

Maybe in the next version (`v6`?) of chi you can replace `URLParam()` with `URLPathParam()` :slightly_smiling_face:

**Comment by jawnsy** [comment]
If changing this is desirable, then I think it's also possible to do this in a backward-compatible way by:

1. Introducing the new `URLPathParam` function
2. Changing `URLParam` to call `URLPathParam`
3. Marking the `URLParam` function as deprecated, in favor of `URLPathParam`

This makes it easier for people to upgrade, since they can do so gradually and do not have to fix a breaking change on upgrade

**Comment by pkieltyka** [comment]
Url params and query params are different things. The method name isn’t going to change.
