### ISSUE TITLE
431 too large headers size?

### ISSUE THREAD

**Issue by ibrahimjelliti** [go-chi/chi#704]
hello,

I am using go chi in my golang backend. I am facing an error of too large request size here(21608 bytes in headers size).
I am not sure if this is an exception from go-chi as of exceeding the headers size limit here? any advice here?
thanks,

**Comment by obtusedev** [comment]
From the go documentation: https://pkg.go.dev/net/http
```go
const DefaultMaxHeaderBytes = 1 << 20 // 1 MB
```
DefaultMaxHeaderBytes is the maximum permitted size of the headers in an HTTP request. This can be overridden by setting Server.MaxHeaderBytes.

Maybe see if changing that will help.

**Comment by pkieltyka** [comment]
This isn’t chi related, closing
