### ISSUE TITLE
File serving from a different url wont work when serving from sub router

### ISSUE THREAD

**Issue by phxgbl** [go-chi/chi#706]
[Official](https://github.com/go-chi/chi/tree/master/_examples/fileserver) example works fine with all paths and URLs. but when the same is moved to sub router, it will show
![Screenshot from 2022-02-15 18-15-41](https://user-images.githubusercontent.com/37118923/154064819-a95d4a07-7a59-44b7-b8fd-8513025eb24d.png)
 file not found
```
	workDir, _   = os.Getwd()
	filesDir     = http.Dir(filepath.Join(workDir, "static/html"))
r.Route("/org/{org_id}/app/{app_id}", func(router chi.Router) {
	router.Get("/*", func(w http.ResponseWriter, r *http.Request) {
		rctx := chi.RouteContext(r.Context())
		pathPrefix := strings.TrimSuffix(rctx.RoutePattern(), "/*")
		fs := http.StripPrefix(pathPrefix, http.FileServer(filesDir))
		fs.ServeHTTP(w, r)
	})
```

})

**Comment by pkieltyka** [comment]
hi, this isn't a chi bug, sorry cannot offer support for this one
