### ISSUE TITLE
Unused extra param of the logger middleware

### ISSUE THREAD

**Issue by ventsislav-georgiev** [go-chi/chi#707]
Since it is part of the LogEntry interface shouldn't it be written to the logger buffer as the rest of the params?
See: 
https://github.com/go-chi/chi/blob/c97bc988430d623a14f50b7019fb40529036a35a/middleware/logger.go#L72
https://github.com/go-chi/chi/blob/c97bc988430d623a14f50b7019fb40529036a35a/middleware/logger.go#L136

**Comment by pkieltyka** [comment]
extra is pretty optional but used for extending the logger for other implementations against the interface. You can pass nil if you dont need it
