### ISSUE TITLE
RFC Add r.Redirect(pattern, url, code)

### ISSUE THREAD

**Issue by JRaspass** [go-chi/chi#709]
Happy to do the code but wanted to see if there was any buy in first.

We could add:
```go
r.Redirect("/foo", "/bar", http.StatusPermanentRedirect)
```
As syntax sugar for
```go
r.Handle("/foo", http.RedirectHandler("/bar", http.StatusPermanentRedirect))
```
Or we could go one step further and make the feature worth it by allowing URL params to match across:
```go
r.Redirect("/foo/{baz}", "/bar/{baz}", http.StatusPermanentRedirect)
```
As syntax sugar for
```go
r.HandleFunc("/foo/{baz}", func(w http.ResponseWriter, r *http.Request) {
	http.Redirect(w, r, "/bar/" + chi.URLParam(r, "baz"), http.StatusPermanentRedirect)
})
```
What do people think?

**Comment by mfridman** [comment]
If it's just syntax sugar I don't think it adds much value, but I like the second example where the params matched across.

**Comment by pkieltyka** [comment]
chi is intended to be kept pretty minimal. thank you for the suggestion but will pass at this time

**Comment by shamilovstas** [comment]
I'm not sure whether my question relates to the initial question, but perhaps it makes sense when subrouters are used? Consider this:
```
router.Route("/{username}", func(r chi.Router) {
	r.Get("/", func(w http.ResponseWriter, request *http.Request) {
		// r.Redirect("/details")  <---- This is where I want to redirect to, keeping the subrouter's prefix (/{username}).
	})

	r.Get("/details", func(writer http.ResponseWriter, request *http.Request) {
		// ...                     <---- Redirects here
	})
}
