### ISSUE TITLE
feat: HTTP cache implementation as middleware.

### ISSUE THREAD

**Issue by darkweak** [go-chi/chi#715]
An HTTP cache system would be great in chi to avoid the execution of unchanged response.

I can implement [Souin](https://github.com/darkweak/souin) as the HTTP cache middleware. With that it will support the CDN validation/invalidation too, set default cache-control header, store in a distributed system using olric or in memory with badger. 

It's already available as Træfik/Tyk plugin, skipper/gin/echo middleware, and is used in the official caddy cache-handler.

Cheers ✌️

**Comment by pkieltyka** [comment]
Sounds great :) do it up. One caveat: please do not introduce any new pkg deps

**Comment by darkweak** [comment]
I won't add a new pkg dep because it will be a third party middleware and we could refer it in the documentation. The users could add the HTTP cache support with the `github.com/darkweak/souin/plugins/chi` dep. With that people they don't want a cache system support wont be affected. That's simpler than recode everything in chi IMHO. WDYT about that?

**Comment by darkweak** [comment]
Can you check the Chi support @pkieltyka ? If it looks good to you I could add this inside the go-chi documentation. At least it can offer the HTTP caching feature as a 3rd part middleware.

Open to discuss about that. ✌️

**Comment by pkieltyka** [comment]
gotcha, I think for now I'll skip this, but thanks for bringing it to my attention. In the future I'll likely do a deeper dive here
