### ISSUE TITLE
Support NO_COLOR

### ISSUE THREAD

**Issue by jolheiser** [go-chi/chi#724]
Would you be open to a simple `os.LookupEnv` for `middleware.Logger` default that supports [NO_COLOR](https://no-color.org/)?
I'd be happy to send in a PR if so.

**Comment by pkieltyka** [comment]
I think that makes sense as well, feel free to submit PR

**Comment by pkieltyka** [comment]
going to close this, as prefer to keep environment variables out of it. I recommend you just make your own middleware logger pkg
