### ISSUE TITLE
brotli compression

### ISSUE THREAD

**Issue by SirMetathyst** [go-chi/chi#730]
I've seen that https://github.com/go-chi/chi/pull/326 has merged brotli compression in but I can't seem to find it, seems to be removed? Why was that the case? Any chance at revisiting the decision to bring brotli compression to the compress middleware?

**Comment by js-everts** [comment]
You can hook up any compression algorithm you like using the `SetEncoder` method. See https://pkg.go.dev/github.com/go-chi/chi/middleware#Compressor.SetEncoder
