### ISSUE TITLE
Chi does not handle "GET /" when configured with `Post("/")` + `NotFound()`

### ISSUE THREAD

**Issue by 0uep** [go-chi/chi#738]
When I configure my routes as the following:

```go
handler := chi.NewRouter()
handler.Post("/", post)    // POST / calls post()
handler.NotFound(notFound) // Other requests call notFound()

server := http.Server{
	Addr:    ":22000",
	Handler: handler,
}
```

the GET request on "/" does not trigger the `notFound()` function.

I would expect the `notFound()` function must be called for any request except "POST /".

## Test it

Please see a real example:
https://github.com/teal-finance/garcon/tree/v0.19.0/examples/post-notfound

Please run it as the following and open http://localhost:22000

    go run github.com/teal-finance/garcon/examples/post-notfound@v0.19.0 -post-endpoint /

=> the browser displays an empty page

Then try with another endpoint for the POST method and refresh http://localhost:22000

    go run github.com/teal-finance/garcon/examples/post-notfound@v0.19.0 -post-endpoint /foo

=> the browser displays *handler.NotFound()*

## My output
    
    > go run github.com/teal-finance/garcon/examples/post-notfound@v0.19.0 -post-endpoint /
    go: downloading github.com/teal-finance/garcon v0.19.0
    2022/07/09 17:12:28 Middleware logger: requester IP, requested URL and duration
    2022/07/09 17:12:28 Middleware logger: requester IP and requested URL
    2022/07/09 17:12:28 Server listening on http://localhost:22000
    2022/07/09 17:12:41 in  127.0.0.1:48728 GET /
    2022/07/09 17:12:41 out 127.0.0.1:48728 GET / 6.49µs
    
    [Ctrl+C]
    
    > go run github.com/teal-finance/garcon/examples/post-notfound@v0.19.0 -post-endpoint /foo
    2022/07/09 17:12:51 Middleware logger: requester IP, requested URL and duration
    2022/07/09 17:12:51 Middleware logger: requester IP and requested URL
    2022/07/09 17:12:51 Server listening on http://localhost:22000
    2022/07/09 17:12:57 in  127.0.0.1:46626 GET /
    2022/07/09 17:12:57 handler.NotFound()
    2022/07/09 17:12:57 out 127.0.0.1:46626 GET / 9.99µs
    2022/07/09 17:12:57 in  127.0.0.1:46626 GET /favicon.ico
    2022/07/09 17:12:57 handler.NotFound()
    2022/07/09 17:12:57 out 127.0.0.1:46626 GET /favicon.ico 14.85µs

**Comment by js-everts** [comment]
This is correct behavior. If you want to treat routes with undefined methods as not found, then you need to add `handler.MethodNotAllowed(notFound)`.

See https://pkg.go.dev/github.com/go-chi/chi/v5#Mux.MethodNotAllowed

**Comment by 0uep** [comment]
## Thank you very much @js-everts :+1:
I have updated/renamed the example: https://github.com/teal-finance/garcon/blob/main/examples/chi
