### ISSUE TITLE
wildcard '*' must be the last value in a route

### ISSUE THREAD

**Issue by aep** [go-chi/chi#741]
according to https://pkg.go.dev/github.com/go-chi/chi

```
Examples:

"/page/*" matches "/page/intro/latest"
"/page/*/index" also matches "/page/intro/latest"
```

however, that's not actually allowed.
**so presumably the docs are wrong?**

unfortunately i need to match

   -  /page/foo/bar/baz/json
   -  /page/derp/json

as different routes.

**Comment by aniaan** [comment]
/page/{other}/index

**Comment by pkieltyka** [comment]
thanks, I can see why thats confusing. I've updated it in the comment
