### ISSUE TITLE
CORS not working if only middleware is used.

### ISSUE THREAD

**Issue by LeanderGangso** [go-chi/chi#742]
CORS does not work unless at least one endpoint is created.
If I only use a middleware, the CORS will not work on any of the middleware routes.

Example:
```go
func main() {
    r := chi.NewRouter()

    // CORS
    r.Use(cors.Handler(cors.Options{
        AllowedOrigins: []string{"http://localhost:5000"},
        AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
        AllowCredentials: true,
    }))

    // Add Middleware
    r.Use(my.Middleware)

    // Need this to make it work (just any endpoint)
    //r.Get("/hello", func(w http.ResponseWriter, r *http.Request)
    //    w.Write([]byte("world"))
    //})

    // start server
    http.ListenAndServe(":3000", r)
}
```

Don't know if this is a bug or intended, just wanted to let you guys know.

**Comment by Kidsan** [comment]
Looks like it is by design to me. `r.Use` is simply appending the middleware fn to a slice of middlewares. When you call `r.Get`, it calls `mx.handle` internally which applies middlewares according to their position in that slice.

**Comment by pkieltyka** [comment]
Yes you need at leave one endpoint defined
