### ISSUE TITLE
405 Method Not Allowed, while redirecting to another page

### ISSUE THREAD

**Issue by HarryChopra** [go-chi/chi#748]
Hello,

This is a strange problem and appreciate your help with this.

I have a route:
```go
router := chi.NewRouter()
router.Post("/article/create", createArticle)
```
Calling a handler:
```go
func createArticle(w http.ResponseWriter, r *http.Request) {

	// Placeholder to Insert a row in the db and obtain the "id"

	http.Redirect(w, r, fmt.Sprintf("/article/%d", id), http.StatusSeeOther)
}
```
Expected to return:
```
$ curl -iLX POST http://localhost:8080/article/create
HTTP/1.1 303 See Other
Location: /article/view?id=4
Content-Length: 0

HTTP/1.1 200 OK
Content-Length: 40
```
But instead I get: (**The Problem**)
```
$ curl -iLX POST http://localhost:8080/article/create
HTTP/1.1 303 See Other
Location: /article/view?id=5
Content-Length: 0

HTTP/1.1 405 Method Not Allowed
Content-Length: 0
```

**Steps I have taken to investigate:**

1. Modified the handler to:
```go
func createArticle(w http.ResponseWriter, r *http.Request) {

	// Placeholder to Insert a row in the db and obtain the "id"

	fmt.Fprintf(w, "created article id: %d", id)
}
```

   To return:
```
$ curl -iX POST http://localhost:8080/article/create

HTTP/1.1 200 OK
Content-Length: 40

created article id: 6    
```

2. I changed the router to net/http servemux (with the original handler) and I get the expected response.

What do think is causing Chi to respond like this? (I'm using `github.com/go-chi/chi/v5`)
Again, Thanks your for your help!

**Comment by js-everts** [comment]
I assume you already have a route defined for `GET /article/view`.

Anyway, `curl` will always use the request method specified with the `-X` flag for all requests, even when following 303 redirects. You can remove the `-X POST` and try to invoke curl with `-d "some data"`. Also use the `-v` flag to make sure curl is changing the request method when following the 303 redirect.

```
curl -vLd "articledata" http://localhost:8080/article/create
```

**Comment by HarryChopra** [comment]
> `curl` will always use the request method specified with the `-X` flag for all requests

Gosh, I didn't know that. I also added a logger to confirm this:

```
$ curl -iX POST http://localhost:8080/article/create

HTTP/1.1 POST /article
HTTP/1.1 POST /article/10


$ curl -vL http://localhost:8080/article/create

HTTP/1.1 POST /article
HTTP/1.1 GET /article/11
```

Thank you for your help!
