### ISSUE TITLE
[QUESTION] - Why Form doesn't work after ParseForm?

### ISSUE THREAD

**Issue by sujit-baniya** [go-chi/chi#756]
I'm using following code for Form Post request but it doesn't seem to work after `ParseForm`

```go
package main

import (
	"fmt"
	"github.com/go-chi/chi/v5"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Recoverer)

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hello world"))
	})

	r.Post("/html", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(r.Form == nil) // true
		fmt.Println(r.PostForm == nil) // true
		fmt.Println(r.Form) // map[]
		fmt.Println(r.PostForm) // map[]
		r.ParseForm()
		fmt.Println(r.Form == nil) // false
		fmt.Println(r.PostForm == nil) // false
		fmt.Println(r.Form) // map[]
		fmt.Println(r.PostForm) // map[]
		w.Header().Set("Content-Type", "text/html")
		w.Write([]byte("<h2>hello world</h2>"))
	})

	http.ListenAndServe(":3333", r)
}
```
Screenshot:

![image](https://user-images.githubusercontent.com/4959215/194074104-ec7ee875-0caf-4ef7-84bc-d2fedc96d749.png)

**Comment by gbarnovi** [comment]
Hello @sujit-baniya 

> For other HTTP methods, or when the Content-Type is not application/x-www-form-urlencoded, the request Body is not read, and r.PostForm is initialized to a non-nil, empty value.
https://pkg.go.dev/net/http#Request.ParseForm


In your case, you are sending multipart/form-data so request should be parsed with **ParseMultipartForm**
https://pkg.go.dev/net/http#Request.ParseMultipartForm
