### ISSUE TITLE
Printing name of a middleware in Walk function

### ISSUE THREAD

**Issue by bentcoder** [go-chi/chi#759]
Hi,

Is there a way of printing the name of the middleware?

Thanks

Assume I used `r.Use(middleware.UsersCreate)` and the Walk would print `middleware.UsersCreate`.

```go
chi.Walk(r.handler, func(method string, route string, handler http.Handler, middlewares ...func(http.Handler) http.Handler) error {
	// ..

	for _, mid := range middlewares {
		// print mid name
	}

	return nil
})
```

**Comment by VojtechVitek** [comment]
`info := chi.GetFuncInfo(mw)`

**Comment by bentcoder** [comment]
Thank you @VojtechVitek but in the meanwhile I worked it out without importing a new package into dependency.

```go
func name(middleware func(http.Handler) http.Handler) string {
	parts := strings.Split((runtime.FuncForPC(reflect.ValueOf(middleware).Pointer()).Name()), "/")

	return parts[len(parts)-1]
}
```

**Comment by bentcoder** [comment]
Just realised both won't work. https://github.com/go-chi/docgen/issues/23
