### ISSUE TITLE
update _examples/logging to use new "slog"

### ISSUE THREAD

**Issue by pkieltyka** [go-chi/chi#761]
Go 1.20 will ship with new "slog" package. We can use it now via "golang.org/x/exp/slog"

Let's upgrade https://github.com/go-chi/chi/blob/master/_examples/logging/main.go to use it instead

**Comment by ydarb** [comment]
@pkieltyka Please assign me to this, I've created a PR for it

**Comment by pkieltyka** [comment]
thank you to @ydarb for their awesome PR and contribution to close out this issue
