### ISSUE TITLE
Removing Route Dynamically

### ISSUE THREAD

**Issue by BubbaJoe** [go-chi/chi#765]
Hello ,

I want to use chi for my project. However, it doesn't support (like most routers) removing a route/handler dynamically.

Any idea how i can create a `note.removeHandler(method, path string)` without causing some memory leak or segmentation violation.

**Comment by vtolstov** [comment]
I'm write swap router, this is struct that implement http.Handler
inside it i'm use mutex lock to get chi router and serve request.

**Comment by pkieltyka** [comment]
What’s the use case for removing a route?

**Comment by BubbaJoe** [comment]
THanks @pkieltyka 

@pkieltyka 
Im creating an api-gateway (dynamic reverse proxy), and i want to dynamically add and remove routes via another API, while also supporting modern routing patterns like: `/api/*` and `/api/{id:^[0-9]{7}$}`. chi is really lightweight, scalable routing and MIT licenses. So i think it's a perfect fit if i can figure out how to remove routes dynamically without any bugs or issues.

**Comment by pkieltyka** [comment]
Gotcha. So chi won’t support removing routes dynamically. But you can use the wildcard operator and can probably find a way to mount a sub router on top of an existing route. Or use a middleware and handle the routing on the wildcard.

**Comment by BubbaJoe** [comment]
Sure i don't expect chi to support this, i am just curious how i one would create this function.

**Comment by BubbaJoe** [comment]
Ah i see what you mean now. Let me try this.
