### ISSUE TITLE
Question: CONNECT method handling in Chi?

### ISSUE THREAD

**Issue by elevran** [go-chi/chi#768]
According to the [HTTP RFC](https://httpwg.org/specs/rfc9110.html#CONNECT):
```
CONNECT uses a special form of request target, unique to this method, consisting of only the host and port number of the tunnel destination, separated by a colon.
```

I could have misunderstood, but this seems to imply that there is no `Path` element present after the Go HTTP Stack has parsed the incoming request. However, registering a CONNECT handler requires a pattern argument and will panic if non is given or is empty. The lack of `Path` element also seems to suggest that CONNECT is a global, and not per route, handler for a server.

1. Is my reading of the specification reasonable? If so, should `mux.Connect` be moved to a global handler (similar to NotFound, etc.)?
2. Otherwise - what should the pattern set in `mux.Connect()` be set to?
3. Is there an example showing standard Go client and server handling a CONNECT method through Chi?

Thanks!

**Comment by pkieltyka** [comment]
hi there,

try to use:

```go
mux.Connect("/", handler)
```

or

```go
mux.Connect("/*", handler)
```
