### ISSUE TITLE
Exclude certain routes or patterns from logger middleware

### ISSUE THREAD

**Issue by benc-uk** [go-chi/chi#777]
It's pretty common to want some routes not included in the logging, an obvious example is a health check when being used by a load balancer or other probe, or a Prometheus metrics endpoint - generates thousands of lines unnecessary output & logging.
In addition there might be certain patterns like email address which accidentally get logged and leak PII

I wanted to use the logging middleware but also exclude some routes, however I can find no way to do this without providing my own full implementation of the `LogFormatter` interface.

Ideally an array of RegEx patterns could be configured for logging exclusion, which are applied to the URI of the requests

**Comment by VojtechVitek** [comment]
> It's pretty common to want some routes not included in the logging, an obvious example is a health check when being used by a load balancer or other probe, or a Prometheus metrics endpoint - generates thousands of lines unnecessary output & logging.

You could create a Health middleware (responding to `/health` or `/ping`) and mount it before the Logger middleware to avoid unnecessary log lines.

> In addition there might be certain patterns like email address which accidentally get logged and leak PII
> 
> I wanted to use the logging middleware but also exclude some routes, however I can find no way to do this without providing my own full implementation of the LogFormatter interface.
> 
> Ideally an array of RegEx patterns could be configured for logging exclusion, which are applied to the URI of the requests

I think providing the LogFormatter implementation (or writing your own RequestLogger middleware) is the right approach here.

Imho, RegEx matching (of `r.Host`, `r.URL.Path`, `r.URL.Query()` params etc.) is not likely to be added to the chi core library.

**Comment by ack3rs** [comment]
I create a custom middleware to exclude the Prometheus end points based on the health check code.  

`package web

import (
    "net/http"
    "strings"
    
    "github.com/prometheus/client_golang/prometheus/promhttp"
)

func ExcludePrometheus(endpoint string) func(http.Handler) http.Handler {
    f := func(h http.Handler) http.Handler {
        fn := func(w http.ResponseWriter, r *http.Request) {
            if (r.Method == "GET" || r.Method == "HEAD") && strings.EqualFold(r.URL.Path, endpoint) {
                promhttp.Handler().ServeHTTP(w, r)
                return
            }
            h.ServeHTTP(w, r)
        }
        return http.HandlerFunc(fn)
    }
    return f
}`

Then added with.. 

`    
R.Use(web.ExcludePrometheus("/metrics"))
`

**Comment by pkieltyka** [comment]
try `r.Use(httplog.RequestLogger(s.Log, []string{"/", "/ping", "/status", "/favicon.ico"}))`

see https://github.com/go-chi/httplog

**Comment by xrff** [comment]
write a custom middleware that just determines the 'URL.Path' and skips the log printing if it hits:
(写一个自定义Middleware，只需要判断URL.Path，如果命中则跳过日志打印。)

func SkipLoggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/health" {
			next.ServeHTTP(w, r)
			return
		}
		middleware.Logger(next).ServeHTTP(w, r)
	})
}

then set '	r.Use(SkipLoggingMiddleware)'
(使用自定义Middleware)

r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("OK"))
})
