### ISSUE TITLE
Middlewares doesn't work as expected if endpoint is same

### ISSUE THREAD

**Issue by esenmx** [go-chi/chi#783]
Hi, is this a expected behavior?

I know there are other ways to achieve that behavior but may be this is overlooked and I wanted to report.

Thanks for this package btw, great work!

```go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"log"
	"net/http"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.Logger)

	// this should not print 'foo'
	r.Get("/foo", func(w http.ResponseWriter, r *http.Request) {})

	r.Route("/foo", func(r chi.Router) {
                // printer middleware, should not work for 'GET' request
		r.Use(func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				log.Println("foo")
				next.ServeHTTP(w, r)
			})
		})
		r.Post("/", func(w http.ResponseWriter, r *http.Request) {})
	})

	log.Fatal(http.ListenAndServe("localhost:8080", r))
}
```

>2023/01/16 14:42:21 foo
2023/01/16 14:42:21 "GET http://localhost:8080/foo HTTP/1.1" from 127.0.0.1:51177 - 405 0B in 221.291µs
2023/01/16 14:42:38 foo
2023/01/16 14:42:38 "POST http://localhost:8080/foo HTTP/1.1" from 127.0.0.1:51227 - 000 0B in 34.375µs

**Comment by fahimbagar** [comment]
@esenmx, maybe intended is not the right word, but the middleware starts to work when it found `/foo` as a path prefix. Since the `GET` handler also has that path, it would get the same treatment.

If you want to use middleware only for the sub router, you may add a trailing slash for the sub router. Not sure if this is a norm though.
```
r.Route("/foo/", func(r chi.Router) {
