### ISSUE TITLE
[question] Setting description/name to routes

### ISSUE THREAD

**Issue by bentcoder** [go-chi/chi#797]
Hi,

I looked but couldn't find anything already in place, maybe I missed but is there a way to set description/name to each routes?

Thanks

```go
r.Route("/something" ...).Description/or/Name("It does something")
r.Delete("/another"...).Description/or/Name("It deletes something")
r.MethodFunc("PATCH", "/user" ...).Description/or/Name("It updates something")
```

**Comment by vtolstov** [comment]
You can do this by yourself take a look into this https://github.com/go-chi/chi/blob/master/middleware/value.go for example
