### ISSUE TITLE
Single method that cached several verbs

### ISSUE THREAD

**Issue by lesichkovm** [go-chi/chi#803]
Want to have a single method that catches POST and GET. 

Looks like Handle can do it but there is no documentation neither on the website or in the examaples, or in the code

Currently I just put separate Get("/blabla") and Post("/blabla") eerywhere and it looks unwieldy

**Comment by VojtechVitek** [comment]
`mux.Handle("/blabla", yourHandler)`

You will want to switch on `r.Method` in `yourHandler` func.

Please use discussions instead of submitting an issue for general questions :)
