### ISSUE TITLE
Group does not create a fresh middleware stack

### ISSUE THREAD

**Issue by fspaniol** [go-chi/chi#824]
According to the documentation, the `Group` function should create a fresh middleware stack.

From the Router interface:
```go
// Group adds a new inline-Router along the current routing
// path, with a fresh middleware stack for the inline-Router.
```

From the Mux struct:
```go
// Group creates a new inline-Mux with a fresh middleware stack. It's useful
// for a group of handlers along the same routing path that use an additional
// set of middlewares. See _examples/.
```

However, while testing out the httplog middleware, I noticed that my requests were being logged even if I were in a new group. I have managed to drill it down to this small example:

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/httplog"
)

func main() {
	// Logger
	logger := httplog.NewLogger("httplog-example", httplog.Options{
		JSON: false,
	})

	// Service
	r := chi.NewRouter()
	r.Use(httplog.RequestLogger(logger))

	r.Group(func(r chi.Router) {
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("hello world"))
		})
	})

	http.ListenAndServe(":5555", r)
}

```

When calling `localhost:5555/`, you'll see that the httplog middleware is actually invoked.

What is the actual wanted behavior here?

**Comment by kubosuke** [comment]
Hi @fspaniol  I think it's expected behavior,

as described above,

```
// Group creates a new inline-Mux with a fresh middleware stack. It's useful
// for a group of handlers along the same routing path that use an additional
// set of middlewares. See _examples/.
```

Group() can be used when you want to use an "additional" set of middleware. previous scope middleware information will be inherited.

here is an example,
https://github.com/kubosuke/chi/blob/master/_examples/limits/main.go

**Comment by fspaniol** [comment]
I guess it's an English interpretation issue then `fresh middleware stack` would lead me to believe that it would not inherit the parent's Mux stack. Maybe this could be better worded?

**Comment by kubosuke** [comment]
better to remove  "with a fresh middleware stack" ?

**Comment by fspaniol** [comment]
That could be. Or maybe explicitly mention that it should `create a dedicated middleware stack inhereting the parent's mux ones`. Of course there can be a better wording for this 😄

**Comment by mfridman** [comment]
@VojtechVitek this issue comes up a lot, and I've seen it cause confusion elsewhere. 

Do you know if it was ever considered adding a `GroupDetached` method that adds "a new inline-Mux with a fresh middleware stack" that does not inherit middlewares from the parent?

I think having both `Group` and `GroupDetached` would solve a lot of the confusion, and it would also simplify code where one needs to reach for the latter?

**Comment by pkieltyka** [comment]
yea, perhaps the "fresh middleware stack" is the wrong terminology, agree that should be changed and instead stated as "an inline middleware stack is created,..." 

thanks for the heads up all
