### ISSUE TITLE
Can I pass *template.Template in context (middleware)?

### ISSUE THREAD

**Issue by mahesh-riddles** [go-chi/chi#836]
```
func ParseTemplates(next http.Handler) http.Handler {

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t, _ := template.ParseGlob("./static_files/templates/*.html")
		ctx := context.WithValue(r.Context(), "template", t)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

```
ctx := r.Context()
	t, ok := ctx.Value("template").(*template.Template)
	if !ok {
		http.Error(w, http.StatusText(http.StatusInternalServerError), 500)
		return
	}
```

It is always http.Error
Why am I not able to get back the template reference?
I tried to send a string. That works ..

I tried to implement that template directly in the handler function, it is working.
When I try to use the middleware, it is failing.

**Comment by VojtechVitek** [comment]
Yes, you can. See https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L146

Perhaps you mixed `html/template` and `text/template` pkg types?

**Comment by mahesh-riddles** [comment]
> Yes, you can. See https://github.com/go-chi/chi/blob/master/_examples/rest/main.go#L146
> 
> Perhaps you mixed `html/template` and `text/template` pkg types?

I think you are right. I should have done this mistake.
I actually changed the code.
I am using struct based handler in which I am sending the template.

But I will check this out and update it. 
But more than 100% you are right. I must have mixed the pkg types.
