### ISSUE TITLE
Mount isn't compositing the route patterns

### ISSUE THREAD

**Issue by joaoschoen** [go-chi/chi#851]
func main() {
	router := chi.NewRouter()
	router.Use(middleware.Logger)
	router.Mount("/album", view.AlbumRouter())
	http.ListenAndServe(":3000", router)
}

func AlbumRouter() http.Handler {
	router := chi.NewRouter()
	router.Get("/", controller.GetAlbum)
	router.Post("/", controller.PostAlbum)
	return router
}
These bits of code are in two separate files

This code should attribute all routes inside my AlbumRouter to the pattern "/album", but no, it's not doing that, if I try to make a request this way I'll get:

2023/09/20 07:43:24 "GET http://localhost:3000/album/ HTTP/1.1" from 127.0.0.1:33092 - 404 19B in 30.47µs

This log, which tells me that the route doesn't exist, why that's odd, but then if I rename the pattern inside of my AlbumRouter function to "/album", which then considering I'm mounting this to my server router using "/album", any sane person would think that the final route would be "/album/album" 

func AlbumRouter() http.Handler {
	router := chi.NewRouter()
	router.Get("/album", controller.GetAlbum)
	router.Post("/album", controller.PostAlbum)
	return router
}

But no: 

2023/09/20 07:43:30 "GET http://localhost:3000/album HTTP/1.1" from 127.0.0.1:33092 - 200 13B in 11.31µs

So the router is messing up something while trying to composite the route tree

**Comment by pkieltyka** [comment]
Try the example in https://github.com/go-chi/chi/tree/master/_examples/rest and work from that
