### ISSUE TITLE
log/slog's LogAttrs (and other methods) now requires a context as their first argument

### ISSUE THREAD

**Issue by mhghw** [go-chi/chi#858]
Hi, I was looking around the examples and in the logging example I found this struct that satisfies the `middleware.LogEntry` interface:
```
type StructuredLoggerEntry struct {
	Logger *slog.Logger
}

func (l *StructuredLoggerEntry) Write(status, bytes int, header http.Header, elapsed time.Duration, extra interface{}) {
	l.Logger.LogAttrs(slog.LevelInfo, "request complete",
		slog.Int("resp_status", status),
		slog.Int("resp_byte_length", bytes),
		slog.Float64("resp_elapsed_ms", float64(elapsed.Nanoseconds())/1000000.0),
	)
}

func (l *StructuredLoggerEntry) Panic(v interface{}, stack []byte) {
	l.Logger.LogAttrs(slog.LevelInfo, "",
		slog.String("stack", string(stack)),
		slog.String("panic", fmt.Sprintf("%+v", v)),
	)
}
```

Since its using `log/slog` as its logger, the LogAttrs method for the `log/slog` is changed from 
`func (l *Logger) LogAttrs(level Level, msg string, attrs ...Attr)`

to 

`func (l *Logger) LogAttrs(ctx context.Context,level Level, msg string, attrs ...Attr)`

and well, your example is not working anymore.

I read the source code and I couldn't figure out why there is a context passing around but it seemed that we can pass context.Background() to the `LogAttr` method (or even nil) and `log/slog` package handles it.

Can you please clarify the usage of context in here for me and see if it's possible to change the `middleware.LogEntry` interface that we could send the request context as an argument to use in `log/slog` methods.

Thank you very much.

**Comment by VojtechVitek** [comment]
slog support was added in https://github.com/go-chi/chi/pull/771

@ydarb mind taking this one please?

**Comment by mcosta74** [comment]
I just want to add that 

```go
slogJSONHandler := slog.HandlerOptions{
    // Remove default time slog.Attr, we create our own later
    ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
        if a.Key == slog.TimeKey {
            return slog.Attr{}
	}
	return a
    },
}.NewJSONHandler(os.Stdout)
```

is no longer valid. The following is the right syntax

```go
slogJSONHandler := slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
    // Remove default time slog.Attr, we create our own later
    ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
        if a.Key == slog.TimeKey {
	    return slog.Attr{}
	}
	return a
    },
})
```

**Comment by pkieltyka** [comment]
https://github.com/go-chi/httplog/releases/tag/v2.0.0 is out built on "log/slog" and has lots of little nice features including a pretty logger when printing to stdout tty
