### ISSUE TITLE
Feature: on Go 1.22 pattern can start with an optional HTTP Method

### ISSUE THREAD

**Issue by sonatard** [go-chi/chi#895]
Since Go 1.22, it has become possible to specify HTTP Methods in the Path. Does chi plan to support this feature?

```go
mux := http.ServeMux()
mux.Handle("GET /user/{id}", userHandler)
```

https://github.com/golang/go/issues/61410

**Comment by pkieltyka** [comment]
are you wondering if chi's .Handle() method should also support the method prefix..? we certainly could add support for it pretty easily without any breaking changes. If others want it as well, I'll add it

**Comment by sonatard** [comment]
> are you wondering if chi's .Handle() method should also support the method prefix..?

👍 

```go
r := chi.NewRouter()
r.Handle("GET /user/{id}", userHandler)
```

**Comment by Spartan09** [comment]
> are you wondering if chi's .Handle() method should also support the method prefix..? we certainly could add support for it pretty easily without any breaking changes. If others want it as well, I'll add it

Can I give it a shot?

**Comment by Spartan09** [comment]
I have opened a [pull request](https://github.com/go-chi/chi/pull/897)

**Comment by pkieltyka** [comment]
merged :) thanks @Spartan09 for the PR
