### ISSUE TITLE
High CPU usage by chi.setPathValue

### ISSUE THREAD

**Issue by aadi-1024** [go-chi/chi#916]
Hello

I'm not sure if this is an issue with Chi or somewhere in my own application, but the `setPathValue()` function seems to be causing very high CPU usage for me. It seems to be due to the hashing taking place in the function(pardon if I'm wrong) as I could infer from the pprof profile output.

![image](https://github.com/go-chi/chi/assets/90773264/7ce85a33-fbb3-42e0-8745-c5f303089428)

The generated chart:

![image](https://github.com/go-chi/chi/assets/90773264/a133f24e-7894-4081-ae5d-e409ffdfe190)

Any help appreciated!

**Comment by aadi-1024** [comment]
![image](https://github.com/go-chi/chi/assets/90773264/e25d253b-0709-4c38-b7ec-457d7f01dd3d)

could this be the issue? all the entries are just `"*"`

**Comment by aadi-1024** [comment]
A bit more digging around and it seems mounting a group with a prefix "/" causes this. I'll look into a bit more to see if I can fix this

**Comment by VojtechVitek** [comment]
Any other volunteers to look into this? Or should we close?

**Comment by aadi-1024** [comment]
I'll be looking into this again once I can manage some time :). Till then I suppose we can close this, I'll open a new issue if I'm able to solve it. Or maybe can just wait for other volunteers to chime in.
