### ISSUE TITLE
weird conflict of router

### ISSUE THREAD

**Issue by qeatzy** [go-chi/chi#929]
`$ go run main.go
`
`$ curl http://localhost:8080/default.js
`
404 page not found
`$ curl http://localhost:8080/canvas
`

```
  <head>
  <script src="/default.js"></script>
  </head>
  <body>
<canvas id="test-canvas" width="300" height="200" style="border:2px solid black;"></canvas>
  </body>

```

```
//main.go
package main

import (
	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"net/http"
)

func main() {
	r := chi.NewRouter()

	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.URLFormat)

	r.Get("/default.js", func(w http.ResponseWriter, r *http.Request) {
		// render.WriteContentType(w, "js")
		w.Write([]byte(`
		var canvas = document.getElementById("test-canvas");
		`))
	})

	r.Get("/canvas", func(w http.ResponseWriter, r *http.Request) {
		// render.WriteContentType(w, "html")
		// <canvas id="test-canvas" width="300" height="200"></canvas>
		w.Write([]byte(`
		<head>
		<script src="/default.js"></script>
		</head>
		<body>
		<canvas id="test-canvas" width="300" height="200" style="border:2px solid black;"></canvas>
		</body>
		`))
	})

	http.ListenAndServe(":8080", r)
}



```
## Question

Why `curl http://localhost:8080/default.js` will report 404?

**Comment by VojtechVitek** [comment]
This makes no sense. Please update your chi to v5 -- you're running some old unsupported version. And please share a reproducer as a Go test or as a Github repo which we can easily run.

**Comment by qeatzy** [comment]
> This makes no sense. Please update your chi to v5 -- you're running some old unsupported version.

I am using recently version, since I installed go-chi only recently. suggested by some post, hoping it was helpful. How can I use a ancient version in this way?

> And please share a reproducer as a Go test or as a Github repo which we can easily run.
That's your opinion. I'm ok with that if told in a more constructive way. 

But still I don't don't see a simple reproducible file with a simple go run command and a curl command as http client has any pitfall or un-convenience.

While writing a client in a testing method is not that great, not all http client are written in go!!

Prove it, I'm using go chi version 5.

And still you are not answering the real question. 
> Why curl http://localhost:8080/default.js will report 404? 
Probably not even see the the simple code (which fill less than page, not even need to scroll.)

$ pwd
~/go/src/github.com/go-chi/chi
$ git log
commit 67be7d9cafdaeb4e04e887ff78d09e030ee43b00
Author: Patryk Kalinowski <patryk@kalinowski.dev>
Date:   Fri Jun 28 16:29:27 2024 +0200

    middleware: add Discard method to WrapResponseWriter (#926)
    
    * middleware: add Discard method to WrapResponseWriter
    
    * resolve review comments
    
    * use ioutil.Discard and deprecate the public interface
    
    * move the Discard method back to the public interface
    
    * discard calls to WriteHeader too

commit 7957c0d4ddaee560a01110145dbf2809ffdb6663
Author: Vojtech Vitek (golang.cz) <vojtech.vitek@gmail.com>
Date:   Fri Jun 21 08:30:42 2024 -0400

    Revert "fix(middleware): Close created writer in the compressor middleware (#…" (#924)
    
    This reverts commit f10dc4a9cab53a47f600f518fcccaa044666e95f.

commit f728a1c1976959d4a313da09bac44e88ec111917


Sorry for the later reply.

**Comment by VojtechVitek** [comment]
You need to update to chi v5.

```diff
import (
- 	"github.com/go-chi/chi"
- 	"github.com/go-chi/chi/middleware"
+ 	"github.com/go-chi/chi/v5"
+ 	"github.com/go-chi/chi/v5/middleware"
	"net/http"
)
```

`go get -u github.com/go-chi/chi/v5`
