### ISSUE TITLE
Middleware derived from Goji seems to be missing copyright notices

### ISSUE THREAD

**Issue by lhinderberger** [go-chi/chi#943]
Hello chi maintainers,

while having a look at chi's source code, I stumbled upon comments in the middleware package (e.g. chi/middleware/wrap_writer) saying that the code is derived from the Goji project.

While it looks like the original project also uses an MIT-style license, the original copyright notices were apparently not retained when copying the code to chi.

I want to bring this problem to your attention, but please be aware that I am not a lawyer and I cannot give legal advice.

**Comment by VojtechVitek** [comment]
Hi @lhinderberger,

Thanks for reporting this. Yes, some of the middleware code was indeed based on https://github.com/zenazn/goji/tree/master/web/middleware.

While this is attributed in both README.md and in individual middleware files, perhaps the license notice could have been copied over better? Do you have any recommendations?

Perhaps we could add https://github.com/zenazn/goji/blob/master/LICENSE#L1 to middleware/LICENSE or append it to the main LICENSE file. Thoughts @pkieltyka ?

**Comment by pkieltyka** [comment]
it's a good question what is the correct attribution for using some of goji's code in the middleware. We do have lines such as https://github.com/go-chi/chi/blob/master/middleware/wrap_writer.go#L3 anywhere we use Goji code, and in our README under Credits we also reference Goji. https://github.com/go-chi/chi/tree/master?tab=readme-ov-file#credits

I think the next thing would be to link to the Goji LICENSE file in the credits section.

If anyone has any other suggestions, please let us know.

**Comment by pkieltyka** [comment]
https://github.com/go-chi/chi/pull/944

**Comment by pkieltyka** [comment]
It's a standard MIT license, which is also the license of chi, so I think its okay. I'll merge the PR and close this ticket. Thanks for your suggestions.
