### ISSUE TITLE
SetWriteDeadline not supported

### ISSUE THREAD

**Issue by jzillmann** [go-chi/chi#947]
Using `huma` on top of `chi` and running into https://github.com/danielgtaylor/huma/issues/491 which means a constant logging of `warning: unable to set write deadline`.
My uneducated guess is that the go standard connection (https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/net/net.go;l=119) supports the `SetWriteDeadline` but chi's wrapper not !?

**Comment by VojtechVitek** [comment]
Hi,

Chi's `ResponseWriter` implements `Unwrap()` method.

So I believe if Huma used `http.ResponseController` properly, it would work fine.
I'll leave this to https://github.com/danielgtaylor/huma/issues/491.

Feel free to reopen with a minimal reproducer code if this is indeed Chi bug.

Thanks.
